### ISSUE TITLE
ZuulFilter.processFilter should not throw Throwable 

### ISSUE THREAD

**Issue by baylisscg** [Netflix/zuul#10]
As implemented Zuul manages filters as ZuulFilters instead of IZuulFilter. ZuulFilter's `runFilter()` method throws Throwable necessitating any code that starts filter processing to catch Throwable which is considered bad practice as it catches *all* errors including JVM ones.

Quite what the fix would be I'm uncertain about. Simply switching Throwable for ZuulException in ZuulFilter and FilterProcessor would do it. There's probably scope for adding ZuulError and some more specific subclasses too.

**Comment by kerumai** [comment]
Closing this as unlikely worth changing for Zuul 1.x
