### ISSUE TITLE
Can't use ZuulException in the filters

### ISSUE THREAD

**Issue by KhodyrevDS** [Netflix/zuul#101]
You cant use ZuulException  in the filter's run method because run not throws ZuulException  and ZuulException  is not RuntimeException

**Comment by apatil4** [comment]
+1 on that issue. We can workaround that but with unnecessary logic of putting the exception in Request Context. Also the try - catch block in ZuulServlet serves no purpose if exceptions are happening in the filters and the error filters cannot be executed at all.

Can the run method in IZuulFilter interface throw a ZuulException. In that case  any other Exceptions in the filters can be wrapped in the ZuulException. 

If the above approach is fine, I can submit a pull request

**Comment by hanshesse** [comment]
+1.  I'm no groovy expert, but appears that groovy doesn't have the same checks and allows the exception to be thrown.  See e.g. https://github.com/Netflix/zuul/blob/1.x/zuul-netflix-webapp/src/main/groovy/filters/pre/Routing.groovy

**Comment by sarpk** [comment]
Any update on this?? I'm also having the same issue

**Comment by Aloren** [comment]
Why pull request was closed? :( I also need this. Currently throwing zuul exception is a headache in java code

**Comment by robinvandenberg** [comment]
+1

There is a workaround (https://jmnarloch.wordpress.com/2015/09/16/spring-cloud-zuul-error-handling/) but that feels quite dirty and is creating more overhead than needed. It would be nice to throw a ZuulException with statuscode + errormessage from a filter.

**Comment by mattnelson** [comment]
> Why pull request was closed? :( I also need this. Currently throwing zuul exception is a headache in java code

I was doing some cleanup on my fork and deleted the branch before it was merged, which auto closed the pull request. I can see about getting a new PR out, though keep in mind the PR was out there for 5+ months and not merged.
