### ISSUE TITLE
Trying to run zuul 2 sample but always got "Missing Endpoint filter, name = NO_ENDPOINT_NAME"

### ISSUE THREAD

**Issue by YumiSuki** [Netflix/zuul#1054]
# Problems
I am trying to learn zuul 2 by running zuul2-sample and then got  `[Salamander-ClientToZuulWorker-6] ERROR com.netflix.zuul.filters.endpoint.MissingEndpointHandlingFilter - Missing Endpoint filter, name = NO_ENDPOINT_NAME`  when perform HTTP GET request to zuul (http://localhost:9090). 

# What have I done? 
I have clone and build zuul master without any problems and then I have disable eureka because it is always giving an error using these two properties configration:
```
eureka.validateInstanceId=false
eureka.shouldFetchRegistry=false
```

And then change zuul port to 9090 so I can access it easily using:
```
zuul.server.port.main=9090
```

# Questions
1. What have I done wrong and how can I fix it?
2. How can I use zuul 2 for reverse proxy? Sample, tutorial or document would be helpful.

Any help would be appreciated. Thanks.

**Comment by rab4u** [comment]
I'm also facing the similar issue : 
Error Information [Salamander-ClientToZuulWorker-0] com.netflix.zuul.filters.endpoint.MissingEndpointHandlingFilter.apply(MissingEndpointHandlingFilter.java:46)evel com.netflix.zuul.filters.endpoint.MissingEndpointHandlingFilter.apply(MissingEndpointHandlingFilter.java:46)ogger{36} - Missing Endpoint filter, name = com.netflix.sample.zuul.filters.outbound.ResponseFilter

There is no other logs or stack-trace. couldn't figure out how to fix the issue - Any help is much appreciated

**Comment by YumiSuki** [comment]
Anyone help please? @SMakhrov @carl-mastrangelo @@artgon
