### ISSUE TITLE
Cannot Initialize zuul

### ISSUE THREAD

**Issue by FazlanFarook** [Netflix/zuul#1074]
I have tried to initialize the zuul project, but the option is disabled in the dependency,

Please find the screenshot below
![Screenshot from 2021-06-08 16-47-26](https://user-images.githubusercontent.com/21996917/121188007-b9477c80-c879-11eb-9d58-3efc12978a99.png)

**Comment by VisionaryAppDev** [comment]
As far as i know, Spring support only zuul 1 and replace zuul with their Spring Cloud Gateway after that.
