### ISSUE TITLE
(Documention) zuul-simple-webapp reference to missing javaPreFilter and javaPostFilter 

### ISSUE THREAD

**Issue by charleswhchan** [Netflix/zuul#108]
In the wiki for [Simple Example App: zuul-simple-webapp](https://github.com/Netflix/zuul/wiki/zuul-simple-webapp), there are references to javaPreFilter and javaPostFilter.

I was not able to find these files in the repo anymore. Perhaps the documentation is out of date?

**Comment by ap-ensighten** [comment]
https://github.com/Netflix/zuul/blob/1.x/zuul-simple-webapp/src/main/java/com/netflix/zuul/StartServer.java#L69
