### ISSUE TITLE
Warning unknown channel options - SO_KEEPALIVE, SO_LINGER, TCP_NODELAY

### ISSUE THREAD

**Issue by lavsurgut** [Netflix/zuul#1085]
Hello guys,
I launched the zuul-sample project (tag v2.3.0) using adoptopenjdk-8.jdk on my MacOS laptop and see folllowing warnings:

WARN  ServerBootstrap:464 - Unknown channel option 'TCP_NODELAY' for channel '[id: 0x9c604ef6]'
WARN  ServerBootstrap:464 - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x9c604ef6]'
WARN  ServerBootstrap:464 - Unknown channel option 'SO_LINGER' for channel '[id: 0x9c604ef6]'

E.g - this seems to be ignored:
https://github.com/Netflix/zuul/blob/master/zuul-core/src/main/java/com/netflix/zuul/netty/server/Server.java#L252
when setting up the server.

Could you please clarify if its important warnings or they can be ignored?

**Comment by artgon** [comment]
They can be ignored when running locally on your laptop.
