### ISSUE TITLE
Idle timeout in CommonChannelConfigKeys kicking in when using ribbon

### ISSUE THREAD

**Issue by lenyt** [Netflix/zuul#1097]
Hello,

This is likely to be some config problem on our part but we find that when we are using ribbon and setting read timeout it does take effect if it is less than 65 seconds but if it is larger than 65 seconds, idle timeout that's set by BaseZuulChannelInitializer.addTimeoutHandler which sets it to 65 seconds (value from CommonChannelConfigKeys) kicks in at 65 seconds and winds up returning 504.

We are using netflix-zuul 2.1.6. We are using ribbons and not using eureka. For example, some configuration we are setting are:

myclient.ribbon.listOfServers=localhost:8888
myclient.ribbon.ReadTimeout=90000
myclient.ribbon.ConnectTimeout=10000

eureka.registration.enabled=false
eureka.shouldFetchRegistry=false
eureka.validateInstanceId=false

Any insights into this would be appreciated.
Regards,
LT

**Comment by artgon** [comment]
You can override the idle timeout with the `server.connection.idle.timeout` property.

**Comment by lenyt** [comment]
Thank you Arthur! We tried it and as you said that property does override the idleTimeout from CommonChannelConfigKeys.
