### ISSUE TITLE
Zuul routing fails for POST request body with German / French / Chinese characters.

### ISSUE THREAD

**Issue by plsameera** [Netflix/zuul#1104]
The zuul filter throws Forwarding error when the POST request body has German / French / Chinese characters in SimpleHostRoutingFilter. The generic English characters seem to work fine. 

HttpServletRequest request = ctx.getRequest();
String charEncoding = request.getCharacterEncoding()

On inspecting the HttpServletRequest in the request context, the cachedcontent shows non-encoded character symbols for few of the  German / French / Chinese letters. The character encoding shows "UTF-8" but still the characters still don't work.

Spring Boot Version - 2.4.3
Spring Cloud Version - 2020.0.2
Netflix-zuul Version - 2.2.8.RELEASE

**Comment by artgon** [comment]
We do not support the Spring integration.
