### ISSUE TITLE
Disable logging of DefaultLastHttpContent

### ISSUE THREAD

**Issue by tussinha** [Netflix/zuul#1114]
We are facing an issue where our log files are getting overwhelmed by READ and WRITE logs of DefaultLastHttpContent.
Is there an option to disable logging  of DefaultLastHttpContent only?

`_, {"instant":{"epochSecond":1633329330,"nanoOfSecond":825000000},"thread":"Salamander-ClientToZuulWorker-0","level":"INFO","loggerName":"zuul.server.nettylog","message":"[id: 0xbcea5352, L:/127.0.0.1:7001 - R:/127.0.0.1:56226] WRITE: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 60, cap: 60/60, unwrapped: PooledUnsafeDirectByteBuf(ridx: 668, widx: 668, cap: 1024)), decoderResult: success), 60B\r\n         +-------------------------------------------------+\r\n         |  0  1  2  3  4  5  6  7  8  9  axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              |.....ceL)...    |\r\n+--------+-------------------------------------------------+----------------+","endOfBatch":true,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":43,"threadPriority":5,"timestamp":"2021-10-04T12:05:30.825+0530"}_`

**Comment by argha-c** [comment]
As long as you're using the `log4j` logger, you can disable/force logging at higher severity with a FQDN. See [the sample log config](https://github.com/Netflix/zuul/blob/master/zuul-sample/src/main/resources/log4j2.properties#L18-L19) for an example.
