### ISSUE TITLE
Zuul as file upload proxy

### ISSUE THREAD

**Issue by aivans** [Netflix/zuul#113]
Did anyone use Zuul in the context of file upload proxy?

I would be interested in a filter implementation where the request is simply relayed to the origin server and not as a 2 step operation where the entire content is received in Zuul and a separate connection to the origin is made afterwards.

Thanks

**Comment by wmfairuz** [comment]
Hi,
Any updates on this issue? I'm interested to know if someone has implemented this.

**Comment by aivans** [comment]
@wmfairuz 
Maybe take a look here: https://github.com/spring-cloud/spring-cloud-netflix/issues/254

**Comment by wmfairuz** [comment]
@aivans thanks!
