### ISSUE TITLE
Zuul2 Connection Pool Settings

### ISSUE THREAD

**Issue by rajc28** [Netflix/zuul#1172]
Hi Team , I am having hard time understanding the below connection settings and how they are inter-related. Can someone provide more details on it.
```
Ribbon Client Config Property
<originName>.ribbon.MaxConnectionsPerHost 

Zuul Properties
<originName>.netty.client.maxRequestsPerConnection
<originName>.netty.client.perServerWaterline 
```
And In Zuul2 documentation I see this point **Zuul does not use Ribbon for making outgoing connections and instead uses its own connection pool, using a Netty client.** Does this mean the ribbon property **originName
.ribbon.MaxConnectionsPerHost** is not used by zuul ?

We have a scenario where we are using same origin host for multiple services where we are observing issues between zuul and origin, what is the best approach and better connection pool settings.

```
Example:
originName1 goes to origin host1
originName2 goes to origin host1
'
'
originNameN goes to origin host1
```

At present we are using below connection pool settings

```
<originName>.ribbon.MaxConnectionsPerHost=-1

<originName>.netty.client.maxRequestsPerConnection = 10000
<originName>.netty.client.perServerWaterline = -1
```

And do we need to tweak any other connection property for better results ?

**Comment by artgon** [comment]
Zuul will respect the Ribbon properties to bootstrap a connection but it doesn't use the client itself. What kind of issues are you running into?

**Comment by rajc28** [comment]
We are getting lot of 504's and 502's during high traffic which is 10k req/sec.

And also I see a point **Zuul creates a connection pool per host, per event loop ** , does the **host** in this context mean origin host or zuul host ?

**Comment by artgon** [comment]
"Host" there refers to the origin server. See [benchmarking section](https://github.com/Netflix/zuul/wiki/Benchmarking) for sample config to run high RPS tests.

**Comment by mehmetgul** [comment]
I have question on <originName>.netty.client.perServerWaterline          // default: 4
I was testing the connection limits and I set the perServerWaterline=1 and run performance test for 20K req/min and 40K req/min with 1 sec, 2sec and 4sec delay. Total 5 test. (Attaching the brief test result)
I know that this property is for per server, per event loop and per event is for 1 CPU.
So we are having 2 container and each container having 2CPU. 
Base on my test results the error rates are very less despite of setting the limit 1.
Do we suppose to set another property along with this or this property is meant to handle in different way?

<img width="1620" alt="Performance Test Results" src="https://github.com/user-attachments/assets/7afd20ed-e930-4a9a-9266-dc90b9b43f0d">
