### ISSUE TITLE
How to run Zuul 2 sample in local

### ISSUE THREAD

**Issue by DevArunLingala** [Netflix/zuul#1177]
As per Zuul Sample app [properties](https://github.com/Netflix/zuul/blob/master/zuul-sample/src/main/resources/application.properties), it sounds we need to run it for a target AWS zone

```
region=us-east-1
```

 but I would like to run it in local and test it. 
 
 Please help me how to run it in local machine and test Filters & Websockets/SSE

**Comment by keedosn** [comment]
try to set eureka.region=default in application.properties
