### ISSUE TITLE
Hateoas links broken

### ISSUE THREAD

**Issue by sfat** [Netflix/zuul#124]
Hi,
I am trying to make use of zuul in my project. (I am making use of Zuul, Eureka and Spring boot, of course)
I have a service "users" (port: 9002) and another spring boot app, which is the UI part + backend stuff (port: 8080).

My zuul configuration:

```
zuul:
  routes:
    users:
      serviceId: users 
      path: api/users/**
```

The problem that I think it's the problem is that I have set on the second app (UI and whatnot) a contextPath: /myContextPath

When I access my service through the proxy I basically access it via http://localhost:8080/myContext/api/users/api
But looking at the hateoas urls, the urls look like http://localhost:8080/api/users/api/blahblah

I presume you can't specify to zuul a relative path (I think I looked a bit over the code while debugging and I saw that it explicitly puts a "/" when you specify a relative path.

Is this a bug or I am missing something?
I presume if I strip out the contextPath for my app it should resolve, but I need the contextPath in my case.

**Comment by spencergibb** [comment]
I'm pretty sure you want to file this issue here https://github.com/spring-cloud/spring-cloud-netflix/issues, the core zuul project has no knowledge of `zuul.routes.*` or spring-boot.

**Comment by sfat** [comment]
@spencergibb oh, my bad. Thanks for the tip
