### ISSUE TITLE
Question: any ETA on Zuul 2?

### ISSUE THREAD

**Issue by thjaeckle** [Netflix/zuul#130]
We're using Zuul together with spring cloud Netflix as our api gateway and have a custom ZuulFilter for authentication against a remote system. 
This is why we are interested in an asynchronous filter mechanism as we fear many concurrent users authenticating at the api gateway would lead to many blocked threads which limits the total concurrent users using the api. 

So what's the plan for Zuul 2? Any release coming soon? 

Thanks. 
Sorry to post as github issue, but I didn't find another possibility to get in touch.

**Comment by alexpanov** [comment]
@thjaeckle 
Please take a look at #139 which answers a similar question.

**Comment by NiteshKant** [comment]
Closing this as it is a duplicate. #139 is the primary issue we can discuss NIO, non-blocking, reactive Zuul implementation questions.
