### ISSUE TITLE
In Zuul2 make it configurable on whether or not to block startup on groovy compile fail.

### ISSUE THREAD

**Issue by dstengle** [Netflix/zuul#132]
If a groovy file fails to compile on original startup, I'd much prefer to have the zuul instance bomb out than potentially have an unsafe edge security situation due to an important filter missing.

On the other hand, if a groovy file fails to compile during reload (which is also questionable in general) then it would be okay to skip in order to keep the server running. Ideally, it would be possible to have an atomic operation in case filters are related in some way that would cause a runtime exception or change in behavior if one is loaded and not the other.

**Comment by NiteshKant** [comment]
@dstengle I agree with your comment about startup failing if a filter fails to compile and ignore if the filter changed and compilation fails.

I am not sure about the filter dependency and atomic upgrade, I personally believe that it makes things too complex specifically introducing dependency management of sorts between filters. 

Are you interested in working on the startup failure change?

**Comment by dstengle** [comment]
@NiteshKant  Sure, I can give this a try. Need to clear up what we want to do, though.

If we ignore, for the moment, that a failure to reload one out of two filters could cause other runtime problems to happen due to context vairables not getting set, etc, the change is a lot simpler.

In this case, it seems like we would want two behaviors:

 - during init, propagate exceptions and prevent zuul startup, since there is a large potential for a bad situation
 - post-init, catch exceptions and log, but continue, since everything might just be okay.

FilterFileManager looks like it has an init() where we can differentiate between these two.

The other question is whether to make this a configurable item and let people start up a zuul that might not have all of the intended filters.

**Comment by NiteshKant** [comment]
Great, will look forward to the changes. 

Yes the two behaviors you have specified is what make sense to me.

I am not a fan for driving such behaviors through configuration. I think what will be good is if `FilterFileManager` takes an argument in the constructor to continue if filters fail and anyone who wants to change this behavior can bind an instance of the same with the appropriate flag.
