### ISSUE TITLE
Question: Zuul to behave like a reverse proxy

### ISSUE THREAD

**Issue by BenDave** [Netflix/zuul#133]
One of the purposes of Zuul is to act as a reverse proxy.

However Zuul only redirects clients to the destination URL, as opposed to transparently forwarding the requests. As a result the destination URL is exposed to the client through the 302 redirect, which is not how reverse proxies behave.

Is there documentation / workaround to make zuul behave as a true reverse proxy ?

**Comment by manuelcorrea** [comment]
You will need to implement your Redirect Strategy in the routing filter
https://github.com/Netflix/zuul/blob/1.x/zuul-netflix-webapp/src/main/groovy/filters/route/ZuulHostRequest.groovy#L161

**Comment by NiteshKant** [comment]
@BenDave Zuul sending a redirect to the destination isn't the way it is supposed to work. It does behave like a reverse proxy. Can you share your setup with us to provide more context on where you are seeing this behavior?

**Comment by fahimfarookme** [comment]
@BenDave I'm also currently facing this issue. Have to found any fix?

**Comment by pakizito** [comment]
Good evening, 
I'm building something like what is described here. I would like zuul to act as reverse proxy like a load balancer aware of the ui instances (eureka). All work, but when i login in the ui instance, zuul redirects to the instance which I didn't want. What I want is something like zuul, but which mantain the url and is aware of the sessions to each instance, like sticky sessions. Is this possible with zuul? I tried several approaches like oauth2 which does this (url is always the same) but i had some issues with ajax calls in the ui instances. 
What should I look for? 
I'm going to try this filter, this one i didn't try. 
I'm loving spring cloud guys, really great job! Congrats. 
With kind regards, 
Rodrigo Carvalheira

**Comment by istonikula** [comment]
I'm seeing something similar with minimal zuul config: an application using spring security (form login) that sits behind zuul proxy. Here are links to the projects:
- proxy:  https://github.com/istonikula/proxy
- app: https://github.com/istonikula/demo

Without the proxy, when navigating to http://localhost:8180/user1/rows the user is redirected to login page http://localhost:8180/login as expected.

With a simple nginx reverse proxy setup like this:
        location / {
            proxy_pass http://127.0.0.1:8180;
        }

the setup also behaves as I expect, i.e. when navigating to http://localhost:8080/user1/rows the user is redirected to login page http://localhost:8080/login.

However, if I replace nginx with the proxy project that uses zuul, navigating to http://localhost:8080/user1/rows is redirected to tp://localhost:8180/login

**Comment by spencergibb** [comment]
@istonikula your question should go in spring-cloud-netflix, not here.
