### ISSUE TITLE
Question: Is there a way to set connection timeout and socket timeout for only specific endpoints?

### ISSUE THREAD

**Issue by mkatircioglu** [Netflix/zuul#135]
I am using Zuul as a API Gateway and it works well. But I need to change connection timeout and socket timeout while uploading file through the api gateway. I have used  zuul.host.connect-timeout-millis and zuul.host.socket-timeout-millis properties but this properties definition affect all endpoints?

Is there a way to set timouts for only specific endpoints?

**Comment by maxiplay** [comment]
+1

**Comment by kerumai** [comment]
If you're using Zuul with Ribbon, then these timeouts can be configured _per ribbon client_. ie. you can configure them differently for each uniquely named ribbon client.

eg. if I'm setting my routeVIP to "myorigin1" (`RequestContext.currentContext.routeVIP=myorigin1`), then I can set the timeouts with these properties:
```
myorigin1.ribbon.ConnectTimeout=3000
myorigin1.ribbon.ReadTimeout=3000
```
See https://github.com/Netflix/ribbon/wiki/Getting-Started

If you're not using Ribbon (ie. your using the ZuulHostRequest route filter) then it's not possible to do this. But feel free to submit a PR to add this functionality to that filter.

**Comment by xiaominger** [comment]
hello,have you added this functionality?

**Comment by xiaominger** [comment]
> If you're using Zuul with Ribbon, then these timeouts can be configured _per ribbon client_. ie. you can configure them differently for each uniquely named ribbon client.
> 
> eg. if I'm setting my routeVIP to "myorigin1" (`RequestContext.currentContext.routeVIP=myorigin1`), then I can set the timeouts with these properties:
> 
> ```
> myorigin1.ribbon.ConnectTimeout=3000
> myorigin1.ribbon.ReadTimeout=3000
> ```
> 
> See https://github.com/Netflix/ribbon/wiki/Getting-Started
> 
> If you're not using Ribbon (ie. your using the ZuulHostRequest route filter) then it's not possible to do this. But feel free to submit a PR to add this functionality to that filter.

hello,have you added this functionality?
