### ISSUE TITLE
Does Zuul2 Support Injection of an Additional Proxy before Message Reaches the Origin?

### ISSUE THREAD

**Issue by jhareuk** [Netflix/zuul#1355]
We are currently using Zuul `2.1.9` as our gateway. I have an HttpInboundSyncFilter that I want to use to inject a proxy call between zuul and the origin service when a certain criteria is met on a request. A cURL example (from Zuul) would look like this `curl --proxy http://my-proxy.com:8080 https://my-service/endpoint`.

Is this something that Zuul2 even supports? I'm not sure if Netty even supports it. I'm trying to find a good example on either but coming up short.

**Comment by bitcras** [comment]
> proxy
