### ISSUE TITLE
Question - non blocking / reactive reverse proxy with Zuul 

### ISSUE THREAD

**Issue by lukestephenson** [Netflix/zuul#139]
I’ve been looking at the zuul simple example which forwards requests onto http://apache.org.  I was expecting this to make use of a non blocking api for scalability.  However all the examples block on the call to the API which is proxied.  If that service experiences a slow down, then that propogates into zuul by blocking a thread.

All the state in RequestContext is held against a ThreadLocal, so it doesn’t appear like the implementation can respond asynchronously.

What am I missing?  How can this be used as a scalable solution for microservice proxying?

Thanks

**Comment by NiteshKant** [comment]
@lukestephenson We are working on a non-blocking version of Zuul and the development work is happening under the [2.x branch](https://github.com/Netflix/zuul/tree/2.x)

**Comment by lukestephenson** [comment]
What's the timeline for version 2?  Took a quick browse of the code on that branch and it's looking very promising.

**Comment by NiteshKant** [comment]
@lukestephenson there isn't a concrete timeline for the completion of the 2.x work but I think we should have something concrete in a couple of months from now. I am closing this issue but feel free to discuss if you have more questions.

**Comment by lukestephenson** [comment]
Has there been much progression on zuul 2.x?
