### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by imnotpete** [Netflix/zuul#1439]
In the project README, under "Info and examples from various projects:", this link is broken:

> https://spring.io/guides/gs/routing-and-filtering/

Perhaps this is the new location?

> https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html

**Comment by nerdynikhil** [comment]
I can work on this. Could you assign it to me please @imnotpete ?

**Comment by imnotpete** [comment]
Hi @nerdynikhil! I'm not actually a member of the project, don't think I have rights here to assign it to anyone.

**Comment by nerdynikhil** [comment]
Sorry about that, Sam. My bad.
