### ISSUE TITLE
How do I enable ZUUL_DEBUG, REQUEST_DEBUG logging.

### ISSUE THREAD

**Issue by micheal-swiggs** [Netflix/zuul#146]
According to this: https://github.com/Netflix/zuul/wiki/How-To-Use ZUUL_DEBUG and REQUEST_DEBUG should be enabled by default? However, going through our logs we just get INFO level logging. What do I need to change?

**Comment by manuelcorrea** [comment]
if you are using the simple app you can take a look at the Debug filter 
https://github.com/Netflix/zuul/blob/1.x/zuul-simple-webapp/src/main/groovy/filters/pre/Debug.groovy#L41

You need to set the archaius (system property) https://github.com/Netflix/zuul/blob/1.x/zuul-simple-webapp/src/main/groovy/filters/pre/Debug.groovy#L27  to true

Hope that helps.

**Comment by micheal-swiggs** [comment]
Thanks for the tip. Unfortunately I still can not getting it working. I copied the Debug filter into my project, but I'm still getting ordinary log messages. I modified the `filterType` method to: 

    public String filterType() {
        log.info("routing-debug {}", routingDebug);
        log.info("debug-parameter {}", debugParameter);
        return "pre";
    }

And from the logs I get:

    routing-debug DynamicProperty: {name=zuul.debug.request, current value=true}
    debug-parameter DynamicProperty: {name=zuul.debug.parameter, current value=d} 

So it appears that the properties have been set to correctly..

**Comment by bibordoloi** [comment]
Hi, has this been figured out? I dont think having the properties zuul.debug.request and zuul.debug.parameter is doing anything. DebugFilter reads these properties and collects logs but the messages dont get written out. I hope someone has found a workaround/solution as this has been out for a while. I am using the latest release 1.2.3.RELEASE.

**Comment by davidstack** [comment]
zuul-core 1.3.0 still have this problem

**Comment by eacdy** [comment]
I've found this problem , too.

**Comment by DiveInto** [comment]
same problem

and setting `zuul.debug.request=true` won't work, ref: http://stackoverflow.com/a/33837195/404145

**Comment by vasandharaj** [comment]
Zuul Team any update on this issue ??

**Comment by bleporini** [comment]
What I use: 
set `zuul.debug.request=true` AND register the following kind of filter:

```java
	@Bean
	public ZuulFilter zuulFilter(){
		return new ZuulFilter() {
			@Override
			public String filterType() {
				return "post";
			}

			@Override
			public int filterOrder() {
				return 999999;
			}

			@Override
			public boolean shouldFilter() {
				return true;
			}

			@Override
			public Object run() {
				final List<String> routingDebug = (List<String>) RequestContext.getCurrentContext().get("routingDebug");
				routingDebug.forEach(System.out::println);
				return null;
			}
		};
	}

```

**Comment by vasandharaj** [comment]
@bleporini 

If i set zuul.debug.request=true, then the entire zuul is not working. I am using 1.2.3.RELEASE

is there any specific release should i use for this ??

**Comment by bleporini** [comment]
I use `1.2.4.RELEASE` ,  I don't know if it makes the difference...

**Comment by vasandharaj** [comment]
@bleporini sorry for the late reply it worked for me. Thanks for your support

**Comment by swelltt0576** [comment]
hey guys,

is there any result?

**Comment by eacdy** [comment]
Semms that it helps. 
<https://github.com/spring-cloud/spring-cloud-netflix/issues/1691>

**Comment by yangzii0920** [comment]
Same issue.

**Comment by l0co** [comment]
This works for me, add it to `bootstrap.yml`:

```
debug: true
trace: true
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
```

**Comment by GenweiWu** [comment]
try set your log level to debug or trace,default is info

**Comment by ghsatpute** [comment]
I'm not able to get the final request logs i.e. final outgoing URL and Request body. There should be a way to log HTTP request and response in Zuul. 

Even though I set `logging.level.org.springframework.cloud.netflix = TRACE` I'm able to get information such as 
```
2019-07-10 14:52:34.322 DEBUG [<my app>] 30334 --- [nio-8001-exec-3] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='vehicles', path='/api/v1/vehicles/**', serviceId='null', url='http://localhost:8013/vehicles-service/**', stripPrefix=false, retryable=true, sensitiveHeaders=[], customSensitiveHeaders=false, }
```

But I'm not sure what's the final REST request that is being fired. Which I think is very important from the debuggging point of view.

**Comment by swelltt0576** [comment]
D




------------------ 原始邮件 ------------------
发件人: "chinaxing"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 下午5:30
收件人: "Netflix/zuul"<zuul@noreply.github.com>;
抄送: "许伟"<s.well.tt@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Netflix/zuul] How do I enable ZUUL_DEBUG, REQUEST_DEBUG logging.(#146)




I'm not able to get the final request logs i.e. final outgoing URL and Request body. There should be a way to log HTTP request and response in Zuul.
 
Even though I set logging.level.org.springframework.cloud.netflix = TRACE I'm able to get information such as
 2019-07-10 14:52:34.322 DEBUG [<my app>] 30334 --- [nio-8001-exec-3] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='vehicles', path='/api/v1/vehicles/**', serviceId='null', url='http://localhost:8013/vehicles-service/**', stripPrefix=false, retryable=true, sensitiveHeaders=[], customSensitiveHeaders=false, }  
But I'm not sure what's the final REST request that is being fired. Which I think is very important from the debuggging point of view.

**Comment by Trattaturen** [comment]
> I'm not able to get the final request logs i.e. final outgoing URL and Request body. There should be a way to log HTTP request and response in Zuul.
> 
> Even though I set `logging.level.org.springframework.cloud.netflix = TRACE` I'm able to get information such as
> 
> ```
> 2019-07-10 14:52:34.322 DEBUG [<my app>] 30334 --- [nio-8001-exec-3] o.s.c.n.zuul.filters.SimpleRouteLocator  : route matched=ZuulRoute{id='vehicles', path='/api/v1/vehicles/**', serviceId='null', url='http://localhost:8013/vehicles-service/**', stripPrefix=false, retryable=true, sensitiveHeaders=[], customSensitiveHeaders=false, }
> ```
> 
> But I'm not sure what's the final REST request that is being fired. Which I think is very important from the debuggging point of view.

Did you find a way to log the Response?
