### ISSUE TITLE
Is Zuul being maintained and enhanced so that it makes sense to build an API routing solution around it?

### ISSUE THREAD

**Issue by jongunnip** [Netflix/zuul#1562]
We are using Zuul as our API Gateway but we are wondering how long Zuul will be a good foundation for an API Gateway.  Zuul hasn't had a release for 2 years.  The commit history appears to be mostly dependency upgrades by dependabot and minor enhancements and fixes.  As API usage changes with new approaches, just wondering if it is likely this project will change to meet new challenges and opportunities.

**Comment by artgon** [comment]
Yes, Zuul is still supported and used widely in production.

**Comment by jongunnip** [comment]
Thanks for confirming @artgon.  We've been very happy with Zuul and impressed with how well it scales.
