### ISSUE TITLE
cannot see hystrix metrics from zuul in hystrix dashboard

### ISSUE THREAD

**Issue by uharband** [Netflix/zuul#166]
i'm using latest version of 1.x branch. i configured my origin to be called via the ribbon client. i'm invoking URLs on to my origin via zuul but i see no hystrix metrics on the hystrix dashboard.
i added the hystrix-metrics-event-stream as explained here:
https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream
dashboard IS connecting to the hystrix.stream exposed by the servlet but no data on the dashboard (remains 'loading')

**Comment by jaume-pinyol** [comment]
Hi,
Did you added it to the web.xml?

```xml
<servlet>
        <servlet-name>HystrixMetricsStreamServlet</servlet-name>
        <servlet-class>com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>HystrixMetricsStreamServlet</servlet-name>
       <url-pattern>/hystrix.stream</url-pattern>
    </servlet-mapping>
```

**Comment by jaume-pinyol** [comment]
Which url are you using in the dashboard?

**Comment by uharband** [comment]
Turns out i was using the wrong version of the event stream. When using the correct one all works as expected. 
Thanks

**Comment by jaume-pinyol** [comment]
:+1:
