### ISSUE TITLE
[1.x] How does de-activating a filter work?

### ISSUE THREAD

**Issue by germanattanasio** [Netflix/zuul#167]
how does zuul handle de-activating filters. If all the revision are de-activated at the same time, will it delete the filter from `FilterFileManager`

**Comment by NiteshKant** [comment]
@germanattanasio can you elaborate what do you mean by de-activating a filter?

**Comment by germanattanasio** [comment]
I want to deactivate a filter from zuul. The `filterLoader.jsp` allow me to do it with the click of a button:
![screen shot 2015-10-01 at 4 26 22 pm](https://cloud.githubusercontent.com/assets/313157/10232881/36847036-6859-11e5-9c73-816771e061cf.png)
 
But how does `FilterFileManager ` or `ZuulFilterPoller` handle the scenario where there is only one revision active. 

I'm asking this because I'm implementing the DELETE functionality, trying to delete filters from zuul by adding a `DELETE_zuul` row in `zuul_filter_indices`

**Comment by NiteshKant** [comment]
Ok thanks for the clarification. [This code](https://github.com/Netflix/zuul/blob/1.x/zuul-netflix/src/main/java/com/netflix/zuul/scriptManager/ZuulFilterDAOCassandra.java#L459) eventually gets invoked on deactivation, it does not look like there is any special handling for the case when all revisions are deactivated for a filter. The best way though to confirm is to try performing the action :)

Question though, if zuul deletes the filter on deactivation of all revs, how will anyone activate the filter at any later point in time?

**Comment by germanattanasio** [comment]
The problem with the current implementation is that even if you deactivate all the revisions for a filter, the last one that was active will still be active.

I built a web app that exposes CRUD operations for zuul filters and allow users to create filters by filling a form. I need to be able to delete filters.

**Comment by NiteshKant** [comment]
@germanattanasio great!
