### ISSUE TITLE
Recommended strategy for incorporating changes since last release v2.3.0 in April 2021

### ISSUE THREAD

**Issue by jongunnip** [Netflix/zuul#1674]
We have a fork of the last official Zuul release (v2.3.0 from April 2021).  It is a fork since we needed to make some minor changes to support our environment.  We've cherry-picked a couple of fixes from github master since 2.3.0.  We'd like to be closer to the latest so we are up-to-date on enhancements and fixes.  

Is there a recommended strategy for how to pull in changes since v2.3.0 since there hasn't been an official Zuul release since 2021?  Are there certain commit points on master that are considered particularly stable and would be recommended for using as a release?  Does netflix have a strategy for how it utilizes the changes since 2021 for its own production usage?  Thanks!

**Comment by sullis** [comment]
Hello! Thank you for opening an issue.  We will try to release a new version this week.

**Comment by jongunnip** [comment]
Great.  Thanks!

**Comment by sullis** [comment]
Zuul 2.4.0 has been published to Maven Central.
