### ISSUE TITLE
Publish 1.2.0 to maven central

### ISSUE THREAD

**Issue by spencergibb** [Netflix/zuul#174]
https://github.com/Netflix/zuul/releases/tag/v1.1.0-rc.2

It has been released, but not published.

**Comment by NiteshKant** [comment]
@spencergibb alright let me look at it.

**Comment by spencergibb** [comment]
@NiteshKant thanks!

**Comment by NiteshKant** [comment]
So, that was an "Oops release" that was never supposed to be made and to make it complex enough, it was supposed to be from the 2.x branch... 

So, as a "best possible solution" I am bumping up the current version of 1.x to 1.2.0 and releasing it now

**Comment by spencergibb** [comment]
Great, we were waiting for a fix on master too!

**Comment by spencergibb** [comment]
@NiteshKant any update?

**Comment by NiteshKant** [comment]
@spencergibb been busy and there are some publishing issues with the 1.x artifacts, which I need to resolve.
Apologies for the delay, we don't use 1.x anymore inside Netflix, so the builds have not been happening for a while.

**Comment by aivans** [comment]
@NiteshKant Considering the large community starting to use Zuul 1.x through Spring Cloud, I would appreciate if Netflix kept the rhythm going on the 1.x branch or release 2.x for public

I am planning this month to add Zuul as an API Gateway in our Architecture and it's a bit scary that we may be in no mans land for a while.

Do you suggest we keep things on hold until 2.x is public?

Thanks

**Comment by NiteshKant** [comment]
@aivans I surely understand your concern around 1.x. @polarbizzle is helping me fix the build & release job for 1.x, hopefully we should be able to release soon.

1.x has received some good PRs from the spring cloud folks, so I would say it is not in a no mans land. Once we figure out this build hickup, I am sure we are on track to release it faster in the future. Although, Netflix is working on 2.x so all changes would land there. I am certainly looking at starting a candidate for 2.x early Decemeber. If 1.x works for you I would suggest not to hold on for 2.x.

**Comment by aivans** [comment]
Thank you Nitesh. I appreciate your advice.
Great piece of engineering from Netflix. Spring Cloud makes it easier for us, Spring/Java houses to adopt, so great again!

**Comment by polarbizzle** [comment]
Sorry for the delay. I'm happy to note that zuul 1.1.0 final has been released to maven central! Let us know how it's working.

**Comment by aivans** [comment]
Thank you
