### ISSUE TITLE
Netflix zuul redirect

### ISSUE THREAD

**Issue by guymalachi** [Netflix/zuul#176]
Hi,

I'm using zuul proxy server as a reverse proxy.
I send http request that going through zuul server and when i get response with status code 3++ (redirect), the browser doing redirect and shows me the url of the real server.
How can i solve this problem ?

Thanks a lot

**Comment by NiteshKant** [comment]
You will have to write a filter for rewriting redirect location for the response that contains absolute URIs.

**Comment by guymalachi** [comment]
Thanks...
I get response with location header to the redirect server.
I wrote post filter that add header with my new location value  and the browser returns:
Duplicate headers received from server
ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION

How can i delete the origin location from header and insert my new one ?

Thanks

**Comment by lovechenrui** [comment]
I want import zuul to idea，But has been an error，Can anybody help me? the error is "Cause: repository not found: D:\projects\test\zuul-1.x"

**Comment by lrn2prgrm** [comment]
I want to use a reverse proxy only with Zuul (no spring cloud) and i cannot write my redirect rule, could you provide a simple example?

**Comment by michaelcizmar** [comment]
The location header is just like any other header.  Take a look at [326](https://github.com/Netflix/zuul/issues/326)
