### ISSUE TITLE
Post request with querystring

### ISSUE THREAD

**Issue by gmgmgmgm** [Netflix/zuul#178]
I think Zuul has bug in SimpleHostRoutingFilter.java.
When thos route filer is executed on post request it trying to create HttpPost object with URI encoder but there are some characters like pipe (|) that os not valid for URI and it throws exception for that value.
Am i right or i missing something ?

**Comment by ausmith** [comment]
I believe that issue was fixed with https://github.com/Netflix/zuul/pull/161, assuming I understand the question correctly.
