### ISSUE TITLE
Adding Groovy classes that are not a ZuulFilter

### ISSUE THREAD

**Issue by peerke** [Netflix/zuul#18]
As a enhancement I would like to request that it would be possible to add Groovy scripts that are not derived from ZuulFilter. This would allow us to make utility/helper classes that can be used in the filters.

**Comment by kerumai** [comment]
It is possible to do this by just including them into the build, eg. see `zuul-core/src/main/groovy/com/netflix/zuul/filters/SurgicalDebugFilter.groovy`
