### ISSUE TITLE
Zuul 2.x : Netty sample for performance testing 

### ISSUE THREAD

**Issue by kasun04** [Netflix/zuul#186]
Hi, 
Is there a sample based on Zuul Netty that can be used for a HTTP performance test? 
Can we use [1] with a few tweaks? Also, is there any performance turning guidelines for that. 

Thanks. 

[1] https://github.com/Netflix/zuul/tree/2.x/zuul-netty-sample

**Comment by NiteshKant** [comment]
@kasun04 sure that can be used as a starting point for a benchmark. What are you comparing against?
There aren't any performance tuning guidelines per se but here is what we tested sometime back:

[WSPerfLab](https://github.com/Netflix-Skunkworks/WSPerfLab)

and here is a [helloworld sample in RxNetty](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/perf/PerfHelloWorldServer.java)

**Comment by kasun04** [comment]
We would like to compare Zuul with a raw Netty based reverse proxy kind of a runtime. Also is there any comparison done against other similar solutions.

**Comment by mikeycohen** [comment]
We will be publishing performance results, etc once we are live with zuul 2 at netflix.
