### ISSUE TITLE
[ Low importance ] How are ports handled?

### ISSUE THREAD

**Issue by ericfrancis** [Netflix/zuul#195]
I have been troubleshooting an app that uses Zuul proxying.

application.properties
```server.port=8443
foo.bar.url=https://foo.bar.com:443/api/fooBar
zuul.routes.foobar.path=/api/fooBar/**
zuul.routes.fooBar.url=${foo.bar.url}
```
In the url, I am specifying port `443`; however, when I deploy my app, it listens on port `8443`. 
`Zuul` is then forwarding the request to `https://foo.bar.com:8443/api/fooBar`. 
Is this the default behavior of `Zuul`?

**Comment by spencergibb** [comment]
`zuul.routes.*` is a feature of [spring-cloud-netflix](https://github.com/spring-cloud/spring-cloud-netflix), not vanilla zuul. I'd suggest opening an issue there.

**Comment by ericfrancis** [comment]
@spencergibb awesome, thank you. I will close and link to my new issue. Thanks again.
