### ISSUE TITLE
Question - How to implement request throttling on ZUUL

### ISSUE THREAD

**Issue by pradeepsingh1234** [Netflix/zuul#196]
Do we have any in built feature in zuul to throttle request ?

**Comment by innokenty** [comment]
So.... any thoughts?

**Comment by pradeepkusingh** [comment]
There is no in-built feature available and I implemented custom one.

**Comment by innokenty** [comment]
@pradeepkusingh Wow! Yeah, I saw your stackoverflow question :) Can you share the code?

**Comment by pradeepkusingh** [comment]
I had to write down tocektbucket algorithm. I will try to share. but lot of example available online.

**Comment by schoberwirt** [comment]
+1 @pradeepkusingh that would be awesome to see a working sample of throttling in zuul

**Comment by kerumai** [comment]
At Netflix, we have multiple stages of rate-limiting and DDoS protections hosted in Zuul. 
The first stage uses a Token Bucket algo (as @pradeepkusingh suggests) as a low-overhead, per-server protection.
We then have more involved mechanisms that look for patterns of malicious activity, and feedback into Zuul where a user/client block is enforced.

Our Token Bucket impl isn't currently open-sourced, but I'd recommend using an existing impl like https://github.com/vladimir-bukhtoyarov/bucket4j .
