### ISSUE TITLE
How to forward error to customized error controller

### ISSUE THREAD

**Issue by WeipingGuo** [Netflix/zuul#200]
I created a customized ErrorFilter to suppress FilterError before sending back to clients. I can see the ErrorFilter is called, however, it does not forward to my error controller. instead of forwarding to tomcat error handling. 

I even changed the error path from /error to /myservice/error, but it still ends up with default tomcat error handling. I must have missed something obviously. The dispatcher seems org.apache.catalina.core.ApplicationDispatcher, not Spring Dispatcher. Any comments and suggestions are appreciated!

`RequestDispatcher dispatcher = ctx.getRequest().getRequestDispatcher(this.errorPath)
			if (dispatcher != null) {
				if (!ctx.getResponse().isCommitted()) {					
					dispatcher.forward(ctx.getRequest(), ctx.getResponse())
				}
			}`

**Comment by spencergibb** [comment]
This is not a spring project. Use spring-cloud-netfix for spring issues.

**Comment by WeipingGuo** [comment]
My bad, wrong board.
