### ISSUE TITLE
Impossible to read body in the post filter

### ISSUE THREAD

**Issue by dmydlarz** [Netflix/zuul#202]
How it is possible to read a response body while using Zuul as a proxy in `post` filter?

I am trying to call the code like this:

```java
@Component
public class PostFilter extends ZuulFilter {

    private static final Logger log = LoggerFactory.getLogger(PostFilter.class);

    @Override
    public String filterType() {
        return "post";
    }

    @Override
    public int filterOrder() {
        return 2000;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();
        ctx.getResponseBody(); // null

        // cant't do this, cause input stream is used later in other filters and I got InputStream Closed exception
        // GZIPInputStream gzipInputStream = new GZIPInputStream(stream);
        return null;
    }

}
```

But I get null with `getResponsyBody()`. Also I can't use InputStream because it's used by other filters, so I can't read it (cause it's closed, or other filters fails with exception that they use closed/ended stream)

**Comment by dmydlarz** [comment]
Hey, I've managed to overcome this, by reading InputStream to ByteArrayOutputStream and then copying OutputStream to two InputStream. The first I consumed as I wanted and second I passed later to `context.setResponseBody(inputStream)`

**Comment by txomon** [comment]
The current filters in the netflix simple webapp do this, making it impossible to use them as they are.

**Comment by dili91** [comment]
> The current filters in the netflix simple webapp do this, making it impossible to use them as they are.

Could you please link them here ? thanks
