### ISSUE TITLE
Unit tests in production code

### ISSUE THREAD

**Issue by Aloren** [Netflix/zuul#208]
I am not quite sure what was the initial idea of having unit tests along with junit and mockito dependencies in production code, but it seems strange. I suppose, it makes sense to move them to correct place like src/test/java? Thanks

**Comment by kerumai** [comment]
There are pro's and con's. In this case it was a preference of the engineers who first started this project.
I don't have a strong opinion on it either way, but at this point it's probably not a high enough priority to change.
