### ISSUE TITLE
Does zuul support longest prefix matching?

### ISSUE THREAD

**Issue by WeipingGuo** [Netflix/zuul#209]
Hi ,

I have two routes like:
/api/v0/  ---> sever 1
/api/v0/user ---> server 2

last time i checked, zuul did not support this kind of routes, it always routed to server 1.  Is this added now?

**Comment by spencergibb** [comment]
If you're using spring-cloud-netfix this isn't the right place to ask.

**Comment by WeipingGuo** [comment]
sorry, will ask the on the spring-cloud-netfix board.
