### ISSUE TITLE
Streaming file download through Zuul

### ISSUE THREAD

**Issue by ali2992** [Netflix/zuul#210]
Basically I'm trying to stream a file download through Zuul. When calling the service directly, the download streams fine, however when calling through Zuul it seems to download the file to zuul first and then stream it from there. For a large file this results in a "waiting connection" loop in the browser while zuul fetches the file AND THEN streams it out. Is there a way to have the stream be "passed through" zuul? I've tried custom response writing filters that specify Transfer-Encoding: Chunked, and I've set response headers etc, is there anything that I'm missing?

**Comment by pcornelissen** [comment]
I'm having the same issue with a big csv file that is generated in the backend. The server streams the output directly as chunked response. This works fine when I curl the service directly, but going through zuul sometimes leads to timeouts because it only starts transferring when the full response has been read :-(

**Comment by WiteCastle** [comment]
I know for large files you should bypass the Spring DispatcherServlet. I'm not sure if it'll help with large downloads but it's worth a shot.

http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_uploading_files_through_zuul

**Comment by pcornelissen** [comment]
I tried that, but it still buffered

**Comment by aivans** [comment]
Hi all,

I guess this is related to Spring Cloud.

Zuul by default does not buffer, unless something was changed very recently, but I doubt it.

Take a look here:
https://github.com/spring-cloud/spring-cloud-netflix/commit/053296de939831c4c72f6871d779f7cf4122c2c7

https://github.com/spring-cloud/spring-cloud-netflix/issues/773#issuecomment-172858499

The way we use Spring Cloud/Zuul, which by the way I think is the best way:
- map the ZuulServlet to "/"
- all request go straight through Zuul and not the Spring DispatcherServlet
- Spring features are used for the management endpoints, admin stuff, error handling and general Dependency Injection

**Comment by ali2992** [comment]
i have the ZuulServlet mapped to "/" also. I have just tried setting the ZuulServlet back to the default and then routing my download through "/zuul" but that is also still buffering. Is there any way I can verify that the spring dispatcher is not handling my request? is the spring dispatcherservlet named "dispatcherServlet" by default as that is the servlet that is always handling my requests looking at the console log

**Comment by ali2992** [comment]
the commit linked doesn't look like it has been applied in the version of spring-cloud-netflix-core that ANGEL.SR6 is using. (1.0.7.RELEASE)

**Comment by ali2992** [comment]
ok i've updated the stack to now use Brixton.SR1 however i am still seeing the buffering when bypassing the spring dispatcher

**Comment by ali2992** [comment]
ok, on further research this isn't a zuul issue, its buffering between the front end and the call to the gateway. calling the gateway directly and it streams fine. This can be closed

**Comment by kerumai** [comment]
@pcornelissen Zuul by itself should allow chunked responses through without buffering. And I just verified this still works (using zuul-simple-webapp).
Ensure you don't have request-debug enabled (ie. the `zuul.debug.request` property in zuul-simple-webapp) as that would cause response buffering.

**Comment by amitabhprasad** [comment]
@kerumai
We are running into exact same issue, 
https://github.com/spring-cloud/spring-cloud-netflix/issues/2773
Do you have any idea what else we can try.
Thanks.

**Comment by honestAnt** [comment]
please do it! 
![image](https://user-images.githubusercontent.com/15356873/64014139-03071d00-cb54-11e9-942b-77e3a58ef436.png)

replace 

--> 
![image](https://user-images.githubusercontent.com/15356873/64014217-3053cb00-cb54-11e9-9ce8-a5f97c9d9eef.png)

org.apache.commons.io.IOUtils.copy(is, outStream);

**Comment by honestAnt** [comment]
@pcornelissen spencergibb
