### ISSUE TITLE
Adding Request Query Parameters to the forwarded request

### ISSUE THREAD

**Issue by BenDave** [Netflix/zuul#211]
Can zuul add Request Query Parameters to  forwarded requests ?

e.g. : 

The original request url is 
`http://my.domain/uri?originalparam=value`

I want to forward this request and add a request parameter named  `myparam`:
`http://redirected.domain/uri?originalparam=value&myparam=value`

I tried to add the parameter with `RequestContext.getCurrentContext().getRequestQueryParams().put()`  but this didn't work.

However  `RequestContext.getCurrentContext().getRequestQueryParams()` does indeed show any request parameters  that were included as part of the original request (`originalparam`).

**Comment by ali2992** [comment]
You can do this, you can create a custom routing filter that adds to the request, look at the code for RibbonRoutingFilter, this is the default filter that is used, you'll see that it creates a new request based on the incoming, it is this new request that is then routed to the service. Creating a custom routing filter will allow you to add whatever parameters you like

**Comment by dorkolog** [comment]
@BenDave I think that creating a pre filter is the simplest way to have this feature.

**Comment by kerumai** [comment]
Yes, as @ali2992 and @BenDave say - you can create a pre filter, and add/modify the query parameters from there. 
This will work if your using either RibbonRoutingFilter(spring-cloud-netflix), or the ZuulNFRequest filter from the zuul-netflix-webapp module.
But it does look like if you're using the ZuulHostRequest this *won't* work.

**Comment by oldfoolwolf** [comment]
see SendResponseFilter.getQueryString()
and set :
zuul.SimpleHostRoutingFilter.route.disable=true
