### ISSUE TITLE
Zuul community

### ISSUE THREAD

**Issue by schrepfler** [Netflix/zuul#216]
It would be good if there's a companion site/repository/forge that gives some community aspect to Zuul (ex. via gitter, we can start this on Netflix/zuul right now). 
The community would share common policies in terms of libs or snippets (either as repos or gists or accompanying jars deployed to maven central) and thus increase the value proposition of adopting Zuul.

**Comment by mikeycohen** [comment]
I think that seems like an interesting idea. I will chat with others in the NetflixOSS community here to see if we can make that happen. I will update when I know.

**Comment by spencergibb** [comment]
FYI, we plan on doing something similar after Feign moves out of the Netflix org to https://github.com/FeignTown. Community contributed projects could live in the org, but out of core. /cc @adriancole

**Comment by schrepfler** [comment]
Sounds good, especially with 2.x on its way.
