### ISSUE TITLE
Zuul proxy omitting ( Authorization ) header with new spring

### ISSUE THREAD

**Issue by yamen23ali** [Netflix/zuul#218]
Hi,
  We have a micro service acting as Zuul proxy server, which will just forward the requests to other micro services ( no auth is needed in the proxy ), when we send a request with ( Authorization ) header  this header will be also forwarded to the internal micro services which will take care of it.
this was working fine for us until we upgraded to spring cloud ( Brixton.RC1 ).

Currently all the headers are being forwarded except for ( Authorization ) its always omitted by the Zuul proxy.

I've made a hack for this and currently i'm getting this header from request context and setting it in ( zuulRequestHeaders ) and this works fine for me .

i read about ( EnableOAuth2Sso ) but this won't work for us because we don't have oauth in the proxy at first place .

Any other way to do this ? ( maybe some configuration change ) ?

**Comment by spencergibb** [comment]
This is not the place for this issue. the `Netflix` org doesn't support Spring Cloud Netflix.

See the [docs](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#cookies-and-sensitive-headers) on sensitive headers.

To change it globally you can set `zuul.sensitiveHeaders=Cookie,Set-Cookie`.

 Please open an issue here: https://github.com/spring-cloud/spring-cloud-netflix/issues if you need it.
