### ISSUE TITLE
UnitTests in Java sources

### ISSUE THREAD

**Issue by ArturSkowronski** [Netflix/zuul#221]
Hello,
I have a question - why are you putting Unit Tests in Java Source like in: https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/java/com/netflix/zuul/FilterFileManager.java

It is a common pattern in repository. What are a reasons behind this decision? Pros, Cons?

Maybe it shouldn't be in Issue section but you really made me curious about that :)

**Comment by ausmith** [comment]
It looks like the group just rejected a PR that was attempting to move the tests out of the source code. #220 The reasoning from @mikeycohen was "This keeps logic and testing close." 

My team's implementation of zuul has our tests separated from the source files as our own style preference (I am not at Netflix so this is a completely independent opinion).

**Comment by ArturSkowronski** [comment]
Thanks for reply. Taste or style of coding is valid argument.
