### ISSUE TITLE
one parameter occur twice when url with query param

### ISSUE THREAD

**Issue by yzhang226** [Netflix/zuul#224]
for example
url - http://localhost:8080/test_api/test/?aa=456 with form data bb=789
`RequestContext.getCurrentContext().getRequest().getParameterValues("aa")` 
will produce` [456, 456] `

#### then i check the source code

* `org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter.FormBodyRequestWrapper`, following code will add all parameters, 
```
private synchronized void buildContentData() {
try {
	MultiValueMap<String, Object> builder = new LinkedMultiValueMap<String, Object>();
	for (Entry<String, String[]> entry : this.request.getParameterMap()
			.entrySet()) {
		for (String value : entry.getValue()) {
			builder.add(entry.getKey(), value);
		}
	}
```

* `com.netflix.zuul.http.HttpServletRequestWrapper.parseRequest`, 
will add QueryParameter again, no matter is post or get, as following,
```
Map<String, List<String>> query = HTTPRequestUtils.getInstance().getQueryParams();
if (query != null) {
    for (String key : query.keySet()) {
        list = query.get(key);
        mapA.put(key, list);
    }
}
```
then add form body
```
String contentType = req.getContentType();
final boolean isFormBody = contentType != null && contentType.contains("application/x-www-form-urlencoded");

// only does magic body param parsing for POST form bodies
if (isPost && isFormBody) {
```

someone occur this issue?

**Comment by spencergibb** [comment]
This is the wing issue tracker for a Spring project

**Comment by spencergibb** [comment]
Wrong not wing
