### ISSUE TITLE
HttpServletRequestWrapper.getRequest returns wrapped request

### ISSUE THREAD

**Issue by spencergibb** [Netflix/zuul#230]
Since #213 has been fixed I've encountered a never ending while loop in Tomcat's [`ApplicationDispatcher`]( https://github.com/apache/tomcat/blob/TOMCAT_8_0_0/java/org/apache/catalina/core/ApplicationDispatcher.java#L907-L908).

```
if (!(current instanceof ServletRequestWrapper))
                break;
```
The request is always a `ServletRequestWrapper` unless I unwrap it.

Prior to #213 `HttpServletRequestWrapper` did not extend `ServletRequestWrapper`, therefor the loop exited. As I tried to integrate zuul 1.2.2 @markt-asf (tomcat committer) noted in https://github.com/spring-cloud/spring-cloud-netflix/pull/1106#discussion_r67402882 that `HttpServletRequestWrapper.getRequest()`  returns wrapped request, which is a bug. I [work around](https://github.com/spring-cloud/spring-cloud-netflix/pull/1106) the issue by overriding `getRequest()` and returning the original request.

**Comment by kerumai** [comment]
Done. Let me know if that still gives you problems @spencergibb .

**Comment by matlockx** [comment]
hey there, this solves the problem on our side. we hit this with spring zuul whenever a service disappeared in our consul. can we get a release?
