### ISSUE TITLE
Whitelabel Error Page This application has no explicit mapping for /error, so you are seeing this as a fallback. There was an unexpected error (type=Internal Server Error, status=500). connect timed out

### ISSUE THREAD

**Issue by joshuamcdo** [Netflix/zuul#232]
So.. I am completely new to zuul, having been thrust straight into it.  I am facing a challenge I can't seem to overcome.

 We made some changes to the configuration.  Changes that have been checked and checked again 100 times.

Zuul is being used simply to re-write some urls in this case, nothing more.  It works fine in all sorts of other environments and used to work in this one until we made these changes.

 What's happening...

 When I visit the URL that is to be re-written :
https://demo-api.demmo.com/some_dir/rest/projects/demo/health-check

The zuul config looks something like this..
spring:
  profiles: development
zuul:
  routes:
    demo:
          path: /demo/rest/projects/demo/**
          url:  https://demo-demo-api.demmo.com/company_name/rest
    demo2:
          path: /rest/projects/demo/**
          url:  https://demo-demo-api.demmo/company_name/rest

I just keep getting the following error.

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 23 17:48:24 UTC 2016
There was an unexpected error (type=Internal Server Error, status=500).
connect timed out

Does anyone have any idea or can point me in a good direction to start walking?

Thanks in advance.

**Comment by spencergibb** [comment]
This isn't the right repo for this as you are using spring cloud. Try http://stackoverflow.com/questions/tagged/spring-cloud for questions like this. If it is a bug, file an issue here https://github.com/spring-cloud/spring-cloud-netflix/issues.

**Comment by joshuamcdo** [comment]
My apologies, I am not a developer by any stretch.

 Thanks!
