### ISSUE TITLE
how to use StaticResponseFilter，

### ISSUE THREAD

**Issue by lovechenrui** [Netflix/zuul#233]

**Comment by garychen0829** [comment]
how to user StaticResponseFilter +1

**Comment by tmack8001** [comment]
These are used when you want Zuul to complete the request itself. Typically for Heath checks, some type of deep check, semantic check maybe, return metrics or data only the Zuul cluster knows about (routes or services available in the cluster it something similar).

Documenting of the Zuul 2.x Endpoint filter type which replaced these status filters is as follows, https://github.com/Netflix/zuul/wiki/Filters#endpoint and the example filter for health check shows an implementation, https://github.com/Netflix/zuul/blob/2.1/zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters/endpoint/Healthcheck.groovy
