### ISSUE TITLE
Zuul behind an AWS ELB over HTTPS/SSL

### ISSUE THREAD

**Issue by cesartl** [Netflix/zuul#236]
I have an AWS `Elastic Load Balancer` with the certificates for my domain and which terminates the `SSL` traffic. The `ELB` has a listener on the `https` port and forwards it as `http` to `Zuul`.

When I use `Spring Boot HATEOAS`, Zuul will replace the links with the correct address but with `http` instead of `https`:

    "_links": {
      "self": {
        "href": "http://my.domain.com:80/rest/foo/bar"
      }
    }

but what I want is:

    "_links": {
      "self": {
        "href": "https://my.domain.com/rest/foo/bar"
      }
    }

The request that generates this response is made over `https`

Because `Zuul` is behind the ELB I'm guessing it cannot know that it should receive traffic through https.

Is there a way to tell `Zuul` to replace links with `https` even though it receives un-encrypted traffic through `http`?

I guess an alternative is to deploy `Zuul` with `https` with a self-signed certificate but I'd rather ovoid this complication if I can.

**Comment by mikeycohen** [comment]
Seems like a Spring issue, not a zuul one..

**Comment by CalamarBicefalo** [comment]
We are facing similar issues, shouldn't AWS ELB rewrite requests so they remain consistent after / before terminating SSL? That's what Zuul does on its end.

**Comment by cesartl** [comment]
I thought that Spring would use special headers that Zuul sets up when forwarding the request. Isn't not the case? If not I'm happy to raise the issue on the Spring project. AWS has released a new Application Load Balancer, I wonder if it would make a difference

**Comment by manuelcorrea** [comment]
We don't use Spring's version of Zuul. However, you should be able achieve that by checking the header X-Forwarded-Port or X-Forwarded-Proto  which are headers set by the AWS ELB

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html
