### ISSUE TITLE
Do not log warning of difference between Content-length and byte array length when Content-length is -1

### ISSUE THREAD

**Issue by sslavic** [Netflix/zuul#239]
Both Zuul 1.1.0 and 1.2.2 log as warning when ServletRequest.getContentLenght and content byte array length do not match (see [here](https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/java/com/netflix/zuul/http/HttpServletRequestWrapper.java#L166)).

From ServletRequest.getContentLenght javadoc:

> ```
> /**
>  * Returns the length, in bytes, of the request body and made available by
>  * the input stream, or -1 if the length is not known ir is greater than
>  * Integer.MAX_VALUE. For HTTP servlets,
>  * same as the value of the CGI variable CONTENT_LENGTH.
>  *
>  * @return an integer containing the length of the request body or -1 if
>  * the length is not known or is greater than Integer.MAX_VALUE.
>  */
> ```

If I'm not mistaken, -1 return value of ServletRequest.getContentLenght typically just means that Content-Length header hasn't been set at all in the request; even if was it would have been invalid value, to quote HTTP protocol [rfc](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13)

> Any Content-Length greater than or equal to zero is a valid value.

IMO HttpServletRequestWrapper should log a warning that the content-length header value and content byte array length do not match, only if content length header has been set (so only when getContentLength did not return -1).

**Comment by sfussenegger** [comment]
this [still is an issue in 1.x](https://github.com/Netflix/zuul/blob/be3ad627d770f01eeafa28a6e3862638a7560faf/zuul-core/src/main/java/com/netflix/zuul/http/HttpServletRequestWrapper.java#L168) with `transfer-encoding: chunked` due to the implementation of `shouldBufferBody()`:

```!java
    private boolean shouldBufferBody() {

        if (LOG.isDebugEnabled()) {
            LOG.debug("Path = " + req.getPathInfo());
            LOG.debug("Transfer-Encoding = " + String.valueOf(req.getHeader(ZuulHeaders.TRANSFER_ENCODING)));
            LOG.debug("Content-Encoding = " + String.valueOf(req.getHeader(ZuulHeaders.CONTENT_ENCODING)));
            LOG.debug("Content-Length header = " + req.getContentLength());
        }

        boolean should = false;
        if (req.getContentLength() > 0) {
            should = true;
        }
        else if (req.getContentLength() == -1) {
            final String transferEncoding = req.getHeader(ZuulHeaders.TRANSFER_ENCODING);
            if (transferEncoding != null && transferEncoding.equals(ZuulHeaders.CHUNKED)) {
                RequestContext.getCurrentContext().setChunkedRequestBody();
                should = true;
            }
        }

        return should;
    }
```

so with `transfer-encoding: chunked` there now is `req.getContentLength() == -1` to be expected, but here's the following code:

```!java
if (shouldBufferBody()) {
  // SNIP
  try {
    LOG.debug("Length of contentData byte array = " + contentData.length);
    if (req.getContentLength() != contentData.length) {
      LOG.warn("Content-length different from byte array length! cl=" + req.getContentLength() + ", array=" + contentData.length);
    }
  } catch(Exception e) {
    LOG.error("Error checking if request body gzipped!", e);
  }
  // SNIP
}
```

**Comment by honnel** [comment]
are there any plans to solve this issue?

**Comment by artgon** [comment]
No plans to fix it. Zuul 1.x is not actively being developed.
