### ISSUE TITLE
Provide more flexibility in constructing a RibbonCommand object

### ISSUE THREAD

**Issue by jdappel** [Netflix/zuul#24]
Currently the RibbonCommand object requires a client to construct empty maps for headers and query parameters even if a particular request doesn't require either of them.  A nice enhancement would be to provide a RibbonCommand builder for clients.

**Comment by kerumai** [comment]
That would be a reasonable improvement, and we'll keep it in mind for the zuul 2.x line, but not going to change in 1.x at this point.
