### ISSUE TITLE
Hardware memory requirments

### ISSUE THREAD

**Issue by heronict** [Netflix/zuul#240]
Can you tell me what the system (hardware) requirements are for using Zuul and the API-gateway. Unfortunately, I did not find this information on your documentation pages.

I was wondering how much RAM I need to allocate for one Zuul only instance only. I've installed 3 instances of Zuul for clustering purposes. I am hoping to get around 10.000 concurrent users on the system. Within you documentation, I've read that the required memory is 8GB. 

To be specific: 
What if I want to run 3 Zuul instances that are clustered on 1 node.
and 2 api-gateway instances on another node. How much RAM do I need to allocate per instance/node?

Thank you in advance!

**Comment by Alexander-Minyushkin** [comment]
Here are some benchmark results that can be used for hardware estimate https://engineering.opsgenie.com/comparing-api-gateway-performances-nginx-vs-zuul-vs-spring-cloud-gateway-vs-linkerd-b2cc59c65369

For example, on T1.Micro (1 vCPU, 1 GB RAM) Zuul can process 950.57 requests per second.
