### ISSUE TITLE
[ Question / Feature Request] Complex Prefixes

### ISSUE THREAD

**Issue by matanshukry** [Netflix/zuul#245]
I would like to have 2 "groups" of routes in my configuration:

(1), a group that starts with /api, which will be stripped.
e.g.
 - request to /api/users/** -->http://user-service/users/**
 - request to /api/images/** --> http://image-service/images/**

(2) A group that starts with /web, which will be stripped
 - request to /web/login/** --> http://web-service/login

It seems each one of those options is possible by it's own, using a global prefix (either "/api" or "/web"), and strip-prefix (set to false) at the service level. However, how can I achieve them both in the same zuul?

If it's not possible, what you guys think about this as a feature?

**Comment by spencergibb** [comment]
@matanshukry are you using spring-cloud-netflix? if so you should look for issues there and see if there is something similar, if not, create a new one.

**Comment by matanshukry** [comment]
@spencergibb I am. I didn't found something like it, so I've create an issue ( https://github.com/spring-cloud/spring-cloud-netflix/issues/1235 ). Thanks!
