### ISSUE TITLE
Question - Zuul & Swagger UI

### ISSUE THREAD

**Issue by anupbisht** [Netflix/zuul#254]
How can I integrate Zuul with Swagger UI?

**Comment by asandez** [comment]
I came across with the similar problem, right now I can route to 1 swagger, but I would like to compile the services in one Swagger page.

**Comment by zifnab87** [comment]
Could something like that be implemented? I know I can put swagger ui in each of my microservices but in order to expose it to the users I would like to be able to show the exact routes through zuul

**Comment by madheshr** [comment]
Any design ideas or thoughts on how to achieve this?

**Comment by mpmiszczyk** [comment]
[This blog](https://piotrminkowski.wordpress.com/2017/04/14/microservices-api-documentation-with-swagger2/) post provides solution for your problem.

In general you can implement (override) your own documentation trough merging ones provided by other services
```java
@Component
@Primary
@EnableAutoConfiguration
public class DocumentationController implements SwaggerResourcesProvider {
 
    @Override
    public List get() {
        List resources = new ArrayList<>();
        resources.add(swaggerResource("account-service", "/api/account/v2/api-docs", "2.0"));
        resources.add(swaggerResource("customer-service", "/api/customer/v2/api-docs", "2.0"));
        resources.add(swaggerResource("product-service", "/api/product/v2/api-docs", "2.0"));
        resources.add(swaggerResource("transfer-service", "/api/transfer/v2/api-docs", "2.0"));
        return resources;
    }
 
    private SwaggerResource swaggerResource(String name, String location, String version) {
        SwaggerResource swaggerResource = new SwaggerResource();
        swaggerResource.setName(name);
        swaggerResource.setLocation(location);
        swaggerResource.setSwaggerVersion(version);
        return swaggerResource;
    }
 
}
```
You can find full working example in  @piomin  [repository](https://github.com/piomin/sample-spring-microservices-advanced)

**Comment by Manasa-1510** [comment]
In my Zuul service i have authentication with jwt  which is needed to access other services .If i use the above code I am unable to see the swagger for zuul service itself and without jwt token i cannot aceess the other services ..Has anybody come across the similar kind of problem  ?

**Comment by Anonym91** [comment]
> In my Zuul service i have authentication with jwt which is needed to access other services .If i use the above code I am unable to see the swagger for zuul service itself and without jwt token i cannot aceess the other services ..Has anybody come across the similar kind of problem ?

Myabe not the best way,Bu in my case，this solves the problem.
` @Override
    public boolean shouldFilter(){
        RequestContext ctx = RequestContext.getCurrentContext();
        HttpServletRequest request = ctx.getRequest();
        String url = request.getRequestURI();
        if(url.contains("login") || url.contains("logout") || url.contains("swagger")
        || url.contains("v2") || url.contains("webjars")){
            return false;
        }
        return true;
    }`
