### ISSUE TITLE
Zuul returns "400 Bad Request" randomly for chunked responses

### ISSUE THREAD

**Issue by fiunchinho** [Netflix/zuul#261]
Hey!
Sending a PUT request to an API through Zuul returns `400 Bad Request` randomly. If I send the same request directly to the API behind, it always works returning `200 OK`, but if the request goes through Zuul, it sometimes returns `200 OK`, sometimes fails.

Analyzing packages with `tcpdump` shows an strange behaviour of one http request receiving two http responses, which it shouldn't happen at all.

The API behind zuul is an Spring Boot application returning a `Single` object, and it sends chunks responses to Zuul. I've reproduced the same issue [with this endpoint](https://gist.github.com/fiunchinho/7ff3dcda089ffbe19d42359a92396650).

`inputStream` is reading a JSON file from the server to simulate the response. With this code, we get a `400 Bad Request` one on every 10-15 requests.
It also looks like if the `inputStream` reads a small file, no error is shown, but if the file goes above some bytes, it starts happening.

Any help?

**Comment by mikeycohen** [comment]
What is the origin routing code you are using? This seems like it may be a spring boot issue. Is there a stack trace or anything when this happens?

**Comment by dgomezs** [comment]
I was experiencing this problem today and it seems gone if you upgrade to the lastests version of spring boot and zuul

**Comment by sokie** [comment]
@dgomezs what version of both seems to be fixing this issue?

**Comment by dgomezs** [comment]
hey @sokie 

This is the config I have and that has been working for me. 

```
def springBootRelease = "1.4.1.RELEASE"

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Camden.SR1'
    }
}

dependencies {

    // tag::jetty[]
    compile (group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: springBootRelease) {
        exclude module: "spring-boot-starter-tomcat"
    }

    compile group: 'org.springframework.boot', name: 'spring-boot-starter-jetty', version: springBootRelease

    // end::jetty[]

    // tag::actuator[]
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: springBootRelease
    // end::actuator[]

    compile 'org.springframework.cloud:spring-cloud-security:1.1.3.RELEASE'

    compile 'org.springframework.cloud:spring-cloud-starter-zuul:1.2.1.RELEASE'
    compile 'org.springframework.cloud:spring-cloud-starter-security:1.1.3.RELEASE'
    compile 'org.springframework.security.oauth:spring-security-oauth2:2.0.11.RELEASE'
    compile "org.springframework.security:spring-security-jwt:1.0.5.RELEASE"

}
```

I hope it helps

**Comment by 18099538715** [comment]
hi,I use spring cloud  Dalston.SR1 ,spring boot 1.5.6.RELEASE ,but it doesn‘t work

**Comment by 18099538715** [comment]
I met this because I have wrote my own  filter, In my filter I change the body size ,then the real content-length is not equals to the value in head.
