### ISSUE TITLE
how Zuul is used together with a land balancer?

### ISSUE THREAD

**Issue by yaojingguo** [Netflix/zuul#262]
I am reading [How We Use Zuul At Netflix](https://github.com/Netflix/zuul/wiki/How-We-Use-Zuul-At-Netflix). I have a question about the architecture diagram. Should we put several Zuul servers behind one load balancer  in a typical Zuul production deployment? Or we should put one Zuul server behind one load balancer. We are planning to use Nginx in the place of AWS Elastic Load Balancer.

**Comment by mikeycohen** [comment]
At Netflix we have many zuul nodes behind elbs. elbs mostly provide ssl termination, and there are a few other benefits in terms of working with route53 that are beneficial for our scale.  You could use zuul directly as a load balancer; nginx can also work..

**Comment by yaojingguo** [comment]
@mikeycohen, I am clear now. Thanks for your kind response.
