### ISSUE TITLE
Next Zuul release (v1.2.3, v1.3)

### ISSUE THREAD

**Issue by mattnelson** [Netflix/zuul#263]
There are a number of changes in 1.x that haven't been released. Are there any blockers or a date scheduled for the next release?

https://github.com/Netflix/zuul/compare/v1.2.2...1.x

**Comment by mikeycohen** [comment]
1.2.3 was creaed and released

**Comment by spencergibb** [comment]
@mikeycohen I don't see 1.2.3 in central http://repo1.maven.org/maven2/com/netflix/zuul/zuul-core/

**Comment by spencergibb** [comment]
ping @mikeycohen

**Comment by kerumai** [comment]
@spencergibb I fixed some failing unit-tests, and got the latest pushed to maven now. Unfortunately I accidentally did a minor rather than patch release, so it's 1.3.0.

**Comment by spencergibb** [comment]
NP, thanks!
