### ISSUE TITLE
Response from Zuul doesn't display 'reason-phrase'

### ISSUE THREAD

**Issue by bhagatali** [Netflix/zuul#266]
It is my understanding that for a response message, a start-line is a status-line. A 'status-line' has three parts, 'HTTP-version', 'status-code', and 'reason-phrase'.

According to RFC 7230, the 'reason-phrase' can be empty text. However, we have encountered issues when dealing with IHS server where, if a response's 'status-line' has no 'reason-phrase', it logs an error message. The request fails with HTTP '500' status code.

**Comment by mikeycohen** [comment]
In general, Zuul acts as a proxy, proxying back what it gets from an downstream(origin) system. One of the powerful things about Zuul is that you can add a reason-phrase to the response in a "post" filter if it's missing. It's quite trivial to do, but by default we don't add things to responses

**Comment by bhagatali** [comment]
I get that Zuul acts as a proxy but the downstream service does send back a response with reason-phrase and it seems to get stripped at the Zuul layer. When I get a response from the end point directly without proxy through Zuul I get the reason-phrase but when I use the Zuul gateway to get a response that phrase is stripped.
