### ISSUE TITLE
how to optimize zuul server's performance

### ISSUE THREAD

**Issue by dragontree101** [Netflix/zuul#269]
i use zuul server as gateway, and i use apache bench to test gateway's performance, 
i found if i request to app server,  concurrency from 50 to 60,   qps request from 200 to 241
but if i request to zuul server,  concurrency from 50 to 60  qps request from 216 to 190

how can i optimize zuul server's param to optimize qps?

**Comment by mikeycohen** [comment]
I'm not really sure how to answer your question. Zuul's performance depends on the work you are doing on it, the hardware your are running,  tuning of Zuul (thread pools and such), the workloads you are putting into it, and the infrastructure you are using. The folks at riot games put out a post recently about how they optimized there system to run zuul more efficiently. This may be helpful.  https://engineering.riotgames.com/news/riot-games-api-fulfilling-zuuls-destiny  In general, Zuul is efficient (for a java program), tho there is always room for micro-optimizations.

**Comment by dragontree101** [comment]
@mikeycohen   very good  article  thanks, i study a lot.
