### ISSUE TITLE
Dynamically remove route

### ISSUE THREAD

**Issue by fmicheloni** [Netflix/zuul#276]
Is there a way to block a route at runtime?
For example, if I have two different paths
- localhost/hello
- localhost/world
  can I disable one of them when Zuul is already running without hardcoding the blocked routes in the properties file?

Thank you!

**Comment by mikeycohen** [comment]
We have implemented in the past  a "blacklist" filter there we dynamically add blacklisted paths in an archaius property. This is one way to dynamically remove routes. Another is to dynamically update the zuul filter with a new routelist.
