### ISSUE TITLE
Provide for manual filter reloading?

### ISSUE THREAD

**Issue by timmc** [Netflix/zuul#28]
When I'm doing interactive development with Clojure (which I don't have a FilterCompiler for) I'd like to be able to swap out old filters for new versions by providing the name and a new ZuulFilter instance. The problem is that while I can do that in FilterRegistry, FilterLoader maintains a cached listing of each type of filter and won't refresh it unless explicitly told to load a new filter from file.

I currently have the following truly awful code to get around that:

``` clojure
(defn dev-reload-filter-entry
  "Use dirty hacks to reload a filter of the same name as before
by supplying a new filter instance. (Remove the old filter by name and add the
provided instance.)"
  [filter-name filter-inst]
  (let [r (FilterRegistry/instance)]
    (.remove r filter-name)
    (.put r filter-name filter-inst)
    ;; Force a reload by using wall-hacks to clear the cache of filters for one type.
    (let [cache-field (.getDeclaredField FilterLoader "hashFiltersByType")]
      (.setAccessible cache-field true)
      (.remove (.get cache-field (FilterLoader/getInstance))
               (.filterType filter-inst))
      nil)))
```

I'm considering sending a PR for FilterLoader that clears the cache for a type (and/or for all types), but I'd like to check if that would be welcome before doing so.

**Comment by jcarvalho** [comment]
Hi.

I've ran into this exact issue when looking into integrating dynamic filter loading into Zuul. If there is still interest, I can submit a PR.

For now, the reflection hack is working fine, but I'd like to use a cleaner solution.
