### ISSUE TITLE
Zuul "hangs" while proxying a 205 response

### ISSUE THREAD

**Issue by derekwyatt** [Netflix/zuul#287]
I have a test server that behaves like the following when responding with a `205`:

    ~> curl -v http://localhost:50001/respond/1?status=205

    * Connected to localhost (127.0.0.1) port 50001 (#0)
    > GET /respond/1?status=205 HTTP/1.1
    > Host: localhost:50001
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 205
    < Date: Sun, 18 Dec 2016 17:36:52 GMT
    < Content-Length: 0
    <
    * Connection #0 to host localhost left intact

When proxying this same request through Zuul I get the following:

    ~> curl -v http://localhost:9200/respond/1?status=205
    *   Trying ::1...
    * Connected to localhost (::1) port 9200 (#0)
    > GET /respond/1?status=205 HTTP/1.1
    > Host: localhost:9200
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 205
    < X-Application-Context: application:9200
    < Date: Sun, 18 Dec 2016 17:37:02 GMT
    * no chunk, no close, no size. Assume close to signal end

    ^^^ "Hangs" here... eventually either curl or Zuul closes the connection

This is:
- springBootVersion: `1.4.0.RELEASE`
- javaVersion: `1.8`
- releaseTrain: `Brixton.SR5`

**Comment by derekwyatt** [comment]
Moved to spring cloud: https://github.com/spring-cloud/spring-cloud-netflix/issues/1563

**Comment by leiy88** [comment]
Why should this issue be closed? It steel remains. 
* springBootVersion: 1.5.7.RELEASE
* javaVersion: 1.8
* releaseTrain: Edgware.SR2
