### ISSUE TITLE
How to enable automatic routing in Netflix/Zuul and Netflix/Ribbon with discovery information from Netflix/Eureka Service?

### ISSUE THREAD

**Issue by larswillrich** [Netflix/zuul#289]
I'm trying to develop a dynamic/automatically routing like described here:

http://stackoverflow.com/questions/41188108/how-to-enable-automatic-routing-in-netflix-zuul-and-netflix-ribbon-with-discover

I dont want to define every route entry in the applicaton.yml. Since i have a Eureka/Service Registry instance in my Microservice network it should be possible, to request this information periodically.

Has someone an idea?

PS: Please answer at the stackoverflow issue as well :)

best regards
lars

**Comment by spencergibb** [comment]
@larswillrich this is not the place for spring cloud issues

**Comment by sandy-adi** [comment]
@artgon I'm actually trying to do the same, is there any blog or example that I can refer to? I'm trying to do this without spring.
