### ISSUE TITLE
Zuul can not route the long delay request

### ISSUE THREAD

**Issue by wangys521yy** [Netflix/zuul#292]
I have one service, it take long time to handle plenty of data. when I use zuul to route the request, I found zuul can not work. It likes that the service has been terminated.

**Comment by kanouken** [comment]
is it looks like the Zuul process is hang on？

**Comment by rrpod** [comment]
@wangys521yy Have you tried changing the timeout value of the ribbon client? Try changing the value of <service>.ribbon.ReadTimeout in milliseconds. For more information refer: https://github.com/Netflix/ribbon/wiki/Programmers-Guide
http://netflix.github.io/ribbon/ribbon-core-javadoc/com/netflix/client/config/CommonClientConfigKey.html#ReadTimeout (JavaDoc)
