### ISSUE TITLE
maxSemaphores per route in Zuul

### ISSUE THREAD

**Issue by vasandharaj** [Netflix/zuul#297]
In Zuul, we are using the default isolation strategy (semaphore) with out eureka. I have found that we can specify the maxSemaphores like **_zuul.semaphore.maxSemaphores=10_** from this issue (https://github.com/spring-cloud/spring-cloud-netflix/issues/1332). But this setting will affect all the services in the zuul.

Is it possible to specify the maxSemaphores per zuul route ??  For example, 
`zuul.es.semaphore.maxSemaphores=10`  for a specific route.

Please find the sample configuration below 
`ribbon.eureka.enabled=false`
`zuul.routes.es.path=/es/**`
`zuul.routes.es.serviceId=es`
`es.ribbon.listOfServers=XXXXXXXX`

`zuul.routes.search.path=/search/**`
`zuul.routes.search.serviceId=search`
`search.ribbon.listOfServers=XXXXXX`

We are using spring cloud netflix 1.2.3 in our production

**Comment by spencergibb** [comment]
Spring Cloud questions/issues aren't appropriate for this repository

**Comment by vasandharaj** [comment]
@spencergibb: I Closed it and please find the same in the below link 

https://github.com/spring-cloud/spring-cloud-netflix/issues/1611
