### ISSUE TITLE
Status of zuul2

### ISSUE THREAD

**Issue by hoswey** [Netflix/zuul#298]
Hi, we want to use zuul in our projects, it seems the 2.x version is most suitable to use. Is it production ready?

**Comment by artgon** [comment]
We're still in the process of cleaning up the internal version and getting it ready to be open sourced. I would wait until we're done and and release it before going to production with that code.

**Comment by jwb** [comment]
Should I expect to wait a week, a month, or more?

**Comment by hoswey** [comment]
We are eager to the ready of zuul2,  even beta release is ok for us. Thanks.

**Comment by tmack8001** [comment]
I too am eager to see the final release of zuul2

**Comment by vtahlani** [comment]
Any update on zuul2 release?

**Comment by asafm** [comment]
We needed a gateway in Java right away - stumbled into Gravitee.io - looks
really good

**Comment by rkalicinski** [comment]
Any hope to see zuul2 release in near future?

**Comment by gihad** [comment]
Is the plan still to open source zuul 2?

**Comment by dgutzeit** [comment]
Is the project going nowhere? v2 will never be released?

**Comment by artgon** [comment]
The plan is definitely to open source Zuul 2. We're making progress but it will still be a while. I hope you can appreciate that we're a small team and this is a very time consuming task.

**Comment by harshmittal** [comment]
Any update/ETA for Zuul2 open source?

**Comment by nidhikv** [comment]
Any further updates on Zuul2 progress?

**Comment by nidhikv** [comment]
Any further update on progress of Zuul2?

**Comment by cjemison** [comment]
Are there any updates on this for Zuul 2?

**Comment by sunnykaka** [comment]
Are there any updates on this for Zuul 2?

**Comment by atttx123** [comment]
Are there any updates on this for Zuul 2?

**Comment by rathoreamrsingh** [comment]
May I know when Zuul 2 will be released?

**Comment by tehjakey** [comment]
I'm also interested in knowing when Zuul 2 will be available

**Comment by rubenns** [comment]
Now I'm using zuul but we need the zuul 2 improvements. I hope it's done soon.

**Comment by pethaniakshay** [comment]
We are using Zuul and waiting for Zuul2. Any estimated date of release open source?

**Comment by mikeycohen** [comment]
I just added comments in https://github.com/Netflix/zuul/blob/1.x/README.md about the status of Zuul 2.0. TLDR we are rokgin on it!!

**Comment by mikeycohen** [comment]
Zuul 2: A lot of people are asking about the status of Zuul 2.0. We are actively working on open sourcing it and with it, likely many filters that we use at Netflix. Yes, we realize it's been a long time coming. When we initially wrote Zuul 2.0, we heavily relied on rxJava to string filters together with Netty. This ended up adding a lot of complexity to the Zuul 2.0 core as well as made it quite difficult to operate and debug. We didn't think it was right to release Zuul 2.0 like this. So we spent a lot of time refactoring out this pattern, using Netty constructs directly. This took the better part of a year to complete and deploy safely within Netflix. So this work is now done. We are working towards releasing this much better, easier to understand, and more reliable Zuul 2.0. Obviously Netflix's business priorities take precedence to our open sourcing efforts, so as we get free time we will put efforts to open sourcing! Stay Tuned

**Comment by 1msoft** [comment]
I hope we can use zuul2 at end of 2017, where is the document ?  thank!

**Comment by artgon** [comment]
Locking this issue for now, as I think Mikey's comment should be the last word :)

**Comment by artgon** [comment]
Today is a big day! We've released Zuul 2 and a sample app on the 2.1 branch. It still needs documentation and we need to migrate/add more tests but at least you can now check it out, run it, and provide us with some early feedback.

**Comment by holy12345** [comment]
@artgon 
Thank you and your team for their efforts, I think this is an exciting moment. : )

**Comment by RickFanta-Cable** [comment]
Thanks so much for releasing Zuul 2.x.  I just heard your StrangeLoop talk and I'm eager to dive in.  Did you also release your Request Passport library somewhere?

**Comment by artgon** [comment]
@RickFanta-Cable yes, it includes the passport code. See https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/netty/insights/PassportLoggingHandler.java for more info. 

Documentation/wiki updates coming soon!

**Comment by mthmulders** [comment]
@artgon I would love to do some experiments with Zuul 2. Are zuul-core artifacts published somewhere? Can't seem to find them in [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.netflix.zuul%22)...

**Comment by tmack8001** [comment]
@mthmulders I believe that zuul2 via the 2.1 branch was only intended to be an early preview and isn't released yet. As @artgon mentioned earlier in this thread he is looking to add documentation and more test coverage "soon".

I'll leave it to @artgon to provide more insight into ETA on a RC1 or M1 of what I would guess will be zuul 2.1.0

**Comment by artgon** [comment]
You can find the snapshot builds here: https://oss.jfrog.org/artifactory/oss-snapshot-local/com/netflix/zuul/zuul-core/2.1.1-SNAPSHOT/

I think we'll do a full release once we document it properly and announce it on our blog.

**Comment by ghoddg** [comment]
hi,
I am using the below versions in my api gateway with zuul,
springBootVersion = "1.5.9.RELEASE"
springCloudVersion = 'Edgware.SR2'

  compile(
	  'org.springframework.boot:spring-boot-starter-web',
	  'org.springframework.boot:spring-boot-starter-tomcat',
	  'org.springframework.cloud:spring-cloud-starter-zuul',
	  'org.springframework.cloud:spring-cloud-starter-eureka'
  )

  testCompile(
	  'org.springframework.boot:spring-boot-starter-test',
	  'org.springframework.cloud:spring-cloud-starter-eureka-server'
  )

I wan to use the zuul 2. Can you please help me how to upgrade it.

**Comment by mthmulders** [comment]
@ghoddg I think you're out of luck. [A few weeks ago](https://github.com/spring-cloud/spring-cloud-netflix/issues/1498#issuecomment-360109442), the Spring Cloud people said they "have no plans to integrate zuul 2".

**Comment by ghoddg** [comment]
ohh really..!!!
you mean with Spring Cloud , we have to go with original zuul only and cant upgrade it with zuul-2?

**Comment by marmax** [comment]
yeah... that's what I call an epic fail... 

I am not saying you didn't work hard but,
* you failed to be transparent in communication about roadmap, ETA etc... 
* still no binary release available (nor is the documentation)

And now, when spring has diverged (so will the community) - what is the meaning for Zuul 2?

**Comment by aivans** [comment]
Please correct me if I am wrong.
Spring are building Spring Cloud Gateway. Looks great.
The philosophy is slightly different though. Zuul is a light-ish gateway that basically relays data to downstream microservices. It mainly touches headers. This was valid for Zuul1.
Spring on the other side seems to fiddle with the request body which may not fit everybody.

It is a shame indeed that the Zuul2 won't get that much traction as Zuul1 and will have doubts will get any traction at all since Spring were a huge advocate for the Netflix stack.

Spring are trying to cover the API Management ground, while Netflix don't really bother about this topic. AFAIK Netflix do not have a public API, so their main use case is relay data to their own Edge APIs from their own devices while taking care of some concerns at the edge.

**Comment by mattnelson** [comment]
I want to thank Netflix for all the work they have done to open source many parts of the NetflixOSS stack. I use many of them in a non-spring stack.
They develop these tools to fit their workflow, if you can get benefit from it as well, then great. But they are under no agreement to make Zuul2 spring compatible. Spring decides there own direction.

> And now, when spring has diverged (so will the community) - what is the meaning for Zuul 2?

The community is much larger than spring. It is incredibly short sided of you to assume that something not adopted by spring is doomed for failure.

**Comment by spencergibb** [comment]
:+1: to @mattnelson's comments. There's much more to decisions than just technology also. Very grateful for the efforts of all the Netflix engineers I've worked with and met with. The open source approaches are very different as well. Spring is open source first because that is our business. Zuul 2 has been in use since 2016, the open sourcing of it going slow. Creating/shipping content is netflix primary business. The fact that they open source things is a benefit to the community as a whole. Personally, I'm looking forward to seeing what production filters they release to see if we could port them. Thier experience is huge even if just indirectly used. There wouldn't be spring cloud gateway without zuul 1 OR 2.

**Comment by marmax** [comment]
@mattnelson @spencergibb as for the meaning - I guess @aivans has expressed it much better than me:
```It is a shame indeed that the Zuul2 won't get that much traction as Zuul1 and will have doubts will get any traction at all since Spring were a huge advocate for the Netflix stack.```

And the rest of my comment was just a lament about (not only mine, I guess) a disappoitment:
- that the expectation that as zuul1 was adopted by spring, the same will happen with zuul2, was false
- that I was fooled by this, mainly due to the lack of communication during the past months
- that if you say a release, I guess it's not meant to be only a tag in a repo, is it?

Don't get me wrong - kudos to them for all what they have opensourced and for the knowledge shared ;)

**Comment by spencergibb** [comment]
I've been pretty open the zuul 2 was not coming to spring cloud

**Comment by marmax** [comment]
@spencergibb I guess you mean that post in https://github.com/spring-cloud/spring-cloud-netflix/issues/1498, 21 days ago, right? Or anything else I might have missed? :)

**Comment by spencergibb** [comment]
Point taken, there are other places I've talked about it since early last year. The 2.1 branch was only publicly revealed a few months ago and there's no public release to integrate with anyway.

**Comment by lakshmipolu** [comment]
@Spencergibb.
Going through few websites and thinking Spring Cloud Gateway is the best option as routing gateway for our API's. As Zuul 2 is still not in Production. Would like to hear few inputs from your side as well about SCG,Documentation and support from Spring team.
Looking forward to hear from you. Appreciate if I get response ASAP.

**Comment by spencergibb** [comment]
@lakshmipolu this is not the forum for any of those requests. Join the spring-cloud gitter.

**Comment by lakshmipolu** [comment]
Sure. Thanks for your response.

**Comment by artgon** [comment]
Good news everyone!

I've updated the wiki with Zuul 2.x documentation: https://github.com/Netflix/zuul/wiki

Please have a look and let me know if there's anything missing, or if you want more depth on any feature.

I've also pushed a full release of Zuul v2.1.1: https://bintray.com/netflixoss/maven/zuul/2.1.1

You can keep using snapshot versions if you want (we test them and use them in production), but this will make it easier for new users to get started, and for visibility.

Happy Friday :)

**Comment by wangchunyang** [comment]
Congratulations!

**Comment by stiyyagura** [comment]
Excellent and thank you!!

**Comment by kamilgregorczyk** [comment]
Great news! I've been waiting to use it and compare it's performance with the gateway project. Could you tell me when will it be available in spring in spring-cloud-starter-netflix-zuul?

**Comment by spencergibb** [comment]
It will not be available as part of spring cloud

**Comment by kamilgregorczyk** [comment]
like, never ever?

**Comment by Aloren** [comment]
@rmunix I suppose decision not to support Zuul 2 is based on the fact that Spring Cloud team is now actively developing [spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway) project, which, as I suppose, will be a replacement for spring-cloud-netflix-zuul.

**Comment by yamen23ali** [comment]
Hi,
  I have a question regarding TCP proxying, is it possible to do it with Zuul2?  AFAIK it was not supported in Zuul1, what i need basically is to receive TCP and forward as TCP.
thanks,

**Comment by artgon** [comment]
Zuul is a L7 proxy and is built around the idea of request-response and therefore assumes the HTTP abstraction in order to run the core functionality. You should probably look for a L4 proxy if you only need TCP proxying.

**Comment by Qiuzhuang** [comment]
> L4

Does this means that technically Zuul supports L4 proxy anyway or it doesn't support L4 proxy layer?

**Comment by Qiuzhuang** [comment]
> Zuul is a L7 proxy and is built around the idea of request-response and therefore assumes the HTTP abstraction in order to run the core functionality. You should probably look for a L4 proxy if you only need TCP proxying.

Does this means that technically Zuul supports L4 proxy anyway or it doesn't support L4 proxy layer?

**Comment by lhenriquegomescamilo** [comment]
Hello everyone, somebody has news on how to use the Zuul2 with spring cloud?

**Comment by gihad** [comment]
@lhenriquegomescamilo I think most people that were on Zuul 1 and Spring Boot were left without support and at this point ended up moving on to Spring Webflux.

**Comment by Aloren** [comment]
@lhenriquegomescamilo the replacement is Spring Cloud Gateway. There will be no support for Zuul 2 in Spring Cloud

**Comment by lhenriquegomescamilo** [comment]
Thanks, @gihad  and @Aloren
