### ISSUE TITLE
RxNetty library version that Zuul 2 uses ( 0.4.x or 0.5.x)

### ISSUE THREAD

**Issue by JeehoonLim** [Netflix/zuul#304]
Hi.

I plan to make a gateway solution, based on Zuul2.

Final release of zuul2 isn't Open sourced, so I test zuul 2.x.mdm version.
I found that Zuul 2.x.mdm version reference the RxNetty 0.5.2-SNAPSHOT library.
I understand that RxNetty 0.5.x version is not stable and should not be applied to the operating environment.

I would like to know which version of the RxNetty library the final release of Zuul 2.x uses.

Thank you.

**Comment by mikeycohen** [comment]
The RxNetty libraries will be removed from the final Zuul 2.0 release. We found that we got more flexibility and simplicity in the Zuul 2 core by working directly with the Netty core than the RxNetty abstractions.
