### ISSUE TITLE
Configuring PoolingHttpClientConnectionManager with Time to Live? 

### ISSUE THREAD

**Issue by GJL** [Netflix/zuul#307]
Hi all,

I am using zuul to route requests to statically configured services according to the request path. 
The services behind zuul are addressed using DNS names. The DNS records can change rather frequently (e.g., daily). 

I have seen in `SimpleHostRoutingFilter`  that zuul uses `PoolingHttpClientConnectionManager` from Apache HttpComponents without configuring the _time to live_ for the connections in the pool 
(see https://github.com/Netflix/zuul/blob/939ada9dce57709cf6b250b77fabfa37e8d988bf/zuul-simple-webapp/src/main/groovy/filters/route/SimpleHostRoutingFilter.groovy#L97). Even if the DNS records change, the connection pool in zuul is keeping the connections to the old instances open. Depending on the load, it can take many hours until all the old connections are evicted from the connection pool. 

I could subclass `SimpleHostRoutingFilter` and override the method `newConnectionManager()` to return my own instance of `PoolingHttpClientConnectionManager` with a configured TTL. Is there any other way to solve my problem, and  does it make sense to add this feature to zuul?

Best,
Gary

**Comment by avoosh** [comment]
@GJL Hi, I am facing the same behaviour, how did you end up?

**Comment by GJL** [comment]
@avoosh I moved the issue to https://github.com/spring-cloud/spring-cloud-netflix/issues/1720
