### ISSUE TITLE
PUT requests with multipart are not proxied correctly (the multipart data is removed)

### ISSUE THREAD

**Issue by trcodestore** [Netflix/zuul#308]
We are using Zuul to forward requests to our "file upload service". Our service has 2 endpoints:

1) A POST endpoint used to upload files. It consumes multipart ("multipart/form-data"). 
2 A PUT endpoint used to upload files (to Update existing files). It also consumes multipart ("multipart/form-data").

Zuul does not forward the multipart data correctly to the PUT endpoint. It seems to strip out the multipart data and results in a "MIMEParsingException". 

If we hit the PUT endpoint directly with cURL, the resulting HTTP request looks like this:

`curl -v -X PUT -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" "http://localhost:8081/file/put"`

> Headers: {user-agent=[curl/7.35.0], host=[localhost:8082], accept=[/], content-length=[203], expect=[100-continue], content-type=[multipart/form-data; boundary=------------------------c1efb86a9054e387]}
> Entity: --------------------------c1efb86a9054e387 Content-Disposition: form-data; name="file"; filename="helloworld.txt" Content-Type: text/plain
>
> this is my file content
>
>--------------------------c1efb86a9054e387--

However, if we try to hit the PUT endpoint via Zuul, the HTTP request looks like this:

`curl -X PUT -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" "http://localhost:8082/file/put"`

> Header: {user-agent=[curl/7.35.0], accept=[*/*], expect=[100-continue], content-type=[multipart/form-data;boundary=hkBnDNXOcDTwkuL1qLhglF6i4NA2YREd], x-forwarded-host=[localhost:8081], x-forwarded-proto=[http], x-forwarded-prefix=[/file], x-forwarded-port=[8081], x-forwarded-for=[127.0.0.1], accept-encoding=[gzip], content-length=[38], host=[localhost:8082], connection=[Keep-Alive]}
> Entity: --hkBnDNXOcDTwkuL1qLhglF6i4NA2YREd--

Notice that the Entity is incomplete.

I have uploaded example code to this repository: https://github.com/trcodestore/zuul-put-demo. The repository contains 2 small projects used to demonstrate this issue. The readme contains build and run instructions. 

Any advice is appreciated. Thank you for your time.

**Comment by spencergibb** [comment]
This is not the correct repo to report. Use Spring Cloud Netflix

**Comment by trcodestore** [comment]
Okay, thank you. I've reported it to [Spring Cloud Netflix](https://github.com/spring-cloud/spring-cloud-netflix/issues/1751). I'll close the issue from this repository.
