### ISSUE TITLE
Removing a header from request in Zuul filter

### ISSUE THREAD

**Issue by vasyaivanov** [Netflix/zuul#310]
Hi, I need to remove one of the headers from the request Zuul receives.
How can I do it in one of Zuul filters or anywhere else?

Thank you,
Jim.

**Comment by aivans** [comment]
`ProxyRequestHelper helper = new ProxyRequestHelper();`
...
`helper.addIgnoredHeaders(headerName)`
Header will not be sent downstream.

**Comment by berndgoetz** [comment]
I know it's a long closed item, but whoever comes here has a simpler way to fix it: There is a property called zuul.ignored-headers that you can use to filter out headers sent to the backend services and returned from the backend to the caller end.
