### ISSUE TITLE
What is the relationship between DispatcherServlet and ZuulServlet? 

### ISSUE THREAD

**Issue by trcodestore** [Netflix/zuul#311]
I understand that requests coming into Zuul are first handled by Spring's DispatcherServlet and are then eventually handled by ZuulServlet. 

- Why does the request have to be handled by both servlets?
- We can bypass DispatcherServlet by defining zuul.servlet-path. Is there any danger in setting the servlet-path to "/" so that the DispatcherServlet is always bypassed for every request? 

I'm currently having trouble with multipart requests. The DispatcherServlet seems to corrupting the payload but I can work around this by using zuul.servlet-path. Rather than setting a special servlet-path just for my multipart requests, I would prefer to have a uniform pattern for all URLs (which is why I'm wondering about the implications in always bypassing DispatcherServlet)

**Comment by spencergibb** [comment]
This is not the place for spring cloud issues.

**Comment by trcodestore** [comment]
Would Spring Cloud Netflix be the correct place?

I wasn't sure where to post it as the question was related to ZuulServlet.

**Comment by spencergibb** [comment]
Yes, Spring Cloud Netflix. There is no Spring here.
