### ISSUE TITLE
Zuul seems to rewrite routes after REST call

### ISSUE THREAD

**Issue by srehker** [Netflix/zuul#313]
Hello everyone,

I have encountered a strange behaviour with our Zuul-Proxy in our Microservice-Project. My Setup consists of a Discovery-Service (Eureka), an API-Gateway (Zuul) and two Microservices "A" & "B".
After starting the setup, the following routes are shown via "localhost:10000/routes":
```
{
  "/api-gateway/**": "api-gateway",
  "/a-service/**": "a-service",
  "/b-service/**": "b-service"
}
```
My Zuul Config looks like this:
```
zuul:
  ignored-services: ''
  add-proxy-headers: true
  sensitiveHeaders: 'Cookie,Set-Cookie'
```

Now I access the services via the gateway and make some REST calls:

http://localhost:10000/a-service/sayHello --> OK
http://localhost:10000/b-service/sayBye   --> OK
http://localhost:10000/a-service/sayHello --> ERROR 404

I can see that the last request is mistakenly routed to Service B, even though I am using the "/a-service/**" route. How can this happen? Did the second REST call to service B somehow rewrite the routing? However "localhost:10000/routes" is still returning the same as above. This also works with calling the services in opposite order B-A-B -> 404 and mistakenly routed to service A.

I attached a minimal project with the 4 components, which should let you easily replicate this behaviour:
[MinimalZuulRouteBugProject.zip](https://github.com/Netflix/zuul/files/827817/MinimalZuulRouteBugProject.zip)

Thank you, for any insights regarding this issue.

**Comment by spencergibb** [comment]
This is not the place for spring-cloud-netflix issues

**Comment by srehker** [comment]
Sorry - please remove/close this then.

**Comment by spencergibb** [comment]
I can't close it, but you can.
