### ISSUE TITLE
Namespace confusion is happening with OpenStack's Zuul project

### ISSUE THREAD

**Issue by SpamapS** [Netflix/zuul#315]
Hi! I work on the Zuul project started by OpenStack developers back in 2012:

https://github.com/openstack-infra/zuul/tree/1.1.0

We've known for a while that there was a name collision when Netflix released its Zuul project. However, we may need to do something to disambiguate, as we have at least one example of confusion around the name:

https://thenewstack.io/ibm-openstack-engineer-urges-cncf-consider-augmenting-jenkins-zuul/

We should work together to find a solution to this. Thanks!

**Comment by SpamapS** [comment]
*bump*.. it's been a month. Is this thing on?

**Comment by spencergibb** [comment]
FYI, I don't work for Netflix.

https://github.com/openstack-infra/zuul/commits/1.1.0?after=ad61501575100c6992f4109bdac045aab5c16809+104

https://github.com/Netflix/zuul/commits/1.x?after=b4c6821a0d644d467c5560da4f836c30ada0efc1+279

Netflix zuul is older by a few months.

I had never heard of open stack zuul before this issue.

Netflix zuul is quite popular 
https://www.google.com/search?q=zuul
https://trends.google.com/trends/explore?q=zuul

**Comment by spencergibb** [comment]
@SpamapS what is your hoped for outcome?

**Comment by SpamapS** [comment]
Indeed! It appears we all had Ghostbusters on our minds back in 2012, as there's a third zuul that was created in the same 6 month span:

https://github.com/defunctzombie/zuul

My desired outcome is that we open a dialog and figure this out. People are not making the distinction well as evidenced by the referencing article (which has thus been referenced to me in face to face and chat conversations where people are very confused why I want to use a web request routing framework to test their code).

Both things are a bit abstract, so it's not so simple as "not the web server, the java framework". I'm leaving all options on the table. Both rename. Neither rename. Disambiguation pages on our websites and in our readmes. Whatever it takes to make sure we both can grow and thrive without confusing our target users and developers.

**Comment by spencergibb** [comment]
I hope it works out.

**Comment by SpamapS** [comment]
Ping? Is this a dead project or am I just being ignored because this is an uncomfortable topic? :-/

**Comment by artgon** [comment]
What kind of solution are you hoping for?

**Comment by SpamapS** [comment]
I'd like to make sure we're both aware of the fact that we have projects that are totally unrelated, but share a name space collision, and discuss ways we can address that. I'm not interested in chest thumping about who was first or who has more users. I just want to make sure the right people find the right code and community.

**Comment by SpamapS** [comment]
@artgon so, you're just going to close it? Nothing? No message for the confused users who might be landing in the wrong zuul project and very confused? No statement from the Netflix/Zuul maintainers? Just..Closed.

I wish your project well, but I am very disappointed in your inability to communicate with us on this fairly important issue.

**Comment by SpamapS** [comment]
I've submitted a similar patch to our Zuul's active dev branch. https://review.openstack.org/#/c/531292/
