### ISSUE TITLE
Zuul not honoring proxy settings

### ISSUE THREAD

**Issue by vasyaivanov** [Netflix/zuul#319]
Hi. I know there is/was a bug where Zuul does now honor proxy setting set in Java.
We tried couple of things.
1) Upgrading to "org.springframework.cloud:spring-cloud-dependencies:Brixton.SR5"
2) Changing RoutingFilter to inherit not from ZuulFilter but from SimpleHostRoutingFilter.

We are using JVM args like this: 
bootRun {
    systemProperty "spring.profiles.active", "dev,orcl"
    jvmArgs "-Dhttps.proxySet=true", "-Dhttp.proxySet=true", "-Dhttp.proxyHost=http://proxy.ourcompanyname.com", "-Dhttp.proxyPort=8080", "-Dhttps.proxyHost=http://proxy.ourcompanyname.com", "-Dhttp.proxyPort=8080", "-Dhttp.nonProxyHosts=localhost|*.ourcompanyname.com"
}

Is this a still known issue?

**Comment by spencergibb** [comment]
Spring Cloud issues should go here https://github.com/spring-cloud/spring-cloud-netflix/issues

**Comment by vasyaivanov** [comment]
Is this a Spring Cloud issue?
I think it is Zuul which is ignoring proxy settings. Please correct me if I am wrong.

**Comment by spencergibb** [comment]
If you're using spring-cloud-dependencies, then it's a spring cloud issue
