### ISSUE TITLE
zuul removing = for uri parameters with blank values

### ISSUE THREAD

**Issue by skumar6883** [Netflix/zuul#321]
I have configured the URL redirect with spring-cloud-netflix-core 1.2.6. and spring boot 1.5.2

My original request
http://localhost:8080/uri?param1=&param2=&param3=value

I want to forward this request in exactly same format
http://redirected.external.domain/uri?param1=&param2=&param3=value

But ZUUL is creating the final redirect URL as:
http://redirected.external.domain/uri?param2&param1&param3=value

The enpoint is expecting "=" as well as part of URI. How can I enforce zuul to add "=" for the params with no values. My project settings are:

zuul:
  routes:
    redirectDomain:
      path: /uri/**
      url: http://redirected.external.domain/uri
    
Help appreciated.

**Comment by spencergibb** [comment]
This is not the place for spring-cloud-netflix issues

**Comment by skumar6883** [comment]
Ah wrong forum! thanks will raise it in right one.

**Comment by skumar6883** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/issues/1804
