### ISSUE TITLE
How to autowire in Zuul Filters

### ISSUE THREAD

**Issue by Sudhirmiglani** [Netflix/zuul#322]
Zuul filters are not getting called when I place @Component on the filter, otherwise if use @Bean and create a new filter, it works.

This works fine.
    @Bean
    public PreFilter preFilter() {
        return new PreFilter();
    }

But since I need some more dependencies in the PreFilter. I am using this
@Component
@Slf4j
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class PreFilter extends ZuulFilter {
}

This filter is not getting called. What am I missing

**Comment by spencergibb** [comment]
This is not the place for Spring Cloud Netflix questions.

**Comment by khannedy** [comment]
@Sudhirmiglani are you using component scan? if you are using spring boot, it should be automatically scan all your @Component classes

**Comment by Sudhirmiglani** [comment]
Oh my bad, Working like a charm now. Thanks for pointing out the silly mistake @khannedy

**Comment by mirak94** [comment]
Actually I have the same issue a little bit stranger. I have one pre filter and another post, the pre filter is executed but the post one is not. Do you guys have any idea?
@spencergibb Excuse me sir, where should I post my question? I just have found that case which similar to mine.
Thank you in advance!
