### ISSUE TITLE
How to collect Metrics in Spring-Cloud Zuul

### ISSUE THREAD

**Issue by jcperezamin** [Netflix/zuul#331]
We wanted our metrics to be captured at ZUUL itself so that a simple counter is implemented in ZUUL and that would provide us the required metrics. Any suggestion in how to implement this would be helpful.

Thanks!

**Comment by spencergibb** [comment]
This is not the spring cloud issue tracker

**Comment by jcperezamin** [comment]
Thanks for your feedback. Do you know the exact link to answer this?

**Comment by milon619** [comment]
@spencergibb basically what we are trying to gather are some basic metrics like API hit count per minute,
Response time, connection errors and any other such useful info from Zuul. Is there a way to have these stats exposed natively from Zuul ?

**Comment by artgon** [comment]
Internally, we use Atlas for all of our metrics: https://github.com/netflix/atlas

**Comment by milon619** [comment]
@artgon , Atlas works by pulling metric data from different microservices or is it a "push" model ? Also what approach is used to expose metrics from Zuul ?

**Comment by brharrington** [comment]
@milon619 Atlas primarily uses a push model, but in some cases we have "pollers" that pull from sources and do a push. Usually it works by instrumenting the code using [spectator](https://github.com/Netflix/spectator) (or [servo](http://netflix.github.io/spectator/en/latest/intro/servo-comparison/) for older libs/apps) and then when [running internally](http://netflix.github.io/spectator/en/latest/intro/netflix/) our plugin will be connected to the registry and figure out how to send in to the appropriate Atlas backend.

**Comment by hartmut-pq** [comment]
Hi all, with spring boot 2.0 there's http://micrometer.io/ coming as ~spring-metrics.
Are there any plans to support zuul metrics?
What kind of metrics are available / are you pushing to atlas currently? Can I find a reference / code sample? 

Would be happy to contribute...!

**Comment by qtwang** [comment]
@artgon  can you give a code sample about zuul2 work together with Atlas?
