### ISSUE TITLE
Secure flag is not working

### ISSUE THREAD

**Issue by jignesh01** [Netflix/zuul#332]
As a part of our security requirement when we try to set secure flag in web.xml our application does not run. When we did some debugging we found out that zuul's PreDecoration filter did not have the request when it does ctx.getRequest() in run() method. Can someone please help with this issue?

Thanks.

**Comment by muhammetcangl** [comment]
Are you sure it's not set? I would like to remind you of this.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

![Screenshot_1](https://user-images.githubusercontent.com/40218384/70377317-4546b400-1924-11ea-97ca-7baae9e60ee2.png)


You can also do this set-up with a simple filter other than web.xml configuration. You can do it using ZuulFilter.

Like this: 
![image](https://user-images.githubusercontent.com/40218384/70377423-5fcd5d00-1925-11ea-9c1b-0ccc158cd9fe.png)

http://kb.entersoft.co.in/vulnerabilities/http-only-cookies.html
