### ISSUE TITLE
Possible to override the RequestSpecificRetryHandler

### ISSUE THREAD

**Issue by chazhung** [Netflix/zuul#334]
We are using Camden SR4.  I have enabled ribbon.httpclient.enabled: true

Digging into the code, the retry handler is instantiating the RequestSpecificRetryHandler directly.  Is there a way to override the retry handler?    I tried to create a decorator and creating a BeanPostProcessor which would wrap the RibbonLoadBalancingHttpClient to return the retry handler that I wanted, but my bean post processor was not included as a post processor for that bean.

**Comment by spencergibb** [comment]
This is not the tracker for spring cloud netflix.
