### ISSUE TITLE
Zuul routing for the static resources

### ISSUE THREAD

**Issue by vasandharaj** [Netflix/zuul#338]
I have a requirement to create route for the static resources (located in my local). I have used spring resource handlers to add the local files system resource to the URL (**http://localhost:9020/demo_1/files/**). please refer the code for your reference
```
@EnableZuulProxy
@SpringBootApplication
@EnableCircuitBreaker
public class ResourceserverApplication extends WebMvcConfigurationSupport {

	public static void main(String[] args) {
		SpringApplication.run(ResourceserverApplication.class, args);
	}
	
	@Override public void addResourceHandlers(ResourceHandlerRegistry registry) {
		super.addResourceHandlers(registry);
            registry
                .addResourceHandler("/demo_1/files/**")
                .addResourceLocations("file:///D:/tmp1/");
    }
}
```
Purpose of the application to serve the media to the clients and the configuration of the zuul follows below
```
server.port=9020

management.security.enabled=false
ribbon.eureka.enabled=false

zuul.routes.files.path=/demo_1/files/**
zuul.routes.files.serviceId=files
zuul.routes.files.stripPrefix=false

files.ribbon.listOfServers=http://localhost:9020/
files.ribbon.ReadTimeout=5000
files.ribbon.ConnectTimeout=5000
```
When I hit the below URL i got 500 response (Forwarding error)

`http://localhost:9020/demo_1/files/1.png`

Then I found that the request running till the hystrix exception occurs so i enabled the debug and found below stuffs

```
x-forwarded-host: localhost:9020,localhost:9020,localhost:9020,localhost:9020,localhost:9020
x-forwarded-proto: http,http,http,http,http
x-forwarded-port: 9020,9020,9020,9020,9020
x-forwarded-for: 0:0:0:0:0:0:0:1, 127.0.0.1
 Accept-Encoding: gzip
```

_**Only thing is zuul path (/demo_1/files/**) and the static resource path is same (/demo_1/files/**)**_ 

1. Why the request is running recursively till its throws hystrix exception ?? 
2.  Is it possible to warp the static resource under zuul (in order to serve better) ??

**Comment by spencergibb** [comment]
This is not the issue tracker for spring-cloud-netflix
