### ISSUE TITLE
How to use multiple urls for one path?

### ISSUE THREAD

**Issue by moon0326** [Netflix/zuul#339]
Hi,

My apologies if this has been asked before, but I could not find what I was looking for.

I have an endpoint where it should talk to two services. For example, POST /users endpoints sends data to Service A and Service B.

How can I define such route when the 'url' only takes one url? It seems this is rather common use case, but I could not find documentation on it.

Thank you in advance.

**Comment by udelblue** [comment]
I believe what you are asking for, is discussed in this enhancement request [https://github.com/spring-cloud/spring-cloud-netflix/issues/921](https://github.com/spring-cloud/spring-cloud-netflix/issues/921).

**Comment by moon0326** [comment]
@udelblue Thank you :)
