### ISSUE TITLE
problems while static resources to get response from apps behind zuul

### ISSUE THREAD

**Issue by ahyoSolitude** [Netflix/zuul#344]
hi,Im new to zuul,I have an app behind zuul and eureka,in that app I have some static resources like index.html,and included jquery etc.in that html I have some ajax requests like /app to get some info,without zuul and eureka，that works fine.I visit my index.html like this :http://myAddr/index.html，and send ajax request to /app. now I put that app behind zuul(name it as myApp),so I visit http://zuulAddr/myApp/index.html to visit that page,and some static resources I also have to add the prefix "/myaddr" to match the zuul routes.and ,the "/app" also have to add the prefix to work fine. is there some way to avoid these prefix adding work? my project have actually a lot of resources and requests.I added server.context-path，but is does not work.if I set the context-path to "myApp",the address became http://zuulAddr/myApp/myApp/index.html,that is really wired.maybe I　missed some important config?

**Comment by letiscoding** [comment]
i have the same question

**Comment by stiyyagura** [comment]
I had same issue in the past I did add the route for each static resource.
