### ISSUE TITLE
Zuul as Single-Point-Of-Failure

### ISSUE THREAD

**Issue by DivsDibs** [Netflix/zuul#345]
I am planning to use standalone Zuul (not using spring-cloud) as a Gateway along with Ribbon as LB. It seems Zuul becomes a Single-Point-Of-Failure. How can we overcome this constraint? If we spin up multiple zuul deployments, then also I'd need a LB or Gateway on top of it to load balance among the zuul deployments? But in that case we are having 2 consecutive layers on LB/Gateway? Is that correct approach to follow? If not, what else can be done?

**Comment by felixoldenburg** [comment]
Hi DivsDibs,
running mutliple Zuul instances behind a load balancer is absolutely fine and a common approach.
Not only in terms of fault tolerance but to scale with the amount of traffic you're going to proxy.
Running your entire back end behind only one Zuul(or any API gateway solution) instance is probably not a good idea.

**Comment by mikeycohen** [comment]
We also employ a multiregion strategy so that there isn't a single point of failure. Between multiple regions, multiple instances per zone, per region, and running zuul with a bunch of headroom, we minimize zuul as a single point of failure.

**Comment by lakshmangit** [comment]
could you please share me a piece of code how to configure multiple instances of zuul gateway configuration. If one instance of zuul gateway is down, i want to  my program to pickup another instance of zuul gateway dynamically.

**Comment by felixoldenburg** [comment]
You wouldn't need any specific Zuul configuration, if all you want is redundancy via multiple instances. It's just a matter of providing multiple Zuul instances for you load balancer and this, of course, depends on your setup and infrastructure (e.g. if you use GCE, AWS, or Azure, or some custom set up)
