### ISSUE TITLE
[zuul-simple-webapp] POST request carries body to routing server

### ISSUE THREAD

**Issue by fisache** [Netflix/zuul#346]
Hi, I'm using _zuul-simple-webapp_ for gateway.
In this app, if post method with body is requested from client, it couldn't carry request body to routing server.
I think that following code means carrying body request in _SimpleHostRoutingFilter.groovy._
```groovy
case 'POST':
  httpRequest = new HttpPost(uri + getQueryString())
  InputStreamEntity entity = new InputStreamEntity(requestEntity)
  httpRequest.setEntity(entity)
  break
```
So, I fixed chunked request body to true.

I think because _zuul-simple-webapp_ is just sample, it have to perform the role as gateway.
Thx!

**Comment by fisache** [comment]
PR #347

**Comment by fisache** [comment]
One more thing.
If routing server check content-length, the server couldn't recognize payload through _zuul-simple-webapp_ 
So, when send 'POST' request, send content length like 'PUT'

**Comment by tmack8001** [comment]
I agree with @fisache here is a request with a body attempting to test the behavior with httpbin.org as the origin server.

```
REQUEST_DEBUG::REQUEST:: http 192.168.86.107:51906  
REQUEST_DEBUG::REQUEST:: > POST /post HTTP/1.1
REQUEST_DEBUG::REQUEST:: > Cache-Control:no-cache   
REQUEST_DEBUG::REQUEST:: > Accept:*/* 
REQUEST_DEBUG::REQUEST:: > Host:raspberrypi:8080
REQUEST_DEBUG::REQUEST:: > Accept-Encoding:gzip, deflate
REQUEST_DEBUG::REQUEST:: > Connection:keep-alive    
REQUEST_DEBUG::REQUEST:: > Content-Type:application/json
REQUEST_DEBUG::REQUEST:: > Content-Length:24
REQUEST_DEBUG::REQUEST:: > { "test": "some value" }
REQUEST_DEBUG::ZUUL:: host=http://httpbin.org 
REQUEST_DEBUG::ZUUL:: Header > cache-control  no-cache
REQUEST_DEBUG::ZUUL:: Header > accept  */*
REQUEST_DEBUG::ZUUL:: Header > connection  keep-alive
REQUEST_DEBUG::ZUUL:: Header > content-type  application/json
REQUEST_DEBUG::ZUUL:: > POST  /post HTTP/1.1
REQUEST_DEBUG::ZUUL:: Entity >
REQUEST_DEBUG::ZUUL :: /post
REQUEST_DEBUG::ZUUL :: Response statusLine > HTTP/1.1 200 OK
REQUEST_DEBUG::ZUUL :: Response code > 200
```

The face that this line ```REQUEST_DEBUG::ZUUL:: Entity >``` has no "entity" data printed confirms that POST endpoints proxied via the ```zuul-simple-webapp``` don't work as expected.

**Comment by mikeycohen** [comment]
I merged that PR so that should fix this issue.
