### ISSUE TITLE
404 - UnSuccesfull instance resolution scenario

### ISSUE THREAD

**Issue by DivsDibs** [Netflix/zuul#349]
The following local (in a single machine) setup always fails and returns 404 for the following Url. 
`http://localhost:8080/Service2/`... but `http://localhost:8080/Service1/` works..

`eureka` hosted @9999 using Tomcat_deployment_1; shows the registered service1 and service2 apps and zuul..
`Service1` is a simple non spring-boot REST service "/service1" hosted @9080 using Tomcat_deployment_2; which works @`http://localhost:9080/Service1/`
`Service2` is a simple non spring-boot REST service "/service2" hosted @9180 using Tomcat_deployment_3 which works @`http://localhost:9180/Service2/`
`zuul` hosted @8080 using bundled `jetty` in `zuul-netflix-webapp` exposed @`http://localhost:8080/`

NOTE - Each tomcat is independent.

#zuul.properties snippet
```
zuul.niws.clientlist=service1|service2
zuul.niws.defaultClient=service1
zuul.ribbon.namespace=ribbon

service1.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
service1.ribbon.DeploymentContextBasedVipAddresses=service1

service2.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
service2.ribbon.DeploymentContextBasedVipAddresses=service2

```
#service1 eureka-client.properties
```
eureka.preferSameZone=true
eureka.shouldUseDns=false
eureka.serviceUrl.default=http://localhost:9999/eureka/v2/
eureka.region=default
eureka.name=service1-Eureka
eureka.vipAddress=service1
eureka.port=9180
eureka.instanceId=MYMAC1123456L

```
#service2 eureka-client.properties
```
eureka.preferSameZone=true
eureka.shouldUseDns=false
eureka.serviceUrl.default=http://localhost:9999/eureka/v2/
eureka.region=default
eureka.name=service2-Eureka
eureka.vipAddress=service2
eureka.port=9080
eureka.instanceId=MYMAC1123457L

```

The above problem will not surface and the `routing` always works if both the apps are deployed in same tomcat and the `client-side-loadbalancing` also works if both the apps are deployed in diff tomcats... The problem only surface if <B>diff app is hosted under diff server deployment</B>... <br><br>
Any ideas folks, what can be wrong?

**Comment by mikeycohen** [comment]
This is a spring boot issue, not a zuul one.. Sorry!

**Comment by DivsDibs** [comment]
@mikeycohen -- as specified in the issue, the issue is seen in non-spring-boot code.... exact codebase from github is used for Eureka and Zuul.. Not sure why you thought the other way... Please advise...
