### ISSUE TITLE
can't access it in tomcat

### ISSUE THREAD

**Issue by linmenglou** [Netflix/zuul#352]
my zuul been done with eclipse, but can't access it in tomcat. tomcat startup successed.

![image](https://user-images.githubusercontent.com/24384202/29697203-50bf98d2-8980-11e7-807e-8726403c4879.png)

**Comment by linmenglou** [comment]
application.yml configuration
![image](https://user-images.githubusercontent.com/24384202/29697306-da799eb0-8980-11e7-9167-108b6efdd688.png)

**Comment by spencergibb** [comment]
Not the spring cloud Netflix repo
