### ISSUE TITLE
How to enable Gzip

### ISSUE THREAD

**Issue by Aban** [Netflix/zuul#358]
Hi,

I just can't find any information about how to enable gzip compression on zuul. Do you know how to do that?

**Comment by tmack8001** [comment]
The Netflix engineers have an example of GZipping responses if the requesting client asked for gzip, but for whatever reason the origin server didn't gzip the response body. This example filter is part of zuul-core in the 3.x rewrite, https://github.com/Netflix/zuul/blob/3.x/zuul-core/src/main/groovy/com/netflix/zuul/filters/GZipResponseFilter.groovy

**Comment by Aban** [comment]
I finally enabled it using this configuration in my application.properties:

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain

Is there any diffference between using this solution and the filter solution suggested?

**Comment by mikeycohen** [comment]
The gzipresponsefilter handles a bunch of cases of when to gzip and when not to. Sometimes downstream services gzip the content, so you don't want to double gzip, sometimes the client explicitly asks for gzip, and sometimes not. Because of this complexity, we wrote that gzipresponsefilter
