### ISSUE TITLE
Incorrect compression detection

### ISSUE THREAD

**Issue by voronaam** [Netflix/zuul#365]
Sample call:

```
curl http://your.host.com -H'Accept-Encoding: notgzip, nevergzip, pleasenogzip'
```

Expected result:
Content is not compressed

Actual result:
Response content is gzipp'ed

Note that there is at least one real world HTTP compression type for which it matters: `pack200-gzip`

More RFC-strict example to disallow gzip is
```
curl http://your.host.com -H'accept-encoding: gzip;q=0,deflate,sdch'
```

Accroding to RFC https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3 the qvalue zero means "not acceptable".

And Zuul breaks RFC.

**Comment by 3052** [comment]
!
