### ISSUE TITLE
ErrorController moved 

### ISSUE THREAD

**Issue by tibberg** [Netflix/zuul#367]
Spring boot 2.0.0.M4, Spring cloud Finchley.M2. 
The ZuulProxy won't start, because `java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.web.servlet.error.ErrorController`

The ErrorController was moved in this commit: 
https://github.com/spring-projects/spring-boot/commit/2e51b48cd9ad9ad3e599aa0cb0b916061a061dfa

**Comment by spencergibb** [comment]
This is not the spring cloud netflix issue tracker and Finchley.M2 is not compatible with Boot M4

**Comment by tibberg** [comment]
I'll close this then. Sorry :)
