### ISSUE TITLE
404 when using Zuul when client host uses JAX-RS(Jersey)

### ISSUE THREAD

**Issue by lokaish39** [Netflix/zuul#368]
I have tried many things, many tutorials and so much of google search but with no success. Here is the issue I have right now,

I have to connect from **HOST_A**(using **Zuul**) to **HOST_B**. Ideally it works. but,

Usecase is- 
- _/api/get/product_, should use the **HOST_A**(localhost) controller which is written with JAX-RS **@Path** annotation.
- _/api/getme/products_, should be routed to **HOST_B** using Zuul which is written with JAX-RS **@Path** annotation.

Above usecase **_doesn't work_** and I have tested it well by creating two independent maven projects.

This usecase **works** only when, in first pointer above we change controller with **@RestController** from Spring.
Without changing anything, if I change HOST_A controller to use **@RestController**, the routing starts working but not when HOST_A uses **@Path** for the controller. Also, to highlight, I have a PRE ZuulFilter, request doesn't even make it to this filter with **@Path**

As I stated above, I don't see any routing pattern/path mistakes, there is already a lot on internet for those issues. :+1: 

**application.yml**
```javascript
zuul:
  routes:
    product:
      path: /api/getme/**
      service-id: http://localhost:8080/api/getme
```

**HOST_A**
```javascript
@Path("api")
@Named
public class DUIClient {
	@Path("/get/product")
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	public Object getName() {
		Map<String, String> names = new HashMap<String, String>();
		names.put("name", "Client");
		return names;
	}
}
```

**HOST_B**
```javascript
@Path("api")
@Named
public class DUIServer {
	@Path("/getme/products")
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	public Object getName() {
		Map<String, String> names = Maps.newHashMap();
		names.put("name", "Server");
		return names;
	}
}
```

**Comment by spencergibb** [comment]
Not the place for spring support

**Comment by lokaish39** [comment]
I don't think, it's spring. 
It's zuul which doesn't route requests only when client host have JAX-RS paths. It does route with RestController.

Are you trying to say, it's JAX-RS issue?

**Comment by Gbryson** [comment]
I was having similar issues,  I found this repo.  It seems like he got it to work:
https://github.com/cassiomolin/microservices-springboot
