### ISSUE TITLE
Canary releases and dynamic routing done right

### ISSUE THREAD

**Issue by ykushch** [Netflix/zuul#372]
We faced with the problem that we need to do such thing as dynamic routing and canary releases. So, for example, we deploy microservice `microservice-1`. Then, when someone finished a big feature we want to deploy it as a microservice `microservice-1.1`. 

### Question
Is it possible to dynamically reroute requests using information (for example from Headers) to use version microservice of version `microservice-1.1` instead on `microservice-1`?

For example, someone needs this feature and he will modify/add specific Header and for all requests, he will use new `microservice-1.1`. And if that Header is missing then the current `microservice-1` version should be used.

If it's not possible, please advise. I am interested in Zuul of course. For service discovery, I am using Eureka. Right now I am looking at [https://linkerd.io/](Linkerd) but there is no support for Eureka.

**Comment by mikeycohen** [comment]
There is no reason why you couldn't write a pre-filter to do that kind of routing.  If that needed to be more dynamic, you could use a dynamic property to choose the header.

**Comment by ykushch** [comment]
@mikeycohen any good examples/techniques that you could advise/show? Looked through the internet and other related question and mostly right now what I could find is kubernetes.
