### ISSUE TITLE
Load balancing in a heterogeneous environment 

### ISSUE THREAD

**Issue by victorherraiz** [Netflix/zuul#375]
Can I configure Zuul to load balance the requests depend on the latency (or other metrics) for the same service? 
We have serveral instances of the same service in a very diferent machines with different throughput

**Comment by artgon** [comment]
Yes, you can plug in your own Ribbon Load Balancer. More info here: https://github.com/Netflix/ribbon/wiki/Working-with-load-balancers

**Comment by victorherraiz** [comment]
I though that Ribbon was deprecated: 
https://github.com/spring-cloud/spring-cloud-netflix/issues/1501

Thank you so much

**Comment by artgon** [comment]
If you're using the current release of Zuul (1.x) then it's using Ribbon. Btw, this may not be the case for Spring usage of Zuul, I'm not very familiar with it.

**Comment by spencergibb** [comment]
Still uses ribbon loadbalancer, just not the ribbon http client.

**Comment by victorherraiz** [comment]
@artgon @spencergibb  Thank you for your time
