### ISSUE TITLE
Query Param ignored in Zuul routing

### ISSUE THREAD

**Issue by Sadarang** [Netflix/zuul#378]
Hi 
I am using ZUUL proxy for routing  so i have given below configuration in my properties file -

zuul.routes.abc.path=/api/v1/datafromhana/**
zuul.routes.abc.url= ${partner.hana.host.url}/xyz/VSSERVICE/lmn/services/Pt/GetCurrentCustomerList.xsjs?PartnerID=1101293

But when i am hitting - http://domainname/api/v1/datafromhana/ in postman, it doesn't give me json data and i found that - query param - "?PartnerID=1101293" is not there in the url.

Please suggest the way to solve this problem. I  want to make it generic like if any user comes and says he want to add new zuul.routes.pqr.path and zuul.routes.pqr.url then we don't need to do any changes in the code. we can just add this two thing in property file and it should work.

**Comment by spencergibb** [comment]
This is not the spring cloud netflix issue tracker.

**Comment by The-Neo-Noir** [comment]
Your  target application should handle the default behavior of the parameter, not zuul. There are other ways  ("use filters") to make zuul act the way you want,But not suggested

**Comment by Sadarang** [comment]
Thank you for your suggestion . I have accessed the targeted url , created a  new http header and sent the request.
