### ISSUE TITLE
How does zuul work without Spring Boot and Cloud?

### ISSUE THREAD

**Issue by hooverhe** [Netflix/zuul#380]
How does zuul work without Spring Boot and Cloud? Because our framework is not using Spring Boot and Cloud, we are needing a gateway, and planning to use zuul and hystrix. I am not sure whether zuul and hystrix can work without Spring Boot and Cloud. If can, would you provide the guide? Many Thanks.

**Comment by hooverhe** [comment]
Our framework is using common Java technologies, including Spring core, mvc, servlet, tomcat etc.

**Comment by artgon** [comment]
See the getting started guide: https://github.com/Netflix/zuul/wiki/Getting-Started
