### ISSUE TITLE
How to make zuul support sseEmitter or server send event?

### ISSUE THREAD

**Issue by LZS1991** [Netflix/zuul#381]
I want to use server send event in the microservice A,and i build an microservice B by using zuul to provide gateway.
So how to make zuul support sseEmitter or server send event?

**Comment by artgon** [comment]
It's not supported in Zuul 1.x.

**Comment by LZS1991** [comment]
Then is there other way to act like server send event when i use zuul?

**Comment by punkstarman** [comment]
It's nice to know that the current version of Zuul doesn't support SSE.

What would be even nicer is to know whether support could be added in the foreseeable future.

WebSockets seem to be slated for 2.0. In my opinion, SSE fit better with a microservices architecture than WebSockets.

**Comment by artgon** [comment]
@punkstarman Yes, we are planning to OSS Websocket and SEE support in Zuul 2.0.

**Comment by dvlreddy** [comment]
Hi artgon,
             Happy to hear that release plan of Zuul 2.0 i am looking forward to know the release date, so that i can plan my migration based on that, is there any fix that will make websocket and sse enabled with Zuul 1.0 available
Best Regards,
Lakshman.

**Comment by xueyuancoming** [comment]
Why is sse push delayed for nearly 20s in version 2.2.3 of zuul
