### ISSUE TITLE
How to remove a groovy filter from zuul (filterRegistry)?

### ISSUE THREAD

**Issue by MAAARKIN** [Netflix/zuul#385]
Currently i put my .groovy zuulfilter in the folder and they are added to my gateway but how to remove this filter dynamically, how can i do that?

looking in the source code FilterLoader.java has putFilter(File file) but not removeFilter(File file).

its possible to remove?

**Comment by MAAARKIN** [comment]
Anybody know's if this is possible?

**Comment by artgon** [comment]
I don't believe there's any functionality for that.

**Comment by MAAARKIN** [comment]
thx @artgon i will create then, i need in my project.

**Comment by sandy-adi** [comment]
@artgon, If I want to add a new route to Zuul my understanding is that one of the ways to do that would be to drop a Groovy file in the filters folder. Is this the only way today or is there a better way to do this? @MAAARKIN do you have an idea?

**Comment by pinpan** [comment]
putFilter(File file) of FilterLoader wil first remove previous registration of the plugin provided by the given file. Then it will try to register it again. Here the trick comes: If you place in the filters folder a file with the same name but not containing a valid class, zuul will unregister your filter and then will fail to register it again throwing corresponding exception. This is of course not nice, so a better option is to make the filter class "abstract". Zuul will check this before registering the filter again and if it is true, the will silently exit the registration method.
