### ISSUE TITLE
NoHttpResponseException while making consecutive request within interval of less than 3 seconds.

### ISSUE THREAD

**Issue by sandeep3028** [Netflix/zuul#389]
**application.yml** : 
```
zuul:
  debug:
    request: true
  routes:
    test-set:
      path: /test/set
      url: https://{{pcf_domain_name}}
    test-get:
      path: /test/get
      url: https://{{pcf_domain_name}}
```
**pom.xml**
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-zuul</artifactId>
</dependency>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Dalston.SR4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
**Exception** :
org.apache.http.NoHttpResponseException: {{pcf_domain_name}}:443 failed to respond
	org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)

**Comment by artgon** [comment]
This is not the spring cloud issue tracker.

**Comment by bakomchik** [comment]
Hi @sandeep3028 , i'm facing the same problem, did you found any solutions?

**Comment by lesliey** [comment]
I's also facing the same problem now, anybody has solutions?I have no ideas,who can help me ?

**Comment by rodrigoords** [comment]
Any answer or redirect to another issue?

**Comment by eelishiram** [comment]
I am having the same issue. Why has it been closed?

**Comment by haydonduan** [comment]
so?

**Comment by lesliey** [comment]
你好，我已收到你的邮件。
