### ISSUE TITLE
Sample Driver Application for Zuul 2

### ISSUE THREAD

**Issue by turgaycelik** [Netflix/zuul#390]
Hello,
We need a sample driver application like zuul-simple-webapp at 1.x branch for 2.1
We can try to develop it in-house but it won't be effective.

**Comment by artgon** [comment]
Good timing, we just released Zuul 2 with a sample app that you can take a look at on the 2.1 branch.

**Comment by turgaycelik** [comment]
Thanks, we are working on it but Zuul 2 is dependent on Ribbon load balancer. We just want to define service URLs directly. My colleague opened a more specific issue (https://github.com/Netflix/zuul/issues/395) for this.

**Comment by artgon** [comment]
Sounds good, let's discuss it there.
