### ISSUE TITLE
How to use zuul2 in kubernetes.

### ISSUE THREAD

**Issue by 1msoft** [Netflix/zuul#397]
I want to use zuul2 in kubernetes, and config by kubernetes.
How to do.

**Comment by artgon** [comment]
Zuul 2 runs as a standalone JAR file with a main method. You can run it in any container that has Java installed.

**Comment by amir-hg** [comment]
@artgon 
Hi 
Can you tell how to create a Standalone jar file using gradle?
and how to run it ?
i can run using ./gradlew run but not able to run jar files
