### ISSUE TITLE
mutual authentication between zuul and microservice with certificates

### ISSUE THREAD

**Issue by abhishekamte** [Netflix/zuul#398]
I have a zuul proxy acting as an edge server and my microservices are non jvm applications and I dont use ribbon or eureka. These microservices are accessible over https only and require client certs to communicate with them. Does zuul support mutual auth with certs for downstream? If so how do i set it up on my zuul server.

**Comment by artgon** [comment]
Not yet supported, but it's something we're definitely thinking about adding.
