### ISSUE TITLE
[Question]Mis-routed requests accross regions

### ISSUE THREAD

**Issue by aivans** [Netflix/zuul#402]
Please elaborate on on the best practices around handling mis-routed requests.
I found this in your articles:
"Ability to identify and handle mis-routed requests. User request is defined as mis-routed if it does not conform to our geo directional records. This ensures a single user device session does not span multiple regions. We also have controls for whether to use “isthmus” mode to send mis-routed requests to the correct AWS Region, or to return a redirect response that will direct clients to the correct Region."

What are the benefits of “isthmus” mode over redirects? When to use each?

My understanding of “isthmus” mode is that Zuul will transparently send the request to another Region, while a redirect is not transparent (involves User agent).

**Comment by artgon** [comment]
I'm not sure what you're asking here. Is the question why not use redirects instead of failing traffic over to another region?

**Comment by aivans** [comment]
Yes please.
- why did you use one versus the other?
- please point to docs on how isthmus mode does work

We are using the Netflix stack, including Zuul.
I am doing a research on how to to architect for multi-region deployment of a SaaS app. We have a large pool of Customers and we do not want to use DNS CName for subdomain strategy right now (each Tenant would get a subdomain).
We want to be able to route the Users to the region they belong to (decision criteria pending) and be able to "re-route" them in case something went wrong with the initial routing.

Thank you

**Comment by artgon** [comment]
Here are some scenarios where redirects don't work:

1. If an entire region is down, redirects won't help you - this necessitates a DNS-based solution for failover.
2. If you're using a common domain (e.g. www.netflix.com) across all regions, redirects won't help you (but likely you already have a region-based DNS solution in place).

The only scenario where cross-region traffic will help you is if Zuul is up but the rest of the region is in trouble. Then you don't have to worry about doing any DNS manipulation and the traffic will flow through transparently.

**Comment by aivans** [comment]
Thank you
