### ISSUE TITLE
[Question] Fork response to Main and Canary

### ISSUE THREAD

**Issue by benitocm** [Netflix/zuul#407]
Hi,

In this presentation https://www.slideshare.net/MikeyCohen1/edge-architecture-ieee-international-conference-on-cloud-engineering-32240146?qid=ba903f32-37ea-415a-a81b-2dc28cda966f&v=&b=&from_search=1, Mikey Cohen explains (slide 92) something related to replicate  the traffic that is coming to Zuul, one replica would go to the main origin that provides the functionality and the other replica would go to the canary service for testing. Because I have just the slides, that was what I interpret from the presentation (may be i am wrong ).

I am interested in something like that ( I have heard the term "shadowing"). For some requests that comes to Zuul, it would be needed to duplicate them, the original one would be redirected to the functional service and the replica one would be routedto the service to be tested. In addition, the response generated by the functional service should returned to the end user,  and the response generated by the service under test should be got to be analyzed.  This kind of setup would be useful also for doing some performance/capacity testing.

Please, could anybody told if it is possible to have this setup with Zuul? If so, how?

Thanks very much in advance.

**Comment by artgon** [comment]
The canary in that slide isn't actually shadowing traffic, it's just taking a very small portion of the traffic coming from the ELB. Shadowing traffic is a tricky proposition because it can affect downstream systems in terms of metrics, idempotency, etc. 

That said, if you want to, you can create a filter that makes a request to another service before it hits your main endpoint filter.

**Comment by benitocm** [comment]
Hi,

First of all, thanks for your time.

If you have a look to the slide 92, there are two red arrows from Zuul-Canary to Main Origin and Canary Origin and also the title is "Fork response to Main and Canary".  Those are the reasons because I thought that the slide was referring to "replicate" the traffic.

Let me elaborate my understanding about shadowing. If part of the traffic is redirected to the new version of a service, I see a couple of issues:
1) If the service is not ok, the end users are being affected.
2) if you want to test a service with database, end users could modify the database in production that  it may be not what you want to do.

If you "replicate" the traffic, you should not affect the end users because their traffic will follow the normal path. For a service with database, you could through away the database once you have finished the tests.

On the other hand, I dont understand the reason because shadowing can affecte downstream systems. Please, could you elaborate a bit more?

**Comment by artgon** [comment]
It's one of those things that really depends on your system. If you're confident that shadowing won't affect you negatively or you can contain it somehow, then it may not be a problem.

**Comment by benitocm** [comment]
Thanks again. 

With regard to how to do it, I had thought about a prefilter that would do it the request to the shadow service in an independent thread. The idea is trying not to affect the call to the mail service. In addition, that independent thread should get the response of the shadow service. It is also important to ensure that the shadow functionality  does not affect the main business of Zuul itself.

I would really appreciate your feedback about this.

PS: From your comments above, it seems that you would not use Zuul for doing shadowing.

**Comment by artgon** [comment]
Yeah, that would be the way to do it -- async in a pre filter so it doesn't affect your request path.
