### ISSUE TITLE
Zuul with Eureka or Consul

### ISSUE THREAD

**Issue by raoul2502** [Netflix/zuul#408]
Hi@ all,

we are planning to built our next projects using microservices-architecture and we have already defined that we want to use Zuul as API-Gateway. Right now we have to decide which service registry we will use: 

Consul or Eureka. 

We want to use server-side load balancing (via Zuul itself). Is it possible to do this while combining Zuul with Consul or Eureka?

Furthermore, we don’t want to use self-registration pattern! Our plan is to use Third-Party registration! Is it possible while combining Zuul with Consul or Eureka? Which tools can be used for this? Are there alternatives for Registrator which works for Docker?

Thanks a lot in advance for your help!

**Comment by artgon** [comment]
Zuul is generally designed to be used with Eureka, that would be the recommended approach.

**Comment by sandy-adi** [comment]
Do you guys publish your packages in some repository or you encourage building from source? 
I understand there could be cases where I have to modify the source and it makes sense to build from source, but other wise if I'd like to use the packages as is what is the best repository to look at?

**Comment by spencergibb** [comment]
AFAIK Netflix have not released binaries in the 2.1 branch, only 1.x

**Comment by artgon** [comment]
You can find the snapshot builds here: https://oss.jfrog.org/artifactory/oss-snapshot-local/com/netflix/zuul/zuul-core/2.1.1-SNAPSHOT/

We'll do a full release once we document it properly and announce it on our blog.
