### ISSUE TITLE
user mailing list?

### ISSUE THREAD

**Issue by lvijay** [Netflix/zuul#415]
I'm new to Zuul and I'm considering it for my organization.  I couldn't find a mailing list for Zuul, is github issues the way?  The only one I found on groups.google.com was for HystrixOSS.

I noticed that zuul-3 uses the RxJava 2.x library.  Would you recommend starting with zuul3 for new projects?

**Comment by artgon** [comment]
Github issues is the way for now. There is no Zuul 3, the latest version is 2.1 and it's no longer based on RxJava. We only use RxJava for providing an interface in the async filters.

**Comment by lvijay** [comment]
Thanks @artgon.  I was referring to the 3x branch but that's good to know.  Closing this issue.
