### ISSUE TITLE
Cannot resolve configuration property in .yml

### ISSUE THREAD

**Issue by godpit** [Netflix/zuul#416]
Cannot resolve configuration property 'zuul.host.connect-timeout-millis' and so on, with spring cloud Finchley.M7, i saw the package of the class 'ZuulProperties'  is org.springframework.cloud.netflix.zuul.filters,  other such as eureka, the package  org.springframework.cloud.netflix.eureka. I use development tool :intellij Idea 2018.1 release candidate.

**Comment by spencergibb** [comment]
This is not the spring cloud issue tracker

**Comment by godpit** [comment]
ok, thanks, i'm so sorry
