### ISSUE TITLE
ProxyEndpoint https

### ISSUE THREAD

**Issue by JacobJohansen** [Netflix/zuul#428]
Is the proxy endpoint able to handle https endpoints or is a custom endpoint needed?
referencing Zuul version 2.1

**Comment by artgon** [comment]
Currently no, but I'm planning to add it soon.

**Comment by JacobJohansen** [comment]
@artgon were you thinking of using a property along the lines of 

```
this.IS_SECURE = new CachedDynamicBooleanProperty(originName+".netty.client.IsSecure", false);
```

**Comment by artgon** [comment]
@JacobJohansen do you want to submit a PR for this?

**Comment by JacobJohansen** [comment]
I was thinking of creating a pr, but i first wanted to clean up the code formating. review the community guidelines. Lastly I was considering wiring in the jks so that it would have a more expected behavior for custom certs.
