### ISSUE TITLE
[Question] How to check zuul is redirecting request to appropriate service

### ISSUE THREAD

**Issue by shekhar-patil27** [Netflix/zuul#429]
Hi,

Could you please help me with the code snippet which will help to determine whether zuul is redirecting request to appropriate service. 

I am using spring boot & zuul 1.x. 

RequestContext.getCurrentContext().getRequest().getRequestURI().toString(); gives me the url which is initiated by browser client, however I am not able to figure out how to make sure zuul is redirecting this request internally to proper service.

Thanks,
Shekhar

**Comment by artgon** [comment]
It's probably better to ask this on the Spring tracker, but in Zuul 1.x you would use this method: https://github.com/Netflix/zuul/blob/1.x/zuul-netflix/src/main/java/com/netflix/zuul/context/NFRequestContext.java#L74
