### ISSUE TITLE
Usage of deprecated Class: com.netflix.zuul.message.http.Cookies

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#432]
The class [com.netflix.zuul.message.http.Cookies](https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/message/http/Cookies.java) is making use of a deprecated reference io.netty.handler.codec.http.Cookie. Is there any plan to address this?

**Comment by artgon** [comment]
Will take a look.
