### ISSUE TITLE
In zuul 2.x sample demo, a request routing to nginx-backend http service always got 404 error

### ISSUE THREAD

**Issue by whbg** [Netflix/zuul#434]
Condition:
1.disable eureka, and then
2.choose ConfigurationBasedServerList

We found this error was relation to 'Host' header forward to real service. Or i  did incorrect configuration(see below bold line)?

**Comment by artgon** [comment]
Which host header are you getting on your backend?

**Comment by whbg** [comment]
<img width="794" alt="2018-05-11 10 01 42" src="https://user-images.githubusercontent.com/38675777/39902790-64eed932-5502-11e8-8041-fc0ef402fc37.png">
configuration is ,
api.ribbon.listOfServers=http://xx.com:80
backend Host header is Host:localhost:7001(it should be Host:xx.com:80)

**Comment by artgon** [comment]
That's not how proxies are supposed to behave. You have to maintain the host header from the original request otherwise your service has no idea where the request came from.

**Comment by liangGTY** [comment]
I think it is not more friendly that the proxy overrides the host header for the host obtained from ribbon.listOfServers? @artgon

**Comment by wongcoekfai** [comment]
And so? how to fix this problem?

**Comment by SMakhrov** [comment]
I have the same problem. @artgon please help to solve this.

**Comment by artgon** [comment]
If you want to change the outbound host header, you can add a filter that modifies the inbound request headers.
