### ISSUE TITLE
zuul retry is not working

### ISSUE THREAD

**Issue by chelailee** [Netflix/zuul#439]
here is my Configuration：

spring:
application:
name: gateway
cloud:
loadbalancer:
retry:
enabled: true
server:
port: 7003
eureka:
client:
serviceUrl:
defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/

zuul:
retryable: true
routes:
admin-cloud-client:
path: /admin-cloud-client/**
servicesId: admin-cloud-client
retryable: true

hystrix:
command:
default:
execution:
isolation:
thread:
timeoutInMilliseconds: 60000

ribbon:
ReadTimeout: 5000
ConnectTimeout: 200
MaxAutoRetries: 0
MaxAutoRetriesNextServer: 1
OkToRetryOnAllOperations: true

when one is down，"MaxAutoRetriesNextServer" can't working,it can't call the normal one.
please tell me what should i do,thank you very much

**Comment by artgon** [comment]
This is not the Spring Cloud issue tracker.
