### ISSUE TITLE
Zuul with Spring Security

### ISSUE THREAD

**Issue by sdesa** [Netflix/zuul#440]
I have an angular application which I am reverse proxying through Zuul. Everything works well until I add Spring Security. Here is my code:

**application.yml (zuul)**

`
    ui:
      path: /**
      url: http://localhost:4200

`
WebSecurityConfigurerAdapter

`
@Configuration
@EnableWebSecurity
public class AppSecurity extends WebSecurityConfigurerAdapter {
......

    @Order(Ordered.HIGHEST_PRECEDENCE)
    @Override
    protected void configure(HttpSecurity http) throws Exception {

    	http.headers().cacheControl().disable();
        http.headers().xssProtection();
        http.headers().httpStrictTransportSecurity();
        
        http
        .headers()
        .addHeaderWriter(new XFrameOptionsHeaderWriter(XFrameOptionsMode.SAMEORIGIN))
        .and()
        .csrf().disable()
        .sessionManagement()
        .sessionCreationPolicy(SessionCreationPolicy.ALWAYS)
        .and()
        .exceptionHandling()
        .authenticationEntryPoint(redirectionEntryPoint()).accessDeniedPage("accessDeniedUrl")
        .and()
        .authorizeRequests()
        .antMatchers("/**").access("@user.hasPermission()")
        .anyRequest().authenticated()
        .and()
        .addFilterBefore(AuthenticationProcessingFilter(), AbstractPreAuthenticatedProcessingFilter.class);

.....

`
There is a accessdenied.html in the spring boot zuul project that the user should be taken to if the user does not have permission. But because of the /** path in the application.yml, the user is never sent to the page if the user does not have access, the user instead gets access to the angular application regardless of permission.

Is there a work around this? Can I tell Zuul to NOT send the user to the angular application if the user does not have access?

**Comment by artgon** [comment]
This is not the Spring Cloud issue tracker.

**Comment by sdesa** [comment]
Moving it out of this.
