### ISSUE TITLE
Zuul filter run twice!

### ISSUE THREAD

**Issue by hello-willy** [Netflix/zuul#443]
i am not good at English, i put the code directly, please help me.
1、my application.yml
`eureka:
  client:
    service-url:
      defaultZone: http://10.17.18.26:10000/btsc/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: routeDemo
zuul:
  routes:
    api-test:
      path: /api/test/**
      serviceId: test
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8`

2、my filter class
`package cn.bluethink.route.filter;

import com.netflix.zuul.ZuulFilter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.springframework.cloud.netflix.zuul.filters.support.FilterConstants.PRE_TYPE;
public class TestFilter extends ZuulFilter {
    private Logger logger = LoggerFactory.getLogger(AuthFilter.class);
    private static int counter = 0;
    @Override
    public String filterType() {
        return PRE_TYPE;
    }

    @Override
    public int filterOrder() {
        return 15;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {
        logger.info("=======================================Done:"+counter++);
        return null;
    }
}
`
3、on my application class, register the filter

`package cn.bluethink.route;

import cn.bluethink.route.filter.AuthFilter;
import cn.bluethink.route.filter.TestFilter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.feign.EnableFeignClients;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
@EnableZuulProxy
@EnableEurekaClient
@EnableFeignClients
public class RouteApplication {

	public static void main(String[] args) {
		SpringApplication.run(RouteApplication.class, args);
	}

	/*
	@Bean
    public AuthFilter authFilter() {
	    return new AuthFilter();
    }
	*/
    @Bean
	public TestFilter testFilter() {
		return new TestFilter();
	}
}
`
That is all. when i run this application, it output the message:
2018-05-18 10:26:27.366  INFO 19380 --- [nio-7777-exec-2] cn.bluethink.zuultest.TestFilter         : =======================================Done:0
2018-05-18 10:26:27.369  INFO 19380 --- [nio-7777-exec-2] cn.bluethink.zuultest.TestFilter         : =======================================Done:1

The filter run twice, why?
----------------------------------------
PS:i use the spring boot to build the project, the spring boot version is 1.5.10, and the spring cloud version is Edgware.SR3

**Comment by artgon** [comment]
This is not the Spring Cloud issue tracker.

**Comment by Agileaq** [comment]
There are two place run the TestFilter:
1. ZuulServletFilter, do some static routing or cache stuff.
2. ZuulServlet,     Core Zuul servlet which intializes and orchestrates zuulFilter execution .

**Comment by tramontaz** [comment]
@hello-willy please make a sure that you don't use org.springframework.stereotype annotation (like a @Component or @Service)
