### ISSUE TITLE
[Question] Zuul documentation and initiation

### ISSUE THREAD

**Issue by stevenNzonzi** [Netflix/zuul#452]
Hi, I am new to zuul and I would like to learn more about how to use it to expose endpoints through a proxy, and its other functionalities. 
I have gone through the wiki but it is very high level. I have also gone through various blog posts but they all seem to be highlighting the choices made throughout the zuul's development and the issues netflix faced.
Is there some other source which I refer to, to understand the sample code much better. And use zuul from the stand point of a beginner?

**Comment by tluolovembtan** [comment]
Me too, want to get more information。

**Comment by artgon** [comment]
Have you taken a look at the sample app? What kind of documentation do you think would make it clearer?
