### ISSUE TITLE
[Question]  zuul 2 can use eureka 1?

### ISSUE THREAD

**Issue by tluolovembtan** [Netflix/zuul#453]
@artgon @pablete 

**Context:**

I built a microservices environment using spring cloud components. eg :
spring cloud zuul, spring cloud eureka , spring cloud config , and other spring boot microservices.

I just want to upgrade zuul 1 to zuul 2 , eureka does not upgrade.

**Q1**. Zuul2 sample uses eureka 2 by default,  Zuul2 can use eureka 1?

 zuul 2.x  build.gradle: 
```java
compile "com.netflix.eureka:eureka-client:latest.release"
```
 zuul 2.x dependencies.lock  : 
```java
"com.netflix.eureka:eureka-client": {
            "locked": "1.8.6",
            "requested": "latest.release"
}
```
**Q2** if yes, Please tell me how to do it.

**Q3** if no, Please tell me why .Is it because of using eureka 2's API?

If you have some reference manual or code, please answer to me :)

**Comment by zhouxwyeah** [comment]
+1
i also have the same question, i want upgrade zuul2 in my old system which using eureka1.*

**Comment by artgon** [comment]
Zuul 2 is using eureka 1. The new version of eureka client actually has a different namespace, i.e. `eureka2-client`.

**Comment by wuzhefang** [comment]
+1
