### ISSUE TITLE
Question regarding auth 

### ISSUE THREAD

**Issue by devup2** [Netflix/zuul#457]
Am trying to configure oauth2 authorization flow in zuul 2. Do I add the the logic in the filters( HttpInboundSyncFilter and HttpSyncEndpoint) or is there better place to plug in the oauth2 client logic.

**Comment by artgon** [comment]
Yeah that would be the way to do it.

**Comment by qtwang** [comment]
@artgon  I try to run the example of HttpSyncEndpoint ，Healthcheck.groovy, but it seem doesn't work,
so I make a breakpoint at the method of apply,it doesn't go into the method.....I don't how to run it

**Comment by artgon** [comment]
@qtwang what's the result of `curl -v localhost:7001/healthcheck` when running the sample?

**Comment by qtwang** [comment]
@artgon the result is as below:
   ```
    This application has no explicit mapping for /error, so you are seeing this as a fallback.
    Mon Jul 02 09:52:36 CST 2018
    There was an unexpected error (type=Not Found, status=404).
    No message available
```
I add a  "System.out.println("endpoint result result result!!!!")", it can't be printed；
I make a breakpoint on the method of apply,it doesn't go into the method;
so，it make me confused.
```
HttpResponseMessage apply(HttpRequestMessage request) 
       System.out.println("endpoint result result result!!!!")
        HttpResponseMessage resp = new HttpResponseMessageImpl(request.getContext(), request, 200)
        resp.setBodyAsText("healthy")
        // need to set this manually since we are not going through the ProxyEndpoint
        StatusCategoryUtils.setStatusCategory(request.getContext(), ZuulStatusCategory.SUCCESS)

        return resp
    }
```
so far, I know how to how to run the example of HttpInboundSyncFilter like Debug.groovy, and I also know how to run the example of  HttpOutboundSyncFilter like ZuulResponseFilter.groovy.

in zuul1, I can read the request and write the respone by extend ZuulFilter 
   ```
 public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();
        Cookie cookie = new Cookie("condition", String.valueOf(ctx.get("condition")));
        cookie.setPath("/");
        cookie.setDomain("xxx.com");
        cookie.setMaxAge(60);
        ctx.getResponse().addCookie(cookie);
        return null;
    }
```
but in zuul2, I doesn't have a RequestContext, and as I know, only HttpSyncEndpoint  can be used for reading the request (HttpRequestMessage request)and writing the response(HttpResponseMessage),
neither HttpInboundSyncFilter  nor HttpOutboundSyncFilter  can do that.
so, my question is how to use the httSyncEndpoint and how to run an example to write cookie from the request paramter ?  
thanks a lot!!

**Comment by tmack8001** [comment]
The message HttpRequestMessage and HttpResponseMessage will both implement https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/message/http/HttpRequestInfo.java which has access to a shared request/response RequestContext which can be used in any filter just like in Zuul/1.x

**Comment by qtwang** [comment]
@tmack8001 I know that, but  only the apply method of HttpSyncEndpoint is like this ：
` HttpResponseMessage apply(HttpRequestMessage request)`
and  HttpInboundSyncFilter  is like this:
`HttpRequestMessage apply(HttpRequestMessage request)`
HttpOutboundSyncFilter is like this:
`HttpResponseMessage apply(HttpResponseMessage response) `
