### ISSUE TITLE
How can I request a microservice via zuul 2 ?

### ISSUE THREAD

**Issue by notatent** [Netflix/zuul#467]
I want to use Zuul 2 in my project，and I have built project with Zuul2 + Eureka successful, but I don't know  Which url link should I type in the web browser, Can anyone help me ? Thanks !

Here my situation:
  1. Eureka server
       using tomcat (port 7080) deploy Eureka Server war archive.
 2. microservice ,  name : billing
       &nbsp;using spring cloud + Eureka Client.
       &nbsp;provide REST service : name queryBill
       &nbsp;properties file :
               &nbsp;&nbsp;&nbsp;&nbsp;spring.application.name=billing
               &nbsp;&nbsp;&nbsp;&nbsp;server.port=9003           
        &nbsp;&nbsp;&nbsp;&nbsp;eureka.client.serviceUrl.defaultZone=http://localhost:7080/eureka/v2/
 3. microservice ,  name : provider-springmvc     (terrible name, just for example, simulate when not a spring cloud project using Eureka Client)
       &nbsp;using springmvc + Eureka Client.
       &nbsp;provide REST service :  name m
       &nbsp;properties file :
                &nbsp;&nbsp;&nbsp;&nbsp;eureka.name=provider-springmvc
                &nbsp;&nbsp;&nbsp;&nbsp;eureka.port=8004
                &nbsp;&nbsp;&nbsp;&nbsp;eureka.serviceUrl.default=http://localhost:7080/eureka/v2
  4. zuul-sample (which I just modified some items in .properties file )
        &nbsp;using Zuul 2  + Eureka Client.
        &nbsp;properties file :
                 &nbsp;&nbsp;&nbsp;&nbsp;eureka.name=zuul-2
                 &nbsp;&nbsp;&nbsp;&nbsp;eureka.port=8099
                 &nbsp;&nbsp;&nbsp;&nbsp;eureka.serviceUrl.default=http://localhost:7080/eureka/v2

(2. microservice ，3. microservice，4. zuul-sample )   all of them register to Eureka Server successfully , I can the "registration status: 204" , and they were show on the page of Eureka Server monitor .
<img width="846" alt="2018-06-19 7 00 05" src="https://user-images.githubusercontent.com/24230530/41593577-1e37138c-73f3-11e8-8b12-8c4dc4cb9a46.png">

If I request to 2. microservice directly , it work.
http://localhost:9003/queryBill
I want to request service via Zuul2 , But I don't know  Which url link should I type in the web browser.
http://localhost:8099/queryBill
http://localhost:8099/billing/queryBill
http://localhost:7001/queryBill
http://localhost:7001/billing/queryBill
all of them failed( Zuul2 netty server using 7001 port)

But
when I using Zuul 1,  it wok. (Zuul 1  and Zuul 2 both using Eureka 1, nothing with Eureka 2...)
project envirment:
&nbsp;&nbsp;using spring cloud + Eureka Client
&nbsp;&nbsp;properties file :
&nbsp;&nbsp;&nbsp;&nbsp;spring.application.name=service-zuul
&nbsp;&nbsp;&nbsp;&nbsp;server.port=8888
&nbsp;&nbsp;&nbsp;&nbsp;eureka.client.serviceUrl.defaultZone=http://localhost:7080/eureka/v2
I can request service via Zuul1
http://localhost:8888/billing/queryBill

**Comment by notatent** [comment]
The "eureka.port=8099" in the 4.zuul-sample doesn't work, I found 8099 didn't active by netstat .
So the url should be
http://localhost:7001/queryBill
or
http://localhost:7001/billing/queryBill

But ,  web browser remind me "HTTP ERROR 502", and  IDEA remind me "Error choosing server for key null",

The key was set to null by BasicNettyOrigin line 121...

I know there is something wrong with setting of Ribbon, does the following setting right?

> #api.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
> api.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
> #api.ribbon.DeploymentContextBasedVipAddresses=api-test.netflix.net:7001
> api.ribbon.DeploymentContextBasedVipAddresses=${eureka.name}:${eureka.port}

**Comment by notatent** [comment]
After I debug, I found it's not "key"'s business.
when we use Eureka as  service register center ,  Ribbon will use Eureka Client get services information from Eureka Server, and do the load balance. 
SessionContext will store the service instance name, we have change something to help  Ribbon get right services.
1. application.properties      
api.ribbon.DeploymentContextBasedVipAddresses=**billing**
2.Routes.groovy
context.setRouteVIP("**api**")

and use the follow url
http://localhost:7001/queryBill

**Comment by GraceYYJ** [comment]
could u provide your demo？i don't know how to use zuul2 in my project....

**Comment by Harlan6** [comment]
could u provide your demo？i don't know how to use zuul2 in my project....  tks

**Comment by thanhphi0401** [comment]
> After I debug, I found it's not "key"'s business.
> when we use Eureka as service register center , Ribbon will use Eureka Client get services information from Eureka Server, and do the load balance.
> SessionContext will store the service instance name, we have change something to help Ribbon get right services.
> 
> 1. application.properties
>    api.ribbon.DeploymentContextBasedVipAddresses=**billing**
>    2.Routes.groovy
>    context.setRouteVIP("**api**")
> 
> and use the follow url
> http://localhost:7001/queryBill

i need demo project integrated with eureka. please help me
