### ISSUE TITLE
Zuul Static Resources Not Found ..

### ISSUE THREAD

**Issue by Yvan0329** [Netflix/zuul#473]
I configured the hystrix dashboard forwarding with zuul, but found some problems, static resource files were not found.
This is my zuul configuration：
![image](https://user-images.githubusercontent.com/25361947/42382634-7f3c170a-8167-11e8-9e97-0d82b58c0357.png)
This is my dashboard configurarion:
![image](https://user-images.githubusercontent.com/25361947/42382643-8932612e-8167-11e8-9932-6d62360f42f5.png)
When I visit the http://localhost:8080/dashboard/hystrix page, the image and js are not found, but the page can display normally.
![image](https://user-images.githubusercontent.com/25361947/42382647-8f846306-8167-11e8-8b8b-af12d0a28fb2.png)
The address of the picture and js access is:
![image](https://user-images.githubusercontent.com/25361947/42382659-964e12ea-8167-11e8-89b4-d75585dfb546.png)
The reason they can't find it is because there is no prefix/dashboard~~
Can you help me solve this problem? thank u very much~~~

**Comment by Yvan0329** [comment]
I know that zuul can do the forwarding of services, but can I do page forwarding?

**Comment by artgon** [comment]
This is not the Spring Cloud issue tracker, you should ask there. There's no functional difference between a service response and page response, just different content type.
