### ISSUE TITLE
How can I use zuul2 without eureka?

### ISSUE THREAD

**Issue by lidd** [Netflix/zuul#476]
I have my own discovery service, so is there any possible to use zuul2 without eureka?

**Comment by imet** [comment]
for application.properties file, you can do the following setting:

```
eureka.validateInstanceId=false
eureka.shouldFetchRegistry=false
eureka.registration.enabled=false
eureka.preferSameZone=false
```

**Comment by akshayat** [comment]
As mentioned [here](https://stackoverflow.com/a/34042535/1534925)

> Yes, it is totally possible.You have to use @EnableZuulProxy on your config class and config it something like this :
> 
> zuul:
>   routes:
>     yourService:
>       path: /yourService/**
>       serviceId: yourService
> 
> ribbon:
>   eureka:
>     enabled: false
> 
> yourService:
>   ribbon:
>     listOfServers: localhost:8080
>

**Comment by tmack8001** [comment]
Actually the EnableZuulProxy annotation is a springism where the spring-cloud-netflix project will not be adopting zuul2. Instead there is reference in another issue here on the Netflix/zuul project that references having a status routing file to be "similar to spring".
