### ISSUE TITLE
"loadBalancerKey" value is not  accessble in subclass of IRule.java

### ISSUE THREAD

**Issue by harinathbk** [Netflix/zuul#478]
Hi All,

iIm setting FilterConstants.LOAD_BALANCER_KEY in Zuul Pre Filter but not able to access in IRule sub classes. May i know what value we need to set for FilterConstants.LOAD_BALANCER_KEY? is it serviceId or route or etc..
Please find below spring cloud version ,pre-Filter and IRule sub-class.

Thanks in advance.
========================
springCloudVersion=Edgware.SR4
springBootVersion=1.5.10.RELEASE
==========================
@Slf4j
@Component
class PreAddLoadBalanceKeyFilter extends AbstractZuulFilter {

  PreAddLoadBalanceKeyFilter() {
    super(PRE_ROUTING_HANDLING, 1111);
  }

  @Override
  public boolean shouldFilter() {

    return true;
  }

  @Override
  protected void execute() {
    final RequestContext requestContext = RequestContext.getCurrentContext();

    RequestContext.getCurrentContext()
        .set(FilterConstants.LOAD_BALANCER_KEY, "service-v1");

  }
}
============================
@Slf4j
@Component
@Primary
public class CusctomRoundRobbinRule extends RoundRobinRule {

  @Override
  public Server choose(Object o) {
    return choose(getLoadBalancer(), o);
  }

  public Server choose(ILoadBalancer lb, Object key) {
 
  log.info("loadblancekey::"+(String)key);

    return server;
  }
}
===========================
6.11 How to Provide a Key to Ribbon’s IRule
If you need to provide your own IRule implementation to handle a special routing requirement like a canary test, you probably want to pass some information to the choose method of IRule.

com.netflix.loadbalancer.IRule.java. 

public interface IRule{
    public Server choose(Object key);
         :
You can provide some information that will be used to choose a target server by your IRule implementation like the following:

RequestContext.getCurrentContext()
              .set(FilterConstants.LOAD_BALANCER_KEY, "canary-test");
If you put any object into the RequestContext with a key FilterConstants.LOAD_BALANCER_KEY, it will be passed to the choose method of IRule implementation. Above code must be executed before RibbonRoutingFilter is executed and Zuul’s pre filter is the best place to do that. You can easily access HTTP headers and query parameters via RequestContext in pre filter, so it can be used to determine LOAD_BALANCER_KEY that will be passed to Ribbon. If you don’t put any value with LOAD_BALANCER_KEY in RequestContext, null will be passed as a parameter of choose method.

**Comment by artgon** [comment]
This is not the spring cloud issue tracker.

**Comment by xuben** [comment]
same problem, don't know how to figure it out. can anyone be mercy enough to tell me how to do routing based on a specific key value with or without using zuul. I didn't use zuul in my case though.

**Comment by 84yy** [comment]
maybe  this can help  https://github.com/spring-cloud/spring-cloud-netflix/issues/1272
