### ISSUE TITLE
Best Practices: Error Responses from Inbound filters

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#481]
Are there best practices around how to respond from inbound filters. Let's say for example, there is a inbound filter to check if a particular route exists and if not it needs to respond back with a 404. The only way to do this right now seems to be to create a new endpoint filter that'd return a 404 and then set that as the endpoint on the request context? 
Isn't there a better way to do this? Like just throw an exception with say a `404` code or something?

**Comment by artgon** [comment]
You can create a generic static endpoint filter and use the context to pass in body, status, etc. You can route to it similarly to how the sample does proxy endpoint routing -- based on something in the context.

**Comment by qtwang** [comment]
@artgon can we get the response body info from the HttpOutboundSyncFilter HttpResponseMessage response API?

**Comment by artgon** [comment]
Yes. `response.getBody()` or `response.getBodyAsText()`.

**Comment by qtwang** [comment]
thanks ，@artgon no matter what content response ，the body is always null，if I have to setBody or setBodyAsText？so how can I get the body content from the original server？

**Comment by artgon** [comment]
I'm not sure what you're asking. Are you setting the body or getting the body?

**Comment by danesavot** [comment]
I think I am on the same page with @qtwang as I am trying to understand how Zuul 2 works. I am not able to get the body content from the HttpOutBoundSyncFilter using response.getBody() or response.getBodyAsText() after calling to the origin server from the ProxyEndpoint. It is giving Null value. Look like ProxyEndpoint is still waiting to receive the data from the origin server while Zuul continues to handle the rest of the filters. Any explanation on how to get the body content and do the modification?

**Comment by qtwang** [comment]
@artgon  yes，I am asking the same question as @danesavot ask below .

**Comment by artgon** [comment]
Can you share some code to reproduce the issue? I can't make it happen on the sample app.

**Comment by artgon** [comment]
Ok, I think I see what's missing here. For both inbound and outbound filters, if you're getting a body and you want to print it all out in the filter, you need to override the `needsBodyBuffered()` method and return `true`. See parent class here: https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/filters/BaseFilter.java#L130

I'll update the wiki to include this. Thanks for bringing it to my attention.

**Comment by danesavot** [comment]
I have figured out to get the body content using needsBodyBuffered() last week after I dived into the source codes but I totally forget to update the answer! Anyway, thanks for the response! Hope, you will be more responsive next time :)
