### ISSUE TITLE
Question : proxy to HTTP 2

### ISSUE THREAD

**Issue by lovers36** [Netflix/zuul#482]
Is there a way to set "HTTP2 - ZUUL - HTTP2"?
If not, do you have a plan about?

**Comment by artgon** [comment]
Not yet, but we're working on it.

**Comment by nevesjorgelucio** [comment]
@artgon Is this feature still in progress or can we already use zuul to forward http/2 requests? If not, do we have any advantage of using http/2 with zuul only for incoming request and forwarding it as http/1.1?
