### ISSUE TITLE
Is zuul2 preformance better than zuul1?

### ISSUE THREAD

**Issue by AngryApe** [Netflix/zuul#486]
We built gateway with zuul1 and hystrix， now we want to upgrade  our zuul1 to zuul2, but the pressure test shows qps is much lower than zuul1(zuul1 1500+, zuul2 500+). Then I set netty worker to 20(cpu 4 core) and it reachs to 1100. Do you have some advice for best practices?

**Comment by artgon** [comment]
If you're doing a load test, try using the [benchmark properties file](https://github.com/Netflix/zuul/wiki/Benchmarking). Generally, performance in Z2 should be better than Z1 (although roughly similar). Also, in Z2 you should generally have either 1 or 2 workers per CPU. Any more than that and you'll get diminishing returns. 

Keep in mind that you can't block at all in Netty. You can't just port your code directly to Z2 unless you're positive that there's no blocking at any point.

**Comment by AngryApe** [comment]
Change the async executor in `BaseZuulFilterRunner#filter(final ZuulFilter<I, O> filter, final I inMesg)` to a custom fixed thread pool fixed this problem, cause we use hystrix with sync mode and it  needs plenty of thread to handle IO operations.

**Comment by sandy-adi** [comment]
@AngryApe the qps base lines you are using for zuul1, is that the qps for a single instance of zuul1? or was it against a cluster. Also could you please share the server configuration?

**Comment by sandy-adi** [comment]
@artgon if I've an origin server that can handle upto 4000 req/sec is it ok to assume that adding zuul2 in front would not cause considerable degradation?

**Comment by artgon** [comment]
@AngryApe Zuul 2 doesn't work that way. It's completely async, so you can't wait on requests in a blocking fashion. You shouldn't need to use Hystrix on the origin request.
