### ISSUE TITLE
Zuul proxy not maintaining session with connected routes

### ISSUE THREAD

**Issue by hmalhotra20** [Netflix/zuul#488]
I have zuul proxy connected to Spring boot services having sessions. Is Zuul a right fit for such a scenerio? Right now on each request in same browser, linked services are creating new sessions each time.

I found few links to inject session id through a filter but did not work with Spring boot 2, Zuul 2 and tried using Spring session 2.0.,4 also.

Added this to the filter

   @Override
    public Object run() {

        RequestContext context = RequestContext.getCurrentContext();
        HttpServletRequest request = context.getRequest();
        List<String> cookies = Collections.list(request.getHeaders("cookie"));
        HttpSession session = request.getSession(true);
        if (session != null && cookies.stream().noneMatch(c -> c.startsWith("SESSION="))) {
            context.addZuulRequestHeader("cookie", "SESSION=" + session.getId());
        }
        if(session!=null)
            log.info("ZuulPreFilter session proxy: {}", session.getId());

        return null;
    }

**Comment by shrimantpawar** [comment]
what about 1.4 version?
