### ISSUE TITLE
Github "Latest Release" is stale

### ISSUE THREAD

**Issue by tmack8001** [Netflix/zuul#490]
With the release and follow on releases for the 2.x work I would say that the latest release tag on Github should be updated to point to 2.1.2 as the "latest release".

![image](https://user-images.githubusercontent.com/2158627/43555843-67d1a78e-95b1-11e8-972e-c0511f9889f8.png)

Similarly this is the "latest" link (https://github.com/Netflix/zuul/releases/latest) which would redirect internally to Github over to the release marked as latest release (right now as https://github.com/Netflix/zuul/releases/tag/v1.2.3).

```
curl https://github.com/Netflix/zuul/releases/latest
<html><body>You are being <a href="https://github.com/Netflix/zuul/releases/tag/v1.2.3">redirected</a>.</body></html>
```

**Comment by artgon** [comment]
Done. Also made a point release to push out latest changes.

**Comment by tmack8001** [comment]
Awesome thanks Arthur
