### ISSUE TITLE
When does the project start to support routing through file or other configuration?

### ISSUE THREAD

**Issue by GoQeng** [Netflix/zuul#494]
When does the project start to support routing through file or other configuration?

**Comment by artgon** [comment]
No timeline yet but hopefully soon! :)

**Comment by d-litvinov** [comment]
Do you have any updates?

**Comment by tmack8001** [comment]
As a temporary work around I'd recommend looking at what it her users have done to support this type of routing. Especially helpful as a migration for those using spring's zuul wrapper `zuul.routes`.

Obvious or not so obvious you would need to provide your own "matching" algorithm until Zuul has one built in natively. Though like Spring a for...each over each route definition is a naive first solution that works to a point... At a certain number of routes this becomes problematic as it is O(n) runtime performance. A Trie pattern / suffix matching algorithm would be a more scalable, but initially more complex solution to this (ref: https://en.m.wikipedia.org/wiki/Trie).

**Comment by d-litvinov** [comment]
Thanks, the workaround works for me
