### ISSUE TITLE
Slack channel or live questions on Zuul 2

### ISSUE THREAD

**Issue by danesavot** [Netflix/zuul#495]
Is there any slack channel or live questions and answers on Zuul 2?

**Comment by sandy-adi** [comment]
It would be great to have one

**Comment by artgon** [comment]
I agree it might be easier in some ways, but we also don't have the bandwidth to answer them in real time. I think using Github issues is a reasonable compromise. 

It does seem like most issues are questions though, so you do make a good point. We can re-evaluate in the future.

**Comment by sandy-adi** [comment]
@artgon completely understand that your team will be stretching pretty thin to answer all the questions. Having a slack or similar channel could facilitate communication within the zuul community and may be the community will chip in. there is a slack channel named "zuulteam.slack.com" is that your internal slack channel?
