### ISSUE TITLE
How to handle multiple origin proxy for one request in zuul2?

### ISSUE THREAD

**Issue by jiangsuxd** [Netflix/zuul#497]
For example, /api/combine needs to aggregate date from origin A, B, C. Is there any appropriate way to send these origin proxy in current eventloop, instead of creating seperated thread pool.

**Comment by artgon** [comment]
Unfortunately no. Zuul is intended to be a proxy, not a request aggregator. You would have to do the requests async on a separate threadpool and then return them back to the single inbound request on the event loop.

**Comment by goodmorninggoaway** [comment]
@jiangsuxd How did you address this in your app?
