### ISSUE TITLE
How to get HTTP POST parameters in endpoint by using zuul2

### ISSUE THREAD

**Issue by bayernolive** [Netflix/zuul#500]
in zuul-sample project, Healthcheck.groovy, how to get the http post parameters?

the request command is :   curl -d "data=hello world" "http://localhost:7001/api"

    @Override
    HttpResponseMessage apply(HttpRequestMessage request) {
        //Get parameters
        request.getQueryParams();  // this can get the parameters  in the url
        //How to get POST parameters?
        request.getBody(); // this is null
        request.getInboundRequest().getBodyContents(); // this is null

        HttpResponseMessage resp = new HttpResponseMessageImpl(request.getContext(), request, 200)
        resp.setBodyAsText("healthy")

        // need to set this manually since we are not going through the ProxyEndpoint
        StatusCategoryUtils.setStatusCategory(request.getContext(), ZuulStatusCategory.SUCCESS)

        return resp
}

**Comment by artgon** [comment]
First of all, you need to do this in an `InboundFilter` not an `EndpointFilter`. Once you do that, you'll need to override `needsBodyBuffered()` method and return `true`. That will buffer the entire body and you can print it out all at once. See parent class method here: https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/filters/BaseFilter.java#L130

**Comment by bayernolive** [comment]
Thanks for your advice. that solve my question
