### ISSUE TITLE
"Authorization" Header does not pass to downstream service 

### ISSUE THREAD

**Issue by haasiniE** [Netflix/zuul#501]
The request header "Authorization" is not being passed with Spring boot version 2.0.3 zuul to downstream services.I have disabled Authorization as sensitive header but Zuul will not send Authorization header to downstream service.

Below is the present config that will work only with the following code.

zuul:
sensitiveHeaders:
routes:

Versions:
springBootVersion = '2.0.3.RELEASE'
dependencyManagement {
imports {
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Finchley.RELEASE"

}
}
compile 'org.springframework.cloud:spring-cloud-starter-netflix-zuul'

Route filter as below:

@SuppressWarnings("unchecked")
@Override
public Object run() {
	
	try {   
        RequestContext ctx = RequestContext.getCurrentContext();
        ctx.addZuulRequestHeader("Authorization","Bearer xxx");
	} catch(Exception ex) {
		log.error("Exception", ex);
		
	}
Spring boot version 1.5.7 Zuul is to able to send the header "Authorization" with the to the downstream services without adding the Authorization header through RequestHeader by using route filter.

Below is the config:

zuul:
sensitiveHeaders:
routes:

Versions:
springBootVersion = "1.5.3.RELEASE"
dependencyManagement {
imports {
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.SR1"

}
}
compile ‘org.springframework.cloud:spring-cloud-starter-zuul’

**Comment by artgon** [comment]
Please direct your question to the Spring Cloud issue tracker.
