### ISSUE TITLE
Zuul 1.3 does not reset the wrapped request parameters correctly

### ISSUE THREAD

**Issue by mjeanroy** [Netflix/zuul#507]
Hi,

First of all, I'm using Zuul in version 1.3.0 with spring-cloud-netflix-starter-netflix-zuul in version 1.4.4.

I have a problem in my application with the `SendErrorFilter` (from spring-cloud) when the filter forward the request to the error handler: in this case the request parameter are not correctly handled by the `HttpServletRequestWrapper` instance.

Here is an explanation of what happened:

1- In the  [`SendErrorFilter#run`](https://github.com/spring-cloud/spring-cloud-netflix/blob/50a02e3ba4e7c54982a37a2fcd14a07da537ffe6/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendErrorFilter.java#L91) method, the handler retrieved the `ApplicationDispatcher` to forward the request to the `/error` path. Note that the request parameters have already been read in this case, so [`HttpServletRequestWrapper#parameters`](https://github.com/Netflix/zuul/blob/56ba3ecac8d26e5257903ed9fc1b32694e137211/zuul-core/src/main/java/com/netflix/zuul/http/HttpServletRequestWrapper.java#L61) is not `null`.
2- I'm using tomcat 8.5.23, so in this case, the `ApplicationDispatcher` is an instance of `org.apache.catalina.core.ApplicationDispatcher`
3- During the forward operation, the ApplicationDispatcher [mutate the original request wrapper and call the `setRequest` on it](https://github.com/apache/tomcat/blob/94155efccd19fc3338433c63cfa5430e2d1ae00a/java/org/apache/catalina/core/ApplicationDispatcher.java#L358) and the request parameters are not the same anymore.
4- When the request is rendered (a simple JSP), the request parameters are not resolved correctly, since the `HttpServletRequestWrapper#parameters` have already been computed...

Not sure if it's clear, not easy to explain, sorry, let met know if you want me to rephrase it,, or I can try to give you a sample application if needed.

There is a mix here with spring-cloud, tomcat and Zuul, but I think the problem is with the `HttpServletRequestWrapper` which does not reset appropriate fields when the original request is set, what do you think?

I looked at the repository and I can see that zuul is now in version 2, is the 1.X version still maintained?

If not, we can plan on our side a migration and see if the problem still occurs, otherwise, and if you agree, I can work on PR. I think a simple solution could be to override the `setRequest` method in `HttpServletRequestWrapper` and resetting the `parameters` (reset it to `null`) map when it happened.

What do you think?

**Comment by artgon** [comment]
We aren't adding any new features to Zuul 1.x, but we will maintain/fix bugs as needed. I think for your specific use case, you can decorate the class and fix it for your own purposes. Otherwise, maybe the Spring folks will be willing to give you some input. Cheers.
