### ISSUE TITLE
Publish and scrape metrics

### ISSUE THREAD

**Issue by devup2** [Netflix/zuul#508]
Am trying to publish both JVM and request metrics using an endpoint filter in Zuul2. Whats the best way to scrape the JVM and request metrics recorded by BasicRequestMetricsPublisher?

**Comment by artgon** [comment]
Zuul is designed to work with Atlas: https://github.com/netflix/atlas

Getting started: https://github.com/Netflix/atlas/wiki/Getting-Started

**Comment by devup2** [comment]
We are using a prometheus + grafana.  Using  jmx node exporter, I am able to extract: com_netflix_servo_zuul_directmemory_max_value and com_netflix_servo_zuul_directmemory_reserved_value. Would be great if I could also scrape zuul.timings.request(total, proxy, internal & added) thats published from BasicRequestMetricsPublisher

**Comment by artgon** [comment]
There are ways to do this but it's not recommended -- you can try and see if it works for you or not. More info here: https://github.com/Netflix/spectator/issues/511

**Comment by muhammad-tayyab-confiz** [comment]
@devup2 trying to do the same that you wanted to do. Did you find any solution ?

**Comment by Sridharc20** [comment]
Team,
We would like to collect zuul2 metrics using prometheus. Is there any way we can do this instead of Atlas?

Or Are there any reference docker images similar to the aws-api-gateway-exporter to expose the metrics as a rest api.

Thanks
