### ISSUE TITLE
do you have a plan about supporting grpc?

### ISSUE THREAD

**Issue by ruinmoon** [Netflix/zuul#509]
I heard about the support plan for http 2 of backend.
I have a lot of interest in grpc.
Do you have a plan  support for proxy of grpc?
I expect a grpc filter including server streaming.
Can you tell me about this?
I believe it is a great plan.

**Comment by artgon** [comment]
Yeah, it's on the roadmap but can't give you a timeframe.

**Comment by artgon** [comment]
Yeah it's available with 2.x architecture. There's no need or plan for 3.x.

**Comment by lixuanbin** [comment]
where? could not find in zuul 2 documents
