### ISSUE TITLE
【ZUUL2 （2.1.3）】SurgicalDebugFilter   -  How to use  setRouteHost

### ISSUE THREAD

**Issue by brightvip** [Netflix/zuul#514]
In zuul2 SurgicalDebugFilter sets setRouteHost(HTTP://127.0.0.1:8088)
But the server that zuul2 forwards comes from eureka, I need to specify the server to debug the program.
#442

**Comment by brightvip** [comment]
[](https://github.com/Netflix/zuul/blob/da4a19ffc48d1c261c13c4ab212a23d7408091a6/zuul-core/src/main/java/com/netflix/zuul/netty/connectionpool/DefaultClientChannelManager.java#L328)

**Comment by jeminkim** [comment]
@brightvip

I think that setRouteHost is not working in Proxy Endpoint Filter of zuul2.X. You should set up specific address like **api.ribbon.listOfServers=127.0.0.1:8088** in application.properties file.
After that, you should use **setRouteVIP("api")** in inbound filter.

If you want to use setRouteHost, you develop your own End Point Filter like Proxy Endpoint Filter.
In my case, I modify OriginServer which support setRouteHost.
