### ISSUE TITLE
zuul2 http query param parse disorder

### ISSUE THREAD

**Issue by lsgggg123** [Netflix/zuul#525]
https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/message/http/HttpQueryParams.java#L41

HttpQueryParams using `ListMultimap<String, String>` as data structure to save query params, this map is support multi value of query param values, and the values is ordered, but the query param name itself become disordered, I'm afraid sometimes this may cause an accident.

**Comment by lsgggg123** [comment]
`com.google.common.collect.LinkedListMultimap` maybe better ?

**Comment by lsgggg123** [comment]
here is unit test:

![image](https://user-images.githubusercontent.com/15649907/47063505-d7b26280-d20d-11e8-9e4c-2ccdd4d774ee.png)

![image](https://user-images.githubusercontent.com/15649907/47063460-9ae66b80-d20d-11e8-8e71-55d2a6a27518.png)

**Comment by artgon** [comment]
It's not safe to rely on ordering of query param key-values because maps don't guarantee any sort of ordering. 

That said, can you provide a use case where this is necessary? Are you trying to make a decision based on enumerating keys/values in order?

**Comment by agx5109** [comment]
In a lot of cases the request param order is often used to verify the signature headers in which case re-ordering of the request params would lead to issues. 

Switching over to `LinkedListMultimap` would make a lot of sense. 

Would it be possible @artgon ?
