### ISSUE TITLE
zuul2 HttpQueryParams get() method issue

### ISSUE THREAD

**Issue by jiangsuxd** [Netflix/zuul#527]
In source code(https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/message/http/HttpQueryParams.java#L118), we can see get() method uses name.toLowerCase() as key, while getFirst() method uses original name.
public List<String> get(String name)
{
    return delegate.get(name.toLowerCase());
}
Suppose current url is xxx?cityId[]=1&cityId[]=2, invoke get("cityId") would cause none value which is not expected. Is there any special reason to use lower case of param key rather than original key?

**Comment by artgon** [comment]
Good question, will look into it.

**Comment by mrlee7** [comment]
@artgon 
Can I create a PR and handle the issue?
If possible, do you have any thoughts or opinions on this issue?

**Comment by mrlee7** [comment]
Hello @artgon I fixed this issue on #1672, Could you please take a moment to review it?
If possible, I would also like to request @sullis  to kindly join in reviewing this PR. 
Your cooperation is highly appreciated.

Thanks (_ _)
