### ISSUE TITLE
Netflix/ zuul ignores DELETE request body

### ISSUE THREAD

**Issue by raju4392000** [Netflix/zuul#528]
Hello,
Does anyone faced the below error?
we are using  Netflix/ Zuul versions
"com.netflix.zuul:zuul-core:1.3.1"
"com.netflix.zuul:zuul-netflix:1.3.1"

and the piece of backend code behind the zuul is

    @RequestMapping(value = "/deletewithbodytest", method = DELETE)
    @ResponseBody
    public Response delete(@RequestBody String requestString) {
        return Response.ok(requestString).build();
    }

Body I was passing : -d '{"someval":1}'

Below is the error I was getting:
{"errors":[],"statusCode":500,"header":null,"id":null,"status":"Failed","errorMessages":["Required request body is missing: public javax.ws.rs.core.Response
 
spring-cloud-netflix has this fix in 1.2.0 and below is the issue created
https://github.com/spring-cloud/spring-cloud-netflix/issues/949

Is there any solution for zuul-netflix?

**Comment by mattnelson** [comment]
Delete with entity has a checkered past despite being part of the [spec](https://tools.ietf.org/html/rfc7231#section-4.3.5) now...

> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

https://github.com/eclipse-ee4j/jaxrs-api/blob/2.1.2/jaxrs-api/src/main/java/javax/ws/rs/client/Invocation.java#L121-L126
https://github.com/eclipse-ee4j/jersey/blob/initial_contribution/core-client/src/main/java/org/glassfish/jersey/client/JerseyInvocation.java#L122
https://github.com/eclipse-ee4j/jersey/issues/1983
