### ISSUE TITLE
Can zuul2 be run in mulitple ServerType modes?

### ISSUE THREAD

**Issue by devup2** [Netflix/zuul#531]
Am trying to run Zuul2 in both HTTP and WEBSOCKET modes.

**Comment by artgon** [comment]
Yes, just make sure they bind on different ports. The enum in the sample app is just for demo purposes. You could run the server in all the modes simultaneously as long as they're on different ports.

**Comment by devup2** [comment]
Do websocket connections get routed using the same ribbon configurations and groovy filters?
