### ISSUE TITLE
[Question] Configuration for file upload

### ISSUE THREAD

**Issue by lovers36** [Netflix/zuul#533]
Hello,
I tried request AWS S3 REST API through zuul 2.

But it is too low performance to upload file.

for example, 5mb
direct upload to AWS : 3.6s
through zuul 2 : 36.9s

I read wiki. but I can't find solutions.
I think I don't know configuration for file upload.

I using zuul-sample. 
Modified increasing readtimeout and remove [needsBodyBuffered()] on debug.

Q1. is there any configuration for increasing performance?
Q2. is there way to request to origin during receive client's body? (for large size file upload)

**Comment by artgon** [comment]
Do you have a code sample? I can't speculate what the issue might be, but suffice it say we have teams push large amounts of data through Zuul without any latency issues. 

For Q2, Zuul by default will stream the headers and all the chunks without buffering the full client request (unless you specify that it does so).
