### ISSUE TITLE
zuul 2.1.3 interface HttpRequestMessage AND HttpResponseMessage ->method  setBodyAsText getBodyAsText ，Need to Compress or decompress

### ISSUE THREAD

**Issue by brightvip** [Netflix/zuul#538]
zuul 2.1.3 interface HttpRequestMessage AND HttpResponseMessage ->method  setBodyAsText getBodyAsText ，Need to Compress or decompress
Gzip will garble the content

**Comment by pakosaldanaort** [comment]
you have more information about this issue? @brightvip

**Comment by brightvip** [comment]
@pakosaldanaort yes

` public static String getBodyAsText(HttpRequestMessage request) {
        return  getByteAsText(request.getBody(),request.getHeaders());
    }

    public static String getBodyAsText(HttpResponseMessage response) {
       return  getByteAsText(response.getBody(),response.getHeaders());
    }

    private static String getByteAsText(byte[] bodyByte,Headers headers) {
        if (bodyByte != null && bodyByte.length > 0) {
            List<String> headersGzip = headers.get("Content-Encoding");
            boolean ifGzip = false;
            if (headersGzip == null || headersGzip.isEmpty()) {
                headersGzip = headers.get("content-encoding");
            }
            if (headersGzip != null && !headersGzip.isEmpty()) {
                for (String string : headersGzip) {
                    if (StringUtils.containsIgnoreCase(string, "gzip")) {
                        ifGzip = true;
                        break;
                    }
                }
            }

            if (ifGzip) {
                try {
                    byte[] unzippedBytes = IOUtils.toByteArray(new GZIPInputStream(new ByteArrayInputStream(bodyByte)));
                    return new String(unzippedBytes, Charsets.UTF_8);
                } catch (IOException e) {
                    return new String(bodyByte, Charsets.UTF_8);
                }
            } else {
                return new String(bodyByte, Charsets.UTF_8);
            }
        }
        return null;
    }`

**Comment by brightvip** [comment]
@artgon 
I think 
https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/filters/common/GZipResponseFilter.java
Just GZIP compression of the content on return, because I saw the extends HttpOutboundSyncFilter
I need to extend HttpInboundFilter when zuul2 accepts the request
Check if the content of the request is secure, intercept the illegal request

Is my understanding of GZipResponseFilter.java wrong?
