### ISSUE TITLE
Reject requests in Filter

### ISSUE THREAD

**Issue by matgaon** [Netflix/zuul#543]
Based on examples in stackOverflow I am trying  to reject requests in a filter - real use case being token validation.

I am calling setZuulResponse(false) and setRouteHost(null)

My simple example is as follows

    @Override
    public Object run() throws ZuulException {

        System.out.println("Session token validation filter called") ;
        RequestContext context = RequestContext.getCurrentContext();
        context.setSendZuulResponse(false);

        context.setResponseStatusCode(401);
        context.setResponseBody("{\"error\":\"Sorry No Entry . Rejected by mj\"}");
        context.setRouteHost(null);
        return null;
    }

While the client does get the correct response -- http status 401 and the error msg, I am noticing that the original target service does get called.

How do I prevent the target service from being called.

This filter is of type route.

regards

**Comment by master-starcloud** [comment]
you should change this filter type to pre , then target service not being called.

**Comment by master-starcloud** [comment]
@matgaon

**Comment by matgaon** [comment]
@master-starcloud Thank you for confirming that it needs to be PRE
