### ISSUE TITLE
Zuul Proxy: How to configure Ribbon/Hystrix on end-point/route level instead of service level

### ISSUE THREAD

**Issue by jamestrandung** [Netflix/zuul#545]
I have an `ft-admin` microservive which exposes 2 endpoints `app-config` and `app-analytic`. In my `@EnableZuulProxy` gateway project, I can define the routing rules and specify other configurations for Ribbon and Hystrix on microservice-level using the `serviceId` as following.

    zuul:
      routes:
        admin-services:
          path: /admin/**
          serviceId: ft-admin
          stripPrefix: true
    
    ft-admin:
      ribbon:
        ActiveConnectionsLimit: 2
    
    hystrix:
      command:
        ft-admin:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 10000

I'm wondering if there's a way to bring the above configurations down to endpoint-level for each `app-config` and `app-analytic` individually. The goal is to be able to give a different setting for each endpoint as following.

    zuul:
      routes:
        app-config-endpoint:
          path: /app-config/**
          serviceId: ft-admin
          stripPrefix: false
        app-analytic-endpoint:
          path: /app-analytic/**
          serviceId: ft-admin
          stripPrefix: false
    
    app-config-endpoint:
      ribbon:
        ActiveConnectionsLimit: 5
    app-analytic-endpoint:
      ribbon:
        ActiveConnectionsLimit: 2

    ...

When I run my gateway project in Debug mode with `ft-admin.ribbon.ActiveConnectionsLimit: 2`, I can see the following lines in the log.

```
c.netflix.config.ChainedDynamicProperty  : Property changed: 'ft-admin.ribbon.ActiveConnectionsLimit = 2'
c.netflix.config.ChainedDynamicProperty  : Flipping property: ft-admin.ribbon.ActiveConnectionsLimit to use it's current value:2
```

However, when I run my project with `app-config-endpoint.ribbon.ActiveConnectionsLimit: 5`, I see the following lines.

```
c.netflix.config.ChainedDynamicProperty  : Property changed: 'ft-admin.ribbon.ActiveConnectionsLimit = -2147483648'
c.netflix.config.ChainedDynamicProperty  : Flipping property: ft-admin.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
```

I've tried to search through a ton of posts but it seems like the configurations always stop at the microservice-level. The endpoint/route level configurations are completely ignore. 

I'd be very grateful if you could point me in the right direction or tell me your story if you've tried this before.

**Comment by artgon** [comment]
Please direct your question to the Spring Cloud issue tracker.
