### ISSUE TITLE
Zuul 2 and Websocket Integration

### ISSUE THREAD

**Issue by kasibkismath** [Netflix/zuul#551]
Lately, I've been working on Zuul 2 push that is the websocket integration. I have got a sample spring boot websocket app which works well without Zuul 2 integration. However, I do have problems integrating the sample app together with the Zuul 2, thus routing all the connect, disconnect and send message activities via Zuul 2.

```
//start of main.js extract
function connect() {
    var socket = new SockJS('http://localhost:7001/gs-guide-websocket');
    stompClient = Stomp.over(socket);
    stompClient.connect({}, function (frame) {
        setConnected(true);
        console.log('Connected: ' + frame);
        stompClient.subscribe('http://localhost:7008/topic/greetings', function (greeting) {
            showGreeting(JSON.parse(greeting.body).content);
        });
    });
}


function sendName() {
    stompClient.send("http://localhost:7001/app/hello", {}, JSON.stringify({'name': $("#name").val()}));
}
//end of main.js extract
```

Following the sample app for Zuul 2, the SampleServerStartup class has been modified to take the **_SERVER_TYPE_** as **_WEBSOCKET_**, therefore we have two ports which are being used according to the sample that are **_7001_** and **_7008_** for **_zuul.server.port.main_** and **_zuul.server.port.http.push_** respectively.

**_api.zuul.listOfServer_** is pointing to the spring boot app which servers the websocket backend.

However when sending the message it doesn't go anywhere and there is no clue whether these configurations are correct. If not what Am I missing?

Note: I'm using sockjs-client and STOMP

**Comment by susheel-aroskar** [comment]
Zuul server doesn't yet support proxying WebSocket connection. It allows client to maintain an open connection with the server and then push messages to the client, on that WebSocket, by sending those messages to zuul.server.port.http.push port (7008 by default). It won't proxy inbound WebSocket messages to the backend.

**Comment by gigi** [comment]
Hi!
Do you have any plans to implement routing for inbound messages independently from transport?
I think it sounds good to use already established WebSocket connection for any async client-server communication.

Smth like
```json
{
    "service": "payment",
    "someMetaInformation": {"key1": "value1"},
    "body": {"key2": "value2"}
}
```
Thanx!

**Comment by raksoras** [comment]
It's something we want to look at in future but not a high priority for us right now.

**Comment by mehdiaitbouallal** [comment]
Hi !
Did you manage to solve this problem somehow ??
