### ISSUE TITLE
[Zuul] Ability to Configure Global Connection Pool Defaults

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#552]
Currently the connection pool defaults are [hard coded](https://github.com/Netflix/zuul/blob/c34a5e47562b379d84ece323a8729985649b60cd/zuul-core/src/main/java/com/netflix/zuul/netty/connectionpool/ConnectionPoolConfigImpl.java#L51). Is there a reason for hard coding this? Can we change this to make the global defaults configurable?

**Comment by artgon** [comment]
Those are not hardcoded, they are fast properties that can be configured via Archaius. Take a look at the sample properties and wiki: https://github.com/Netflix/zuul/wiki/Core-Features#connection-pooling
