### ISSUE TITLE
Zuul to microservice is taking long on every 30th second

### ISSUE THREAD

**Issue by Adhrit2009** [Netflix/zuul#553]
We are using zuul + ribbon. I turned off Eureka .

So every 30 secs Zuul takes longer to process the request. Ideally it takes around 2ms to send the request to microservice but after 30 secs it is taking 120 ms. Can you please help me whats going on?? If It hit my microservice without zuul it is consistent 2 ms. ..can you please help me?

My Zuul configuration:

spring:
  application:
    name: xxxx
  profiles:
    active: default
  cloud:
    config:
      failFast: true
  security:
    enabled: false
  main:
    banner-mode: 'off'

eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

zuul:
  host:
    connect-timeout-millis: 60000  # starting the connection
    socket-timeout-millis: 60000   # monitor the continuous incoming data flow
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    auth:
      path: /xxx/xx/**
      stripPrefix: false
      #url: http://localhost:9003/
    xx:
      path: /xx/xx/**
      stripPrefix: false
      #url: http://localhost:9002/
    xx:
      path: /xx/xx/**
      stripPrefix: false
      #url: http://localhost:9004/
    xx:
      path: /xx/xx/**
      stripPrefix: false
      #url: http://localhost:9001/
    xx:
      path: /xx/xx/**
      stripPrefix: false
      #url: http://localhost:9006/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 120000
  eureka:
    enabled: false
  security:
    ignored: /**
  basic:
    enabled: false
  management:
    security:
      enabled: false

xx:
 ribbon:
   eureka:
      enabled: false
   ServerListRefreshInterval: 60000

**Comment by amjd** [comment]
I admittedly don't know anything about Zuul, but I was just going through an issue in this repo and I came across something which *might* be useful to you.

In issue #395, somebody mentioned that even if you disable Eureka, service discovery is still attempted every 30 seconds. So you need to set the `eureka.shouldFetchRegistry` property as `false`.

Check if that solves the issue.
