### ISSUE TITLE
Zuul, Eureka in AWS ECS

### ISSUE THREAD

**Issue by fdanismaz** [Netflix/zuul#556]
Hi,

We have many microservices in our solution deployed to AWS and now we are trying to put an API Gateway with Netflix Zuul in front of them and a service registry with Netflix Eureka.

All microservices along with service registry and zuul proxy are deployed in ECS with EC2 launch type. We successfully registered our services and API gateway to the service registry in cloud environment but we when we send a request to an underlying microservice (report service for example) over the API 
gateway, we get Zuul Forwarding Error.

We think that since we deploy our microservices to ECS, somehow our service registry cannot access to the other underlying microservices but could not resolve why.

**Comment by artgon** [comment]
So your services are registered with Eureka but cannot be connected to? Can you provide your config files and full error/response headers?

**Comment by zhaojunjie163** [comment]
Hi @fdanismaz, have you addressed the issue?

**Comment by dvsingh9** [comment]
I to got exact same issue. any help

**Comment by carlosbpf** [comment]
Anyone managed to make this work on ECS? How did you register EUREKA and made it available to the services to register?

**Comment by Shubhamr837** [comment]
same issue , it works fine in localhost but doesnt work in ecs . Eureka is registration is ok for all the services , individual services are also working but zuul doesnt forward api reaquests

**Comment by fdanismaz** [comment]
Try extending `EurekaInstanceConfigBean` and override `getHostname`. You can get the data center information by calling `AmazonInfo dataCenterInfo = (AmazonInfo)this.getDataCenterInfo()`. Based on the AmazonInfo object, you can decide to return route53 hostname, ip address, or machine hostname.

Hope this helps.

**Comment by ChristianEGB** [comment]
@fdanismaz this Config Bean in my understanding have to be into the Eureka project, right? do you have any idea of how to do the entire configuration or any resource for this?

@Shubhamr837 @carlosbpf @dvsingh9 @zhaojunjie163 did you found how to solve this? @fdanismaz did you?

**Comment by donaldfernandes** [comment]
hi.. is there a solution to this. I anyone has resolved this, appreciate some help in this regard
