### ISSUE TITLE
com.netflix.zuul.netty.connectionpool.OriginConnectException: Origin server inactive

### ISSUE THREAD

**Issue by Harlan6** [Netflix/zuul#560]
2019-03-12 16:49:36,125 WARN  com.netflix.zuul.filters.endpoint.ProxyEndpoint [Salamander-ClientToZuulWorker-4] FAILURE_ORIGIN_RESET_CONNECTION, origin = wallet, origin channel info = Channel: [id: 0x7884ebae, L:0.0.0.0/0.0.0.0:53476 ! R:/172.25.199.169:8072], active=false, open=false, registered=true, writable=false, id=7884ebae, Passport: CurrentPassport {start_ms=1552380576107, [+0=SERVER_CH_ACTIVE, +6134400=IN_REQ_HEADERS_RECEIVED, +6160100=FILTERS_INBOUND_START, +6179100=FILTERS_INBOUND_END, +6215300=ORIGIN_CONN_ACQUIRE_START, +6216800=ORIGIN_CONN_ACQUIRE_END, +6224300=OUT_REQ_HEADERS_SENDING, +9490300=OUT_REQ_HEADERS_SENT, +9504700=IN_REQ_LAST_CONTENT_RECEIVED, +9514400=OUT_REQ_LAST_CONTENT_SENDING, +9518300=OUT_REQ_LAST_CONTENT_SENT, +18110400=ORIGIN_CH_INACTIVE, +18126800=NOW]}
com.netflix.zuul.netty.connectionpool.OriginConnectException: Origin server inactive

a problem like this ,how it hanppened and what I can do

**Comment by notatent** [comment]
Hi Harlan, did you find out the reason which caused the OriginConnectionException(http response code:504)?  I'm facing the same problem.

**Comment by userdeveloper98** [comment]
The same issue for me (504 FAILURE_ORIGIN_RESET_CONNECTION), it is reproducible under high load only (200+ parallel connections). And the problem is not in origin for sure because origin server itself supports much more than 200.

**Comment by vitsja** [comment]
Facing the same issue here. Have tweaked the following ribbon properties without any effect:

ribbon.MaxAutoRetries=10
ribbon.OkToRetryOnAllOperations=true
ribbon.ConnectTimeout=30000
ribbon.ReadTimeout=30000

**Comment by artgon** [comment]
`ORIGIN_RESET_CONNECTION` implies that that your backend server closed the connection before the request could be transmitted. If you're trying to run a load test, please consult this guide: https://github.com/Netflix/zuul/wiki/Benchmarking.

**Comment by vitsja** [comment]
We already applied the mentioned configuration tweaks without any improvement. When running the load test against the healtcheck endpoint, the 504 errors vanish. Interestingly, the backend does not behave in this way, when the proxy is a simple apache2 reverse proxy. Any suggestions how to proceed? Are there any netty configurations known to you, that may solve or improve this issue?

**Comment by artgon** [comment]
What test are you running? Do you have steps to reproduce?

**Comment by vitsja** [comment]
Its kinda simple, I have an apache server as backend that responses with different sized JSON files on five different paths. Zuul simply proxies the incoming requests. Ribbon is used to determine the backends location and thats it. We use Gatling as our Benchmarking tool.

**Comment by steffentemplin** [comment]
I can very easily reproduce this.

Environment:

- VM running latest Debian Stretch
- 4 CPUs, 8 GB RAM
- apt install openjdk-8-jdk git apache2

Setup static JSON response file `/var/www/html/test.json` with contents:

```
{"data": "test"}
```

Check that the backend is working:

```
$ curl http://localhost/test.json
{"data": "test"}
```

Then clone Zuul repository and checkout tag v2.1.3. It also works with latest branch 2.1, but logging is broken there.

Apply [attached patch](https://github.com/Netflix/zuul/files/3055340/zuul-benchmark.patch.txt) to configure zuul-sample accordingly.

Launch Zuul: `./gradlew clean run -Pbench`

Verify proxying:

```
$ curl http://localhost:7001/test.json
{"data": "test"}
```
And finally launch ApacheBench:

```
$ ab -n 5000 -c 10 http://localhost:7001/test.json
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 500 requests
Completed 1000 requests
Completed 1500 requests
Completed 2000 requests
Completed 2500 requests
Completed 3000 requests
Completed 3500 requests
Completed 4000 requests
Completed 4500 requests
Completed 5000 requests
Finished 5000 requests


Server Software:        Apache/2.4.25
Server Hostname:        localhost
Server Port:            7001

Document Path:          /test.json
Document Length:        17 bytes

Concurrency Level:      10
Time taken for tests:   4.292 seconds
Complete requests:      5000
Failed requests:        10
   (Connect: 0, Receive: 0, Length: 10, Exceptions: 0)
Non-2xx responses:      10
Total transferred:      1348140 bytes
HTML transferred:       84880 bytes
Requests per second:    1165.05 [#/sec] (mean)
Time per request:       8.583 [ms] (mean)
Time per request:       0.858 [ms] (mean, across all concurrent requests)
Transfer rate:          306.77 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     1    9   9.6      5     103
Waiting:        0    8   9.3      5     102
Total:          1    9   9.6      5     103

Percentage of the requests served within a certain time (ms)
  50%      5
  66%      9
  75%     11
  80%     14
  90%     21
  95%     28
  98%     36
  99%     45
 100%    103 (longest request)
```

`Non-2xx responses:      10` <- this is what we are looking for. Number might change a bit for each run, but usually always a few requests are failing. Note that this does never happen when benchmarking against apache directly (i.e. `$ ab -n 5000 -c 10 http://localhost/test.json`).

Each of those 10 occurrences leads to such log entries:

```
2019-04-08 16:31:21,582 WARN  com.netflix.zuul.filters.endpoint.ProxyEndpoint [Salamander-ClientToZuulWorker-0] FAILURE_ORIGIN_RESET_CONNECTION, origin = apache, origin channel info = Channel: [id: 0xac523c0a, L:0.0.0.0/0.0.0.0:43464 ! R:localhost/127.0.0.1:80], active=false, open=false, registered=true, writable=false, id=ac523c0a, Passport: CurrentPassport {start_ms=1554741081568, [+0=SERVER_CH_ACTIVE, +2407976=IN_REQ_HEADERS_RECEIVED, +2442164=FILTERS_INBOUND_START, +2465676=FILTERS_INBOUND_END, +2504146=ORIGIN_CONN_ACQUIRE_START, +2508917=ORIGIN_CONN_ACQUIRE_END, +2524072=OUT_REQ_HEADERS_SENDING, +2555823=OUT_REQ_HEADERS_SENT, +2566882=IN_REQ_LAST_CONTENT_RECEIVED, +2583066=OUT_REQ_LAST_CONTENT_SENDING, +2587057=OUT_REQ_LAST_CONTENT_SENT, +13081334=ORIGIN_CH_INACTIVE, +13877506=NOW]}
com.netflix.zuul.netty.connectionpool.OriginConnectException: Origin server inactive
2019-04-08 16:31:21,583 INFO  ACCESS [Salamander-ClientToZuulWorker-0] 2019-04-08T16:31:21.571  127.0.0.1       7001    GET     /test.json      504     11817   -       2629acb4-43ad-42c5-a48a-20adac010d9f    -       "localhost:7001"        "-"     "-"     "-"     "-"     "ApacheBench/2.3"       "-"     "-"     "-"
```

**Comment by Harlan6** [comment]
I  change  the  config,but the request  per  second  is  still very  low,only  6000,how  to  improve  it  or  how  many  tps  is the  limitation?

**Comment by steffentemplin** [comment]
I opened https://github.com/Netflix/zuul/pull/567. For me it fixes the issue.

**Comment by steffentemplin** [comment]
@artgon Have you been able to reproduce it with my instructions? Is there a chance that somebody would have a look at my according merge request?

**Comment by artgon** [comment]
Hey, sorry for the delay on this, I'll take a look at it this weekend.

**Comment by artgon** [comment]
@steffentemplin thanks for the detailed bug report. This definitely looks like a legit bug where we're not handling that `Connection` header on the origin side. We do handle it correctly on the client side, in `ClientResponseWriter`.

**Comment by artgon** [comment]
Thanks everyone for your contributions!
