### ISSUE TITLE
[Question] Building Zuul from source

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#564]
I'm trying to build zuul from source. I'm getting the following error when I try to do a gradle build:

```
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '7.1.0']
> Failed to apply plugin [class 'nebula.plugin.bintray.NebulaBintrayPublishingPlugin']
   > Could not create an instance of type nebula.plugin.bintray.BintrayExtension_Decorated.
      > Could not find any public constructor for class nebula.plugin.bintray.BintrayExtension_Decorated which accepts parameters [].
```

[Gradle Stack Trace](https://gist.github.com/sandy-adi/f75c8ca43014adecb715468136ca23e4)

Has anybody encountered this issue and is there a work around this? Seems like this is happening after the recent gradle upgrade

**Comment by sandy-adi** [comment]
It was a problem with the gradle configuration, was not able to connect to the jcenter repository. Had to configure to connect to local gradle repository

```
buildscript {
    repositories {
        maven {
            url 'http://myartifactory.repository/artifactory/gradle-dev'
        }
    }
}
```

**Comment by artgon** [comment]
Thanks, fixed.
