### ISSUE TITLE
Custom LoadBalancerRule for choosing a specific Server

### ISSUE THREAD

**Issue by gkumardd** [Netflix/zuul#571]
I am trying to implement Sticky Rule approach, where I would want to specify the Server to choose from, under certain circumstances, where I know which server the traffic should go to. With Zuul1, there was a way to pass the loadbalanerkey to the Choose or ChooseServer method on a custom IRule. But not sure how this would work with Zuul2, given the Request Context nor the Session Context being not available within the IRule and/or Filter. 

Question:
1. Is there a way to get the loadbalancerkey populated / set to a value from Filter?
OR
2. Is there a way to access a cookie or header within a custom IRule? That way, at least i can share the data via header/cookie and access it.

**Comment by gkumardd** [comment]
Just to add more detail: The AbstractLoadBalancer class which all of the available LoadBa;lancers implement currently has 'null' as a key value defaulted for chooseServer method.
`public abstract class AbstractLoadBalancer implements ILoadBalancer {
    
    public enum ServerGroup{
        ALL,
        STATUS_UP,
        STATUS_NOT_UP        
    }
        
    /**
     * delegate to {@link #chooseServer(Object)} with parameter null.
     */
    public Server chooseServer() {
       return chooseServer(null);
    }

    
    /**
     * List of servers that this Loadbalancer knows about
     * 
     * @param serverGroup Servers grouped by status, e.g., {@link ServerGroup#STATUS_UP}
     */
    public abstract List<Server> getServerList(ServerGroup serverGroup);
    
    /**
     * Obtain LoadBalancer related Statistics
     */
    public abstract LoadBalancerStats getLoadBalancerStats();    
}
`

**Comment by sandy-adi** [comment]
@artgon is there a way to get access to the ZuulRequestContext on the LoadBalancer?
