### ISSUE TITLE
Request Decryption and Response Encryption using Pre and Post Filters.

### ISSUE THREAD

**Issue by dwamatu** [Netflix/zuul#574]
Hi to all,

I'm trying to intercept all calls via using Zuul.  My application has to apply a public/private key encryption. 

- I want to use the Zuul Pre-filter to decrypt (**using the servers private-key**) the message before sending the request to the downstream application.

- Also, to encrypt the response using a public key (**the clients public key**) fetched from a data store.

Question

1. Is this the best approach?
2. Is this possible to accomplish?

**Comment by dwamatu** [comment]
I was able to resovle this, using the pre and post filter for decrytion and encryption respectively.

**Comment by aperumal1** [comment]
HI @dwamatu , i tried using pre and post filter to decrypt the request and encrypt the response, but response is not getting encrypted. can you help on this.
