### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [Netflix/zuul#578]
Hello, i am a graphic designer and i love contributing my logos to open source projects as my own way of contribution. I noticed you don't have a logo. Would you mind if i contributed a logo to your project?

**Comment by carl-mastrangelo** [comment]
Hi @dee-y Thanks for the offer, but I believe Zuul has an existing logo.  I also beleive there may be copyright / trademark issues with making a logo that our team is not currently prepared to handle.
