### ISSUE TITLE
Question: How to stop execution in a authentication inbound filter in zuul 2?

### ISSUE THREAD

**Issue by wederbrand** [Netflix/zuul#580]
I'm writing a inbound filter to validate authentication. How can I reject the call and return a 401 if the authentication failed?

And from my routing class, how can I return a 404 when none of my routes are matched? 

Do I need to write a HttpSyncEndpoint just to create the status code response?

Thanks.

**Comment by sandy-adi** [comment]
@wederbrand I had a similar question #481 

I think the only way to do it is to write a EndPoint filter.
