### ISSUE TITLE
Zuul 2.0 Server CORS handling

### ISSUE THREAD

**Issue by ronisac** [Netflix/zuul#582]
Hi All,

I would like to know how we can handle CORS in Zuul 2.0.
I have created an OutboundSync filter which will add headers to response for allowing origins, headers and methods and filter ordering has been set to zero. Even though I could see those in the response headers, CORS is blocked the request and it is giving 403, bad gateway.

Anybody please help me what would have gone wrong.

Please find below code snippet of the filter

```
response.getHeaders().add("Access-Control-Allow-Origin", "*");
		response.getHeaders().add("Access-Control-Allow-Credentials","true");
		response.getHeaders().add("Access-Control-Allow-Methods", "POST, PUT, GET, OPTIONS, DELETE, HEAD");
		response.getHeaders().add("Access-Control-Allow-Headers", "*");
		response.getHeaders().add("Access-Control-Max-Age","3600");
		response.getHeaders().add("Access-Control-Expose-Headers", "content-type, genieclient, geniebrand, X-XSRF-TOKEN, authorization");
```

**Comment by qtwang** [comment]
@ronisac I make cors like this way:
public class CorsPreFilter extends HttpInboundSyncFilter {
    private static final Logger log = LoggerFactory.getLogger(CorsPreFilter.class);
    @Override
    public HttpRequestMessage apply(HttpRequestMessage request) {
        SessionContext context = request.getContext();
        context.set("Origin",request.getHeaders().getFirst(HttpHeaderNames.ORIGIN));
        return null;
    }
    @Override
    public boolean shouldFilter(HttpRequestMessage msg) {
        return true;
    }
    @Override
    public int filterOrder() {
        return 0;
    }
}


public class CorsAftFilter extends HttpOutboundSyncFilter {

    private static final Logger log = LoggerFactory.getLogger(CorsAftFilter.class);

    @Override
    public HttpResponseMessage apply(HttpResponseMessage response) {
        SessionContext context = response.getContext();
        response.getHeaders().set(HttpHeaderNames.ACCESS_CONTROL_ALLOW_ORIGIN,(String)context.get("Origin"));
        response.getHeaders().set(HttpHeaderNames.ACCESS_CONTROL_ALLOW_CREDENTIALS,"true");
        response.getHeaders().set(HttpHeaderNames.ACCESS_CONTROL_ALLOW_HEADERS,"Origin,Content-Type,authorization,Accept,token,X-Requested-With");
        response.getHeaders().set(HttpHeaderNames.ACCESS_CONTROL_ALLOW_METHODS,"POST,GET,OPTIONS,DELETE");
        response.getHeaders().set(HttpHeaderNames.ACCESS_CONTROL_EXPOSE_HEADERS,"Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-forwared-port,X-forwarded-host");
        response.getHeaders().set(HttpHeaderNames.VARY,"Origin,Access-Control-Request-Method,Access-Control-Request-Headers");
        return null;
    }

    @Override
    public boolean shouldFilter(HttpResponseMessage msg) {
        return true;
    }

    @Override
    public int filterOrder() {
        return 0;
    }
}

**Comment by ronisac** [comment]
Thanks @qtwang for the answer. I will try this option as well. For now I have extended "Http2SslChannelInitializer" class for adding CorsConfig object in CorsHandler and then add to ChannelPipeline object.
```
	super.initChannel(ch);
		
		ChannelPipeline p = ch.pipeline();
		CorsConfig corsConfig = CorsConfigBuilder.forAnyOrigin().allowNullOrigin().allowedRequestHeaders("*").exposeHeaders("location")
				.allowedRequestMethods(HttpMethod.OPTIONS, HttpMethod.PUT, HttpMethod.POST, HttpMethod.GET, HttpMethod.DELETE).build();
		p.addLast(new CorsHandler(corsConfig));
```

**Comment by DanilYusupov** [comment]
@ghost, @ronisac could You tell please, what libraries do You both use?
Because I didn't find HttpInboundSyncFilter, HttpOutboundSyncFilter and Http2SslChannelInitializer classes in org.springframework.cloud.spring-cloud-netflix-zuul and com.netflix.zuul.zuul-core libraries 😮‍💨
