### ISSUE TITLE
Creating build using gradle for Zuul2

### ISSUE THREAD

**Issue by t3chboy** [Netflix/zuul#585]
Hi guys,
We took clone of the project from this repository and made changes in all filters in sample app. 
When running below command from root folder my application runs perfectly proper.
`./gradlew -t run`
Now we want to create JAR and host it on server so when we try to create build using below  command we are facing issues.
`./gradlew fatjar`
Below are error logs while building : 

```
Configure project :
Inferred project: zuulapigateway, version: 2.1.5-SNAPSHOT
Publication nebula not found in project :.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'fatjar' not found in root project 'bczuulapigateway'. Some candidates are: 'jar'.

```

**Comment by amir-hg** [comment]
hi 
did you find any solution to create a jar packaging to run zuul 2 ?
