### ISSUE TITLE
context.getTimings() giving 0 for every time variable in BasicRequestMetricsPublisher.

### ISSUE THREAD

**Issue by muhammad-tayyab-confiz** [Netflix/zuul#588]
I am trying to calculate request completion time for the complete request cycle(i.e from api gatway to microservice and back to api gatway). I found that BasicRequestMetricsPublisher is calculating it but i am getting 0 there everytime, even if my request was successful.

**Comment by johnliucn925** [comment]
We saw same issue. Seems like these data are not populated.  I tried to override BasicNettyOrigin.getProxyTiming function with proxy timing in context and seems zuul.timings.request.proxy gets populated.  But not sure of it is right change. Still need see how to populate total and originReportedDuration. 
   @Override
    public Timing getProxyTiming(HttpRequestMessage zuulReq) {
        return zuulReq.getContext().getTimings().getRequestProxy();
       // return new Timing(name);
    }
