### ISSUE TITLE
[Question] Are there javadocs generated for zuul core?

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#589]

**Comment by artgon** [comment]
Yes, they're pushed to the public repo for each build.

**Comment by sandy-adi** [comment]
Could you please link me to the public-repo?

**Comment by maregunjob** [comment]
I think this is what you're looking for - [JFrog Bintray Netflix](https://bintray.com/netflixoss/maven/zuul/2.1.4#files/com%2Fnetflix%2Fzuul%2Fzuul-sample%2F2.1.4). The jars are available under `Files` or a direct link [here](https://bintray.com/version/files/netflixoss/maven/zuul/2.1.4?order=asc&sort=name&basePath=com%2Fnetflix%2Fzuul%2Fzuul-core%2F2.1.4&tab=files).
