### ISSUE TITLE
Question: Zuul 2 filter authentication/request validation approach

### ISSUE THREAD

**Issue by maregunjob** [Netflix/zuul#591]
Hi,

I would like to put Zuul 2 in front of my microservices and do some authentication/validation of the incoming requests. 
Each request that goes through the gateway would have an auth token and I would like to validate that token before letting the filter chain continue. I have several questions and was hoping someone could point me in the right direction.

1. Is an inbound filter the best place to put that logic or is there a better approach?

    At the moment, my idea is to do something like this:

```
class RequestAuthenticationFilter extends HttpInboundSyncFilter {

    @Override
    HttpRequestMessage apply(HttpRequestMessage request) {
         // extract header with auth token and call a webservice registered with 
         // Eureka to validate it

         if (ifTokenNotValid) {
             // let a custom endpoint (e.g. HttpSyncEndpoint) return a 401
             request.getContext()
                 .setEndpoint(UnauthorizedRequestEndpoint.class.getCanonicalName())   
         }

         // otherwise return the request to continue with the filter chain
         return request
    }
}
```

2. Token validation would be handled by a service registered in Eureka so I'm ideally looking for a way similar to how Zuul ProxeEndpoints work where you can set a routeVIP per service.
- Is there a standard approach to making that external call from the inbound filter to a service running in Eureka?

- Are there any helper classes in Zuul 2 I could use to make that request and receive the response in the inbound filter or would I need to import another library with a HttpClient, etc. to achieve this?

Thank you.

**Comment by cyberjso** [comment]
Hi @maregunjob 

Regarding item 1) It seems a way  of achieving  an Authentication filter interrupting the flow is doing what was described on #481.  

Another way is letting the Auth filter be the last on the filter chain. By doing this way It will override the endpoints set by other filters, [like this example](https://github.com/cyberjso/zuul2-k8s-hello).The downside here is that all filters will be performed even if the request is not authorized.

**Comment by maregunjob** [comment]
Thanks @cyberjso for the suggestions. I'm afraid the 2nd link doesn't work. I never got the chance to implement this use case as we've moved away from Zuul 2 due to its lack of support for Java versions higher than 8 (I'm not sure if that's still the case) though we may come back to it one day. Thanks anyway.
