### ISSUE TITLE
Question: Zuul 2 support for newer Java versions

### ISSUE THREAD

**Issue by maregunjob** [Netflix/zuul#593]
Hi,

I understand that Zuul 2 runs on Java 8. I've tried to run it on Java 11, but it didn't work and I haven't been able to spend too much time and investigate why. I suppose some of the dependencies or zuul core itself is not compatible with higher versions of Java. 

Are there plans to get Zuul 2 working with newer versions of Java?

Thank you.

**Comment by artgon** [comment]
Yes, we will support Java 11 in the future. No timeline yet.

**Comment by maregunjob** [comment]
Great, thank you. I'll keep on eye on the project.

**Comment by sandy-adi** [comment]
> Yes, we will support Java 11 in the future. No timeline yet.

Eagerly waiting

**Comment by Maxeh** [comment]
Hey everyone, any news on this? Will there be a Java 11 support? We need Java 11 in our project for the SSL termination which requires CurveX25519 (only available in Java 11).

**Comment by carl-mastrangelo** [comment]
Zuul 2 works with Java 11, we test regularly for it now.

**Comment by samar-bizongo** [comment]
is Zuul 2 working on Java 17 ?
