### ISSUE TITLE
Zuul2.x：使用eurela服务发现-进行路由 

### ISSUE THREAD

**Issue by zhangyang-1** [Netflix/zuul#603]
实在是不理解,这个配置不生效
Zuul可与Eureka无缝协作，但也可配置为使用静态服务器列表或您选择的发现服务。

使用Eureka服务器的标准方法如下所示：

＃ ##负载平衡与后端尤里卡

eureka.shouldUseDns = true
 eureka.eurekaServer.context = discovery / v2
 eureka.eurekaServer.domainName = discovery $ {environment} .netflix.net
 eureka.eurekaServer.gzipContent = true

eureka.serviceUrl.default = http：// $ {region}。$ {eureka.eurekaServer.domainName}：7001 / $ {eureka.eurekaServer.context}

api.ribbon.NIWSServerListClassName = com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
 api.ribbon.DeploymentContextBasedVipAddresses = api-test.netflix.net：7001
在此配置中，您必须指定您的Eureka上下文和位置。鉴于此，Zuul将与尤里卡对给定的VIP自动选择服务器列表api 功能区客户端。您可以找到有关功能区配置的详细信息在这里

**Comment by carl-mastrangelo** [comment]
Hi, can you restate your issue in English?   I don't know if anyone working on Zuul will be able to help otherwise.
