### ISSUE TITLE
zuul servletPath not authenticated after Spring boot 2 migration

### ISSUE THREAD

**Issue by aleboulanger** [Netflix/zuul#617]
I'm not able to authenticated the user with Spring security (Spring boot 2 app) when i'm using Zuul 1.x and this kind of configuration : `zuul.servletPath=/upload`.

The authentication is set to anonymous whereas an Authorization request header is set. 

> The authentication works well with zuul routes 

> I'm using servlet path in order to upload large files (>1go)

**Comment by carl-mastrangelo** [comment]
Hi @aleboulanger,     We are currently not supporting Zuul 1.x any more, can you upgrade to Zuul 2.x?

**Comment by aleboulanger** [comment]
Zuul 2 is not supported by Spring boot 2 since there are develop their own gateway. 
So there is no official documentation about this topic.
But i can try to override the zuul version defined in the BOM of Spring boot.

**Comment by carl-mastrangelo** [comment]
There doesn't appear to be anything else we can do here.   Unfortunately Netflix is only supporting the latest Zuul.   If you'd like to send a PR to allow the previous configuration style, we can review it.   If not, I am going to close this issue out.
