### ISSUE TITLE
[Proposal] - Remerge 2.1 branch into master

### ISSUE THREAD

**Issue by carl-mastrangelo** [Netflix/zuul#621]
A common method of source control involves having a single main development branch, and splitting off feature branches as they are cut.   I would like to apply this to Zuul.   Specifically, I would like to:

1.   Make `master` the primary development branch.   This is where I think most git users would expect to make modifications.
2.   Make `2.1` branch a fork off of master, called `2.1.x`
3.   Bump master to 2.2.0-SNAPSHOT
4.  Primary development should go on to the master branch, and be cherry picked into 2.1.x.

Internal users of Zuul can track 2.2.0-SNAPSHOT on the master branch still affording the rapid development cycle, Netflix needs.

@artgon @kerumai WDYT?

**Comment by kerumai** [comment]
Yeah seems reasonable.

**Comment by artgon** [comment]
What's the benefit of this approach vs long-lived version branches?
