### ISSUE TITLE
FilterLoader.getFilter why not put the filter to the filterRegistry

### ISSUE THREAD

**Issue by craigwu9** [Netflix/zuul#626]
` 
public ZuulFilter getFilter(String sCode, String sName) throws Exception {

        if (filterCheck.get(sName) == null) {
            filterCheck.putIfAbsent(sName, sName);
            if (!sCode.equals(filterClassCode.get(sName))) {
                LOG.info("reloading code " + sName);
                filterRegistry.remove(sName);
            }
        }
        ZuulFilter filter = filterRegistry.get(sName);
        if (filter == null) {
            Class clazz = compiler.compile(sCode, sName);
            if (!Modifier.isAbstract(clazz.getModifiers())) {
                filter = filterFactory.newInstance(clazz);
            }
        }
        return filter;

    }`

why not  put filter to filterRegistry after get a new instance from filterFactory?

**Comment by carl-mastrangelo** [comment]
Is this causing you an issue?

**Comment by craigwu9** [comment]
no， just confused
