### ISSUE TITLE
Why zuul2 has a high delay under low pressure

### ISSUE THREAD

**Issue by weitongming** [Netflix/zuul#627]
zuul version:2.1.3
architecture: zuul + tomcat7

solution 1:

Pressure measuring tool：jmeter with 1 thread
An tomcat http interface request takes almost 7ms , and the jmeter pressure measurement data is as follows：

![image](https://user-images.githubusercontent.com/15322040/65652598-dd7f0d80-e044-11e9-84c1-4237555b4fe3.png)

When I forwarded this request through zuul2 ，i got almost 48ms latency .

![image](https://user-images.githubusercontent.com/15322040/65652272-c7bd1880-e043-11e9-85b5-4521fa883240.png)

what happend to zuul and why the latency of zuul is so high?

Situation has changed under high pressure:jmeter with 100 thread

tomcat:
![image](https://user-images.githubusercontent.com/15322040/65652575-ccce9780-e044-11e9-86fc-d35d2a103b4a.png)

proxy from zuul:
![image](https://user-images.githubusercontent.com/15322040/65652652-07d0cb00-e045-11e9-8db2-6b52efd0fdf6.png)

It seems that zuul did not cause any delay. But why zuul2 has a high delay under low pressure？

Can anyone tell me why and how to resolve this problem ,thansk.

**Comment by JustyouLs** [comment]
unbelievable!

**Comment by carl-mastrangelo** [comment]
Sorry, we don't know what your code is doing.    You'll need to either provide a reproducible case, or gather profiling information on your server to debug this further.

**Comment by weitongming** [comment]
Actually，i just found an incredible thing.
In my zuul project ,there are several different filters for different uses。
If i override the needsBodyBuffered method extend from HttpInboundFilter ,like:
![image](https://user-images.githubusercontent.com/15322040/65814147-b2e1b000-e210-11e9-8b1f-a3790daad1f1.png)
All the latency  has gone ,  the jmeter pressure measurement data is as follows
proxy from zuul:
![image](https://user-images.githubusercontent.com/15322040/65814171-f4725b00-e210-11e9-9e24-4c3b1b30c07b.png)
tomcat:
![image](https://user-images.githubusercontent.com/15322040/65814183-0bb14880-e211-11e9-887e-6ebaf7f57f8b.png)
I can reproduce it with zuul 2.1.3 and any tomcat , it is amazing.

**Comment by carl-mastrangelo** [comment]
@weitongming As I said, you'll need to bring some more evidence to debug this further.  You can use YourKit, or Async Profiler, or another profiler to see what is happening differently in your server.
