### ISSUE TITLE
FilterFileManager.init()  has exception occurred

### ISSUE THREAD

**Issue by shaoqinhe** [Netflix/zuul#639]
Exception during lifecycle processing
java.lang.IllegalStateException: The lifecycle method [init] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PostConstruct()] on annotated element [public void com.netflix.zuul2.app.FilterFileManagerDy.init() throws java.lang.Exception] of type [METHOD]

**Comment by carl-mastrangelo** [comment]
@shaoqinhe what was the exception?

**Comment by shaoqinhe** [comment]
FilterFileManager类 的init()方法有throws Exception，而glassfish调用@PostConstruct注解时，不能把throws Exception写在方法后面，需要try{}catch{}才可以。

**Comment by carl-mastrangelo** [comment]
We would need ned to know what exception was thrown in order to fix it.  Please provide the full stack trace.
