### ISSUE TITLE
Does Zuul Proxy work with uWSGI?

### ISSUE THREAD

**Issue by yan-khonski-it** [Netflix/zuul#678]
I use Zuul Proxy in our platform. Spring Cloud gateway uses Zuul Proxy.
Our platform has a service written in python 3.6 and it runs as uWSGI application. 

Problem is that every second request fails.  My college mentions it here
https://stackoverflow.com/questions/57714898/uwsgi-and-zuul-every-other-request-fails

I checked with wireshark and found out that (I do not know why) after first request was successfully routed and responsed, Zuul would close the connection, so when client makes another HTTP request, Zuul proxy tries to forward it and get error

```
com.netflix.zuul.exception.ZuulException: Forwarding error
...
Caused by: com.netflix.client.ClientException: null
...
Caused by: java.lang.RuntimeException: org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
```

However, if we have nginx between Zuul and uWSGI, it works. Alternatively, if we run our python application (it uses Flast framework) **without uWSGI server, there is no problem**!

Meanwhile, I am going to make a test project to demonstrate you this problem.

**Comment by carl-mastrangelo** [comment]
@yan-khonski-it You will probably need to provide more info.   I don't think we have any sort of wsgi integration, so I would be curios to hear it works.

**Comment by TranDatDT** [comment]
I'm facing the same error. Don't know why.

**Comment by TranDatDT** [comment]
I found the solution for this problem. Simply add `Connection: close` in response header using `add-header` in uwsgi.

**Comment by yan-khonski-it** [comment]
> I found the solution for this problem. Simply add `Connection: close` in response headers using `add-header` in uwsgi.

It did not work in our case. We have tried to force connection closing with header `Connection: close`, it did not work. When I have more time, I will play around with uWSGI application server to see if it could resolve the problem.

**Comment by arpanagrawalGor** [comment]
Were you able to solve it. I am getting the same error.
