### ISSUE TITLE
Is there a way to get and set path variables from Zuul RequestContext within preFilter class

### ISSUE THREAD

**Issue by RajChitta** [Netflix/zuul#683]
Does zuul Request Context provide any methods to get and set path variables of the request?

e.g. :

The original request url is
http://my.domain/uri/acctNbr/balance

From this url, I want to get value of acctNbr (ex- 123456), manipulate/encrypt it and set back (as ex- abcgy0-=gyz-yubhgyt45-0==), into request url.

**Comment by carl-mastrangelo** [comment]
Yes you can do this.  I recommend you use Zuul 2, which calls this SessionContext.

**Comment by RajChitta** [comment]
@carl-mastrangelo, I am using spring-cloud-starter-netflix-zuul 2.1.1.RELEASE version, I don't see SessionContext even in 2.1.3.RELEASE as well.

Could you please provide more details.

**Comment by carl-mastrangelo** [comment]
https://github.com/Netflix/zuul/blob/v2.1.1/zuul-core/src/main/java/com/netflix/zuul/context/SessionContext.java
