### ISSUE TITLE
Running zuul-netflix-webapp

### ISSUE THREAD

**Issue by cprithviraj** [Netflix/zuul#7]
Hello there,
I have set up Eureka server (checked with sample server and client) for Zuul.
For Running zuul-netflix-webapp, I have following questions:
1. What changes do I have to do in zuul.properties file in zuul-netflix-webapp\src\main\resources folder?
2. Is there any other place I need to make any change?
3. I am providing the IP address of the server where Cassandra is running. Is anything else expected?
4. I have Eureka (server and service) and Zuul running on different machines. For eureka service running on the Eureka Server, the eureka.serviceUrl.default property reads as http://localhost/eureka/v2. But the same property in zuul.properties reads as http://hostname/eureka/v2. Is that correct?

With all these changes, I am not able to see any integration between zuul and eureka happenning. 

Overall, I want to understand the architecture diagram of the Zuul-Eureka-Cassandra together and a case study which describes a minimum set up of Zuul required with Eureka and Cassandra.

**Comment by NiteshKant** [comment]
Projects like [RSS recipe](https://github.com/Netflix/recipes-rss), [acmeair](https://github.com/acmeair/acmeair) have since described the architecture used in Netflix with Zuul, Eureka, Cassandra and I think the wiki here describes how to use the sample app. Closing this issue.
