### ISSUE TITLE
Zuul 2.1 links broken in Wiki

### ISSUE THREAD

**Issue by tmack8001** [Netflix/zuul#707]
Since there is no longer a tag 2.1 in the repo all links in the wiki broke unintentionally. If Github allowed PRs to wikis (benefit of having all .md files within the repo instead of the built in Wiki IMO) I would have created a PR to fix this issue (instead below is a diff of what I think fixes this).

https://github.com/Netflix/zuul/tree/2.1/zuul-core no longer resolves to source code and instead should be https://github.com/Netflix/zuul/tree/master/zuul-core.

Attached is a git diff replacing all 2.1 links with master.
[update-2.1-links.patch.zip](https://github.com/Netflix/zuul/files/4077691/update-2.1-links.patch.zip)

**Comment by carl-mastrangelo** [comment]
thanks for the notice, I'll look through.

**Comment by carl-mastrangelo** [comment]
Alright, should be fixed now.  Thanks @tmack8001 for bring this to our attention!
