### ISSUE TITLE
.NET style :(

### ISSUE THREAD

**Issue by KamilJedrzejuk** [Netflix/zuul#713]
https://github.com/Netflix/zuul/blob/a065cccf757184219ca2cdd7dd098a497121e89f/zuul-core/src/main/java/com/netflix/zuul/RequestCompleteHandler.java#L22

**Comment by carl-mastrangelo** [comment]
We have adopted the Google style for new changes, but don want to change the old code just fro restyling.    (i.e. don't change the blame-line)
