### ISSUE TITLE
[Defect] Need ability to support SNI

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/zuul#735]
Currently when zuul routes to origins over https, it creates an SSLHandler without setting the SNI. This works for most cases, but for cases where the service may require SNI the SSL handshake fails. Here's the snippet from the [initChannel](https://github.com/Netflix/zuul/blob/ceee0a3f40d043ad57acb86b8e2a5e24ac3ba734/zuul-core/src/main/java/com/netflix/zuul/netty/connectionpool/DefaultOriginChannelInitializer.java#L64) method of [DefaultOriginChannelInitializer](https://github.com/Netflix/zuul/blob/ceee0a3f40d043ad57acb86b8e2a5e24ac3ba734/zuul-core/src/main/java/com/netflix/zuul/netty/connectionpool/DefaultOriginChannelInitializer.java)

```
if (connectionPoolConfig.isSecure()) {
   pipeline.addLast("ssl", sslContext.newHandler(ch.alloc()));
}
```

if this can be updated to something along the lines below, it will help route to origins that need the SNI

```
SslHandler sslHandler = null;
if (connectionPoolConfig.isSecure()) {
    String sni = connectionPoolConfig.getSNI();
    if (sni != null) {
        int securePort = connectionPoolConfig.getSecurePort();
        sslHandler = sslContext.newHandler(ch.alloc(), sni, securePort);
    }else {
        sslHandler = sslContext.newHandler(ch.alloc());
    }
    pipeline.addLast("ssl", sslHandler);
}
```

Please let me know if this looks like the right approach, We've an issue right now because of this and would like to address it as soon as possible.

**Comment by artgon** [comment]
What's the use case for having SNI on the client side?

**Comment by sandy-adi** [comment]
> What's the use case for having SNI on the client side?

oh no the client doesn't need it. The service that is being proxied via zuul needs it. So we need the ability to set the peer host when creating the ssl handler.

**Comment by artgon** [comment]
I'm still not clear on the use case. You want to proxy the SNI bytes from the incoming request to the outbound request? Why does your backend need SNI?

**Comment by sandy-adi** [comment]
The backend [servers are behind a load balancer](https://www.cloudflare.com/learning/ssl/what-is-sni/). This is a common use case where the client has to send in the SNI to the server.

**Comment by sandy-adi** [comment]
@artgon did that make sense?

**Comment by artgon** [comment]
It's interesting that your backends are also behind load balancers. Is that in lieu of a discovery mechanism? I can see what you're trying to do but it's not a use that we're planning to support.

**Comment by artgon** [comment]
We do, however, plan to support SNI on the front end. This will allow you to terminate multiple TLS certs on the same port.

**Comment by sandy-adi** [comment]
> It's interesting that your backends are also behind load balancers. Is that in lieu of a discovery mechanism? I can see what you're trying to do but it's not a use that we're planning to support.

most of our backends do not use eureka for service discovery, they are either existing services or new services on Kubernetes. We are basically running zuul in stand alone mode as our edge gateway. All east west traffic is handled within kubernetes or other solutions. I understand you don't have plans of supporting it. Could you please take a look at #739 this doesn't change the existing behavior but gives us the ability to extend and customize the Default behavior.

**Comment by artgon** [comment]
I think you can solve this without having to send us a PR. You're already on the right track, but essentially this is what you need to do in your app (which is what we do in closed-source Zuul as well):

1. Create your own `OriginManager` (e.g. `BasicNettyOriginManager`) and bind it in your app
2. Create your own `NettyOrigin` (e.g. `BasicNettyOrigin`) that gets initialized in the manager above
3. Create your own `DefaultClientChannelManager` that gets initialized in the Origin class above
4. Create your own  `DefaultOriginChannelInitializer` that sets SNI bytes on the `sslContext`

Once you have these 4 pieces in place, you can customize any piece of the origin side of the request. We do this internally for all kinds of custom features that make sense for Netflix but wouldn't necessarily make sense for the OSS project.

**Comment by sandy-adi** [comment]
> I think you can solve this without having to send us a PR. You're already on the right track, but essentially this is what you need to do in your app (which is what we do in closed-source Zuul as well):
> 
> 1. Create your own `OriginManager` (e.g. `BasicNettyOriginManager`) and bind it in your app
> 2. Create your own `NettyOrigin` (e.g. `BasicNettyOrigin`) that gets initialized in the manager above
> 3. Create your own `DefaultClientChannelManager` that gets initialized in the Origin class above
> 4. Create your own  `DefaultOriginChannelInitializer` that sets SNI bytes on the `sslContext`
> 
> Once you have these 4 pieces in place, you can customize any piece of the origin side of the request. We do this internally for all kinds of custom features that make sense for Netflix but wouldn't necessarily make sense for the OSS project.

we are doing that right now actually. The problem is our pieces are pretty much a copy of the default classes except for the small piece that creates the sslHandler. We would like to make sure we get any default behavior changes in the future without having to copy over the code to our new components. Not sure if you looked at the PR, but it would be very helpful to us from a maintenance point of view if you can accept the changes. All we are doing is creating accessor methods to enable overrides where needed.

**Comment by sandy-adi** [comment]
@artgon hope all is well?

Any thoughts regarding 

> > I think you can solve this without having to send us a PR. You're already on the right track, but essentially this is what you need to do in your app (which is what we do in closed-source Zuul as well):
> > 
> > 1. Create your own `OriginManager` (e.g. `BasicNettyOriginManager`) and bind it in your app
> > 2. Create your own `NettyOrigin` (e.g. `BasicNettyOrigin`) that gets initialized in the manager above
> > 3. Create your own `DefaultClientChannelManager` that gets initialized in the Origin class above
> > 4. Create your own  `DefaultOriginChannelInitializer` that sets SNI bytes on the `sslContext`
> > 
> > Once you have these 4 pieces in place, you can customize any piece of the origin side of the request. We do this internally for all kinds of custom features that make sense for Netflix but wouldn't necessarily make sense for the OSS project.
> 
> we are doing that right now actually. The problem is our pieces are pretty much a copy of the default classes except for the small piece that creates the sslHandler. We would like to make sure we get any default behavior changes in the future without having to copy over the code to our new components. Not sure if you looked at the PR, but it would be greatly appreciated and very helpful to us from a maintenance point of view if you can accept the changes. All we are doing is creating accessor methods to enable overrides where needed.
