### ISSUE TITLE
SimpleRouteLocator bug

### ISSUE THREAD

**Issue by Barzarrhey** [Netflix/zuul#790]
when no "zuul.ignored-services=*" is configured，zuul will auto route from eureka, and when service named with "-", the route will be set with only the string after "-".
such as service-id "eureka-server", will route "/server/{name}", and it also raise a warning that "Illegal repetition near index 7" or something. 

java 11
spring-cloud-starter-netflix-eureka-client: 2.2.2.RELEASE
spring-cloud-starter-netflix-zuul: 2.2.2.RELEASE
spring-cloud-dependencies: Greenwich.SR5

there also may have bugs in eureka, but i only debug in zuul. 

Any one have the same problems?

**Comment by artgon** [comment]
You'll have to direct your question to the Spring Cloud folks.
