### ISSUE TITLE
 route redirect bug when upgrading to java 11

### ISSUE THREAD

**Issue by RuanNunes** [Netflix/zuul#810]
**this way it works in java 8 but in java 11 the zull gets lost and always redirects to the first**

zuul.routes.cashout-24horas.path=/c1/**
zuul.routes.cashout-24horas.url=http://www.terra.com.br
zuul.routes.cashout-24horas.auth-type=NONE
zuul.routes.cashout-24horas.allowed-methods=GET

zuul.routes.cashout-24horas-authorization.path=/c2/**
zuul.routes.cashout-24horas-authorization.url= http://www.uol.com.br
zuul.routes.cashout-24horas-authorization.auth-type=NONE
zuul.routes.cashout-24horas-authorization.allowed-methods=POST

**this way it works in java 8 and java 11. Can someone explain to me why this problem**

zuul.routes.cashout-24horas-auth-status.path=/c1/**
zuul.routes.cashout-24horas-auth-status.url=http://www.terra.com.br
zuul.routes.cashout-24horas-auth-status.auth-type=NONE
zuul.routes.cashout-24horas-auth-status.allowed-methods=GET

zuul.routes.cashout-24horas-authorization.path=/c2/**
zuul.routes.cashout-24horas-authorization.url=http://www.uol.com.br
zuul.routes.cashout-24horas-authorization.auth-type=NONE
zuul.routes.cashout-24horas-authorization.allowed-methods=GET

**Comment by carl-mastrangelo** [comment]
What version of Zuul are you using?

**Comment by RuanNunes** [comment]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
            <version>2.1.5.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-netflix-core</artifactId>
            <version>2.1.5.RELEASE</version>
        </dependency>

**Comment by carl-mastrangelo** [comment]
I don't believe Zuul 2 is part of that.

**Comment by 468165108** [comment]
you mean that the  GE http request is not work?

**Comment by carl-mastrangelo** [comment]
What I mean is I think Zuul is not related to the failure here.  Also, Spring integrates with Zuul 1, which is no longer maintained.  We test with JDK 11  in our CI with Zuul 2.
