### ISSUE TITLE
Get default values for dynamic zuul properties

### ISSUE THREAD

**Issue by vitsja** [Netflix/zuul#822]
I would like to know if there is any built in mechanism to get the default configuration. At the moment I have a bunch of DynamicProperties loaded from files, for which I can easily extract this information, I am struggling to get all default values for untouched DynamicProperties used by zuul. I need this information to provide an admin a centralized overview of the current configuration. I can't find a valid approach so far.

**Comment by carl-mastrangelo** [comment]
Zuul's configuration extends from the Apache Commons configuration.  I think the provider is pluggable so if you know yours, you can use `Configuration.getKeys()` to iterate through.  There seems to be many providers, so I can't tell which one is actually being used in OSS Zuul.

**Comment by vitsja** [comment]
This was already considered. Sadly the keys do represent only the values that are specified by the resources. If a value is not present in the resource and the configured default value, that is hard coded, is used. This keys value pairs are not accessible afterwards. The wrapper around the DynamicProperty instances seems to cache those values, but there is no hook available to persist those.

**Comment by artgon** [comment]
I'm not aware of any mechanism that does this, maybe @twicksell or @qiangdavidliu have some ideas.

**Comment by twicksell** [comment]
Those defaults are not captured anywhere, so there is no easy way to get a listing of them. There are two methods I'm aware of for dealing with this situation. 

1. Zuul can create an admin endpoint and dump the values of all of its configurations, which would include the defaults. 
2. You could copy from the [Spring approach](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html#configuration-metadata-annotation-processor) by creating a custom annotation processor to capture those default values and record them for later use.

**Comment by vitsja** [comment]
> Those defaults are not captured anywhere, so there is no easy way to get a listing of them. There are two methods I'm aware of for dealing with this situation.
> 
> 1. Zuul can create an admin endpoint and dump the values of all of its configurations, which would include the defaults.

The defaults are not cached, if their origin is exclusively in the code. As soon as they come from a source, they are accessible from the configuration

> 2. You could copy from the [Spring approach](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html#configuration-metadata-annotation-processor) by creating a custom annotation processor to capture those default values and record them for later use. Any other code parsing method would work, this is just a concrete example I've seen used well.

Thanks, I will take a look.
