### ISSUE TITLE
Documentation for monitoring capabilities in Zuul

### ISSUE THREAD

**Issue by aloysiustany** [Netflix/zuul#825]
I am looking to monitor my endpoints which are behind the Zuul gateway. I am interested to know metrics such as successful calls count, failed calls count, duration of calls etc.
I am looking for any documentation that talks about how we can setup such monitoring in Zuul.

**Comment by artgon** [comment]
Zuul supports Atlas metrics (https://github.com/Netflix/atlas/wiki) out of the box and should have a comprehensive set of metrics. You can also extend the `BasicNettyOrigin` to add your own detailed metrics for your specific needs.
