### ISSUE TITLE
Failed to get request body in HttpOutboundSyncFilter

### ISSUE THREAD

**Issue by dianov** [Netflix/zuul#829]
I'm trying to get a full body of incoming (original) request (or request that Zuul sends to the target service) in HttpOutboundSyncFilter like this (Kotlin):
```java
class MyFilter: HttpOutboundSyncFilter() {
    override fun shouldFilter(msg: HttpResponseMessage): Boolean = true

    override fun apply(response: HttpResponseMessage): HttpResponseMessage {
        log.debug { "Request=${response.outboundRequest.bodyAsText}" }
        return response
    }

    override fun filterOrder(): Int {
        return 1
    }

    override fun needsBodyBuffered(input: HttpResponseMessage?): Boolean {
        return true
    }
}
```
Sometimes I get a full request body, and sometimes not (null). When I get null, hasCompletedBody returns false. However, I don't expect this cause I've overridden needsBodyBuffered.

The question is - is it possible to get a full body of the request in outgoing filters? If so, what am I doing wrong?

**Comment by carl-mastrangelo** [comment]
It looks like you are logging the outbound request, not the inbound response.

**Comment by kirillovsky** [comment]
Issue actual for me too.  Can i read full incomming requests body on `HttpOutboundSyncFilter`?
