### ISSUE TITLE
How to collect metrics emitted by zuul2 in a text file?

### ISSUE THREAD

**Issue by rnacharya** [Netflix/zuul#863]
We want to collect all the metrics that zuul emits such as zuul.timings.request.total, etc. We want to make use of our own tools to display these metrics. 
Please give a code example of how to collect at least one metric. So that we get an idea on how it should be done. 
Thanks in advance :)

**Comment by carl-mastrangelo** [comment]
You can take a look at https://github.com/Netflix/spectator which is what Zuul uses for metrics.  I believe there is file-exporter plugin built in.

**Comment by rnacharya** [comment]
I found a MetricPoller class in Zuul-core(2.1.5) that polls few metrics. I think this covers just the servo metrics. 
I have 2 questions:
1. Are Servo and Spectator collecting different set of metrics?
2. Can I have just one Poller to poll all the metrics provided by zuul?
3. Can I have this poller running from the Bootstrap class so that it runs as long as the server is running?

**Comment by rnacharya** [comment]
Also, metrics such as zuul.timings.request.* have 0 value when I log their values at BasicRequestMetricsPublisher where the values are getting recorded

**Comment by carl-mastrangelo** [comment]
Servo is the previous generation of Spectator.  Spectator is what should be preferred.  You can have just one poller which reads from the shared registry.  I am not sure about zuul.timings metric, they are recorded properly when I checked our running instances.

**Comment by rnacharya** [comment]
Could you tell me which class should be referred, to poll spectator metrics?

**Comment by johnliucn925** [comment]
What we did 1. spectator-reg-micrometer . 2 create our own implementation of  BasicRequestMetricsPublisher, and report data with Micrometer. 
totalRequestTime in BasicRequestMetricsPublisher is 0 because timing is not started. you need have a way to start it.   requestPoxy and origin data are fine.

**Comment by rnacharya** [comment]
@johnliucn925, What do you mean by starting the timing?

**Comment by johnliucn925** [comment]
https://github.com/Netflix/zuul/blob/master/zuul-core/src/main/java/com/netflix/zuul/stats/Timing.java#L41
