### ISSUE TITLE
How to send request body to external service using pre filter

### ISSUE THREAD

**Issue by rahul-ara** [Netflix/zuul#867]
Hi to all,
I want to route to external api by passing request body using pre filter.  I tried below code, sent data using postman, it is not working.
@Override
	public Object run() {

		RequestContext ctx = RequestContext.getCurrentContext();
		String key = ctx.getRequest().getParameter(API_KEY);
		
		HttpServletRequest request = ctx.getRequest();
		InputStream in = null;

		try {
			in = request.getInputStream();
			String body = StreamUtils.copyToString(in, Charset.forName("UTF-8"));
			ctx.set(body);
		String redirectURL = "url for external api";
ctx.getResponse().sendRedirect(redirectURL);
		} catch (Exception e1) {
			e1.printStackTrace();
		}
my requirement is pass request body to external service api. Could any one please help me.
Thanks

**Comment by rahul-ara** [comment]
Hello
Thank you for your reply.
I am using spring boot application 2.3.1 version with spring-boot-starter-netflix-zuul and the zuul core version is 1.3.1. It does not have the method needsBodyBuffered. 
So I am trying with  zuul core 2.1.6 version with my spring boot application 2.3.1 version. but my spring boot application is not working.

Could you please help how to fix this issue in spring boot 2.3.1 version. Thank you

**Comment by johnliucn925** [comment]
In your code, request.getInputStream() is trying to get request body. If this does not work, you need check  shouldBufferBody to see why your request does not work.  
`        boolean should = false;
        if (req.getContentLength() > 0) {
            should = true;
        }
        else if (req.getContentLength() == -1) {
            final String transferEncoding = req.getHeader(ZuulHeaders.TRANSFER_ENCODING);
            if (transferEncoding != null && transferEncoding.equals(ZuulHeaders.CHUNKED)) {
                RequestContext.getCurrentContext().setChunkedRequestBody();
                should = true;
            }
        }

        return should;`
