### ISSUE TITLE
Help! - Zuul hangs up response from Microservice when request takes too long.

### ISSUE THREAD

**Issue by djaquels** [Netflix/zuul#868]
Hello community. At the Job where I am working we have to manage long files and some microservices takes over 4:00 to 5:00 minutes to process those files.

To manage our microservices we use a Reverse-Proxy architecture using Eureka Server and Zuul . The problem is that when we call a service the Zuul proxy send the request right. And for short requests (30s) everything works fine. But when the response takes too long the response never arrives to the client. The nex image is an example of the state of the request using POSTMAN.  The client stays waiting the response.

We configure the ribbon and hystrix parameters but still no succes. Hope somebody can help finding the problem.

The configuration we have is the next:

```
spring.application.name=ZuulGateway
server.port=8765
eureka.client.serviceUrl.defaultZone = http://192.168.100.236:8761/eureka
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.enabled=true

ribbon.ReadTimeout= 90000
ribbon.ConnectTimeout= 90000


zuul.host.max-total-connections=1000
zuul.host.max-per-route-connections=100
zuul.semaphore.max-semaphores= 500

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=1000000


zuul.routes.cargadorclip.path=/deu/**
zuul.routes.cargadorclip.serviceId=CargadorClip
zuul.routes.cargadorcxcta.path=/cxcta/**
zuul.routes.cargadorcxcta.serviceId=CargadorCXCTA
zuul.routes.cargadorcxc.path=/cxc/**
zuul.routes.cargadorcxc.serviceId=CargadorCXC
# Aqui le movi yo
zuul.threadPool.useSeparateThreadPool=true
zuul.threadPool.threadPoolKeyPrefix=zuulgw

logging.file.name=/src/files/emisores/proxy.log
logging.file.path=/src/files/emisores/
logging.file.max-size=150MB
```

![imagen](https://user-images.githubusercontent.com/2791345/89346691-1a595f00-d66f-11ea-8d16-9aa3bfe52ea5.png)

**Comment by johnliucn925** [comment]
Ribbon read timeout is 90s. So zuul should return timeout back if backend takes 4-5 mins.   Maybe you could debug your application to see where is stuck. Seems your are using zuul1.x.  You could check DebugFilter is enabled.  set breakpoint at shouldFilter method. and go from there.
