### ISSUE TITLE
CounterFactory not initialized (zuul-core)

### ISSUE THREAD

**Issue by Maxeh** [Netflix/zuul#895]
We are using spring-cloud-netflix-zuul 2.2.5 (newest) with zuul-core 1.3.1 (newest 1.x version; default from zuul pom) and run into the issue that exceptions are not correctly logged, as they are replaced with the exception `java.lang.IllegalStateException: CounterFactory not initialized` thrown in ZuulException.java. Shouldnt there be a DefaultCounterFactory that is used normally? We tried to manually set `CounterFactory.initialize(new EmptyCounterFactory());` but the error still occurred and the original error was not logged. So we are currently in a situation that we see thousands of error logs on production and do not know why they are shown and we cannot reproduce it locally, as locally the DefaultCounterFactory is set. It seems that somehow the CounterFactory is reset or set to null and then the error occurs. Do you know if there is a fix for it? 

As this behavior seems to have changed in newer zuul-core versions (2.x), I was wondering if it would be possible to use a newer zuul-core version with spring-cloud-netflix-zuul 2.2.5? Could there be any problems to use spring-cloud-netflix-zuul 2.2.5 with the newest zuul-core?

Thanks a lot!

Edit: After reading about Zuul2 it seems it is not possible to use it simply with spring. Still the question how I can fix the issue with "CounterFactory not initialized".

**Comment by carl-mastrangelo** [comment]
Im afraid we dont support Zuul 1 any more, and Zuul 2 is not compatible with Spring.    Zuul 1 is before my time on this project, so I don't think I can help.
