### ISSUE TITLE
Zuul2 with GraphQL - Multiple proxy endpoint requests from a single request

### ISSUE THREAD

**Issue by rafaelGuerreiro** [Netflix/zuul#902]
Hello, I'm looking tirelessly into the code to find a way to do the above using Zuul 2 **without** Springboot.

I'm implementing a GraphQL Stitching InboundFilter that will build REST requests from the incoming GraphQL request, but sometimes a query might include multiple REST request to the microservice. Is there a way to create HttpRequestMessages and queue them from within an Inbound filter?

**Comment by artgon** [comment]
Zuul won't be a great candidate for that kind of use case as it's not intended to create multiple outbound requests for a single inbound request. You could make it work with filters but then you're basically building your own proxy anyway.
