### ISSUE TITLE
Cookies are not forwarded

### ISSUE THREAD

**Issue by ghost** [Netflix/zuul#913]
With the following configuration the forwarding of cookies does not work

zuul:
  ignored-headers: Access-Control-Allow-Origin, X-Frame-Options, Access-Control-Allow-Credentials, Vary, Access-Control-Allow-Credentials
  **sensitive-headers: Cookie,Set-Cookie,Authorization,LocalCookie**
  host:
    socket-timeout-millis: 600000
...
...
...

    sessioncontrol:
      path: /sessioncontrol/login/**
      **sensitive-headers: Cookie,Set-Cookie,Authorization,LocalCookie**
      url: 'http://localhost:8082/sessioncontrol/login'
      stripPrefix: true
...
...
...

-------------------------------------------------
-------------------------------------------------

But it works with this

zuul:
  ignored-headers: Access-Control-Allow-Origin, X-Frame-Options, Access-Control-Allow-Credentials, Vary, Access-Control-Allow-Credentials
  **_sensitive-headers: Cookie,Set-Cookie,Authorization,LocalCookie_**
  host:
    socket-timeout-millis: 600000
...
...
...

    sessioncontrol:
      path: /sessioncontrol/login/**
      **_sensitive-headers:_**
      url: 'http://localhost:8082/sessioncontrol/login'
      stripPrefix: true

...
...
...

**Comment by artgon** [comment]
Please direct this question to the Spring project.

**Comment by Pranav014** [comment]
What exactly to do here. I sthe issue resolved as it saysthat second part works...??
