### ISSUE TITLE
REST calls or HTTP calls from zuul 2

### ISSUE THREAD

**Issue by GitJelly** [Netflix/zuul#914]
I want to create a synchronous or asynchronous call from ZUUL2 apigateway to my authentication microservice. How do I do that? What to use? Any code examples?

**Comment by artgon** [comment]
If you're going to make an external call you should use an async filter. See example here: https://github.com/Netflix/zuul/blob/master/zuul-sample/src/main/groovy/com/netflix/zuul/sample/filters/inbound/SampleServiceFilter.groovy

**Comment by GitJelly** [comment]
I want the code for the method makeSlowRequest()

Where is the code for the SampleService??  -> import com.netflix.zuul.sample.SampleService

return sampleService.makeSlowRequest().map({ response ->
            log.info("Fetched sample service result: {}", response)

The Java http client is working for JAVA filters but failing for groovy filters. 
Says this:

2020-11-09 13:45:26,665 ERROR com.netflix.zuul.netty.filter.BaseZuulFilterRunner [Salamander-ClientToZuulWorker-0] Filter Exception: filter=xyz.apigateway.livefilters.inbound.HttpReq, request-info=uri=https://localhost:8443/healthz, method=get, clientip=172.24.0.1, msg=

Unable to make protected java.net.http.HttpRequest() accessible: module java.net.http does not "opens java.net.http" to unnamed module @25bbf683


java.lang.reflect.InaccessibleObjectException: Unable to make protected java.net.http.HttpRequest() accessible: module java.net.http does not "opens java.net.http" to unnamed module @25bbf683
                     
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:341)

**Comment by GitJelly** [comment]
Greetings.
Your suggestion worked for me. Thank you so much.

**Comment by GitJelly** [comment]
Btw, I also wanted to ask if ZUUL2 provides any inbuilt library/module to make http client/requests?
In my code I used java.net.httpclient.  Is there a more sophisticated way?
