### ISSUE TITLE
[question]How to skip Inbound filter processing ?

### ISSUE THREAD

**Issue by rajc28** [Netflix/zuul#916]
How to stop further inbound filter processing based on a condition by setting "context.setEndpoint(Proxyendpoint)"  ?

I tried to use SessionContext.stopFilterProcessing() but it's stopping the entire filter processing including outbound filters.

**Comment by artgon** [comment]
There is no mechanism to stop only inbound filter processing, but you can check if the endpoint is set in the `shouldFilter` method of subsequent filters.

**Comment by rajc28** [comment]
Is there any way to skip few filters in runtime?

Example : 

We have filters in the below order
filter1
filter2
filter3
filter4

In filter2 based on our business logic can we skip subsequent filters(filter3, filter4) or skip any particular filter(filter3) ?

**Comment by johnliucn925** [comment]
Here are few things we are doing, for your reference: 
1. We defined some configuration, and filter can be skipped based on configuration value. e.g auth filter or rate limit filter will run only if configured to run for certain request. 
2. We defined some base filters on top of zuul filter, add our logic to skip filters at runtime.

**Comment by rajc28** [comment]
I understand that we can check on every filter whether to execute it or not based on a condition but I am looking for a way through which we can stop further inbound filter processing based on a condition on first filter itself.

But looks like there is no way to stop only inbound filter processing.
