### ISSUE TITLE
How to configure Zuul2 as reverse proxy?

### ISSUE THREAD

**Issue by SMakhrov** [Netflix/zuul#943]
Hi!

Could you tell how to configure Zuul2 as reverse proxy without Eureka?
For example, if I want all requests which sending to http://localhost route to https://some-app.s3-us-west-2.amazonaws.com ?
For example if I open http://localhost/index.html I need to be proxied to https://some-app.s3-us-west-2.amazonaws.com/index.html

I have tried different configurations but got 301 Moved permanently instead proxy pass to target url.

**Comment by SMakhrov** [comment]
For example this configuration at application.properties doesn't work (I got 301 answer when try to open http://localhost/index.html):
```
zuul.server.port.main=80

# Loading Filters Paths
zuul.filters.root=com.example.cs.sample.filters
zuul.filters.packages=${zuul.filters.root}.endpoint,${zuul.filters.root}.inbound,${zuul.filters.root}.outbound

# Deactivate Eureka
eureka.shouldFetchRegistry=false
eureka.validateInstanceId=false

# Load balancing

api.ribbon.listOfServers=some-app.s3-us-west-2.amazonaws.com:80
api.ribbon.client.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
```

@artgon , could you please help me? I really can't understand how to fix it and do the simple thing with Zuul2 - reverse proxy.

**Comment by silentium59** [comment]
+1

**Comment by SMakhrov** [comment]
I guess that Zuul2 performs 2 requests to gateway from api.ribbon.listOfServers.
On first request Zuul2 got in code behind 200, and on second it got 304 Not Modified. 304 response breaks Zuul2 logics.

If I configure Spring Cloud Gateway in the same way (without Zuul1 and of course Zuul2, - pure SCG), then it works correctly.

Is it bug of Zuul2??? Or it needs some configuration? Any ideas?

**Comment by DenisovaElena** [comment]
+1

**Comment by ZhukovaSD** [comment]
+1

**Comment by SMakhrov** [comment]
I have tried to reproduce it with api.ribbon.listOfServers=httpbin.org:80 - it works.
But for amazon S3 it doesn't work - api.ribbon.listOfServers=some-app.s3-us-west-2.amazonaws.com:80 (it's fake url, you can create your own public s3 to test it).

**Comment by dark-kraft** [comment]
+1

**Comment by dimazubenko** [comment]
+1

**Comment by lab85-ru** [comment]
Cool !

**Comment by SMakhrov** [comment]
A month has passed and there is no any answer. Zuul 2 is no longer supported? 
@carl-mastrangelo, @artgon ?
