### ISSUE TITLE
Duplicate headers in multithreaded request processing

### ISSUE THREAD

**Issue by nayutalienx** [Netflix/zuul#962]
Hello.
We have the following case: 
The application has a request filter that adds a custom http header for some redirection. With a surface code check, it seems that everything is OK. But there is such a case that the new request has a header that we previously added to send to the down recipients. And the strangest thing is that the code that adds this header is located below.

Normal behavior:
![image](https://user-images.githubusercontent.com/47031833/102891838-f5c02100-446f-11eb-810b-26bdf8e1a4fe.png)

Strange behavior:
![image](https://user-images.githubusercontent.com/47031833/102892098-6ff0a580-4470-11eb-8c1c-a91699b78898.png)

**Comment by carl-mastrangelo** [comment]
Are you sure another filter in the chain didn't add it?  In other words, if you change the header name in RequestFilter, do you end up with two headers?   There case I think is maybe that filter is executed twice, but maybe not multithreaded.

**Comment by nayutalienx** [comment]
There is only one filter(test project for issue). I also tried to research double processing request in filter and figured out that requestHeaders links and cached to thread that was executed early: Here is examples with timestamp data: 
![image](https://user-images.githubusercontent.com/47031833/103148356-cf4ffd80-476f-11eb-856c-af7b05cd95a3.png)

**Comment by nayutalienx** [comment]
If you want to try it by yourself, here`s project https://github.com/nayutalienx/zuul-test
