### ISSUE TITLE
OriginConnectException

### ISSUE THREAD

**Issue by SMakhrov** [Netflix/zuul#963]
Hi!

Under load tests Zuul2 fails with the following error. How to tune Zuul2 for avoid it?

`DEBUG com.netflix.zuul.netty.insights.PassportLoggingHandler [Salamander-ClientToZuulWorker-3] State after complete. , context-error = com.netflix.zuul.netty.connectionpool.OriginConnectException: maxConnectionsPerHost=50, connectionsPerHost=50, current-http-reqs = 46, toplevelid = 7464ce0b-575e-446e-936d-e0177d31bbcd, req = uri=https://test:80/index.html, method=get, clientip=192.168.147.37, attempts = [{"status":-1,"duration":0,"attempt":1,"error":"ORIGIN_ORIGIN_SERVER_MAX_CONNS","exceptionType":"OriginConnectException","region":"UNKNOW","instanceId":"test123.s3-us-west-2.amazonaws.com:80","readTimeout":5000,"connectTimeout":2000}], passport = CurrentPassport {start_ms=1609206360921, [+0=IN_REQ_HEADERS_RECEIVED, +114391=FILTERS_INBOUND_START, +1387513=IN_REQ_LAST_CONTENT_RECEIVED, +34975764=FILTERS_INBOUND_END, +35016527=ORIGIN_CONN_ACQUIRE_START, +35018242=ORIGIN_CONN_ACQUIRE_FAILED, +35075970=FILTERS_OUTBOUND_START, +35089510=FILTERS_OUTBOUND_END, +35110908=OUT_RESP_HEADERS_SENDING, +35127608=OUT_RESP_LAST_CONTENT_SENDING, +35155862=OUT_RESP_HEADERS_SENT, +35156733=OUT_RESP_LAST_CONTENT_SENT, +35191918=SERVER_CH_CLOSE, +35194983=SERVER_CH_CLOSE, +35242562=NOW]}`

**Comment by bogiErdei** [comment]
Hi! I have the same problem too. Is there a solution for this?
