### ISSUE TITLE
Is it possible to suspend/resume a request ?

### ISSUE THREAD

**Issue by arshadwkhan** [Netflix/zuul#974]
I have implemented dynamic rate limiting where I queue and suspend the request as it arrives. When the server is ready to service, the request is resumed. Please let me know if its possible to suspend/resume the request in Zuul ?

Thanks

**Comment by carl-mastrangelo** [comment]
Yes, A zuul filter is async, and may pause.   Use the higher level ZuulFilter.apply, which support async processing.

**Comment by arshadwkhan** [comment]
Great. Is there some documentation or example you can point me to ?

**Comment by arshadwkhan** [comment]
Is this product being supported anymore ?

**Comment by arshadwkhan** [comment]
Looking to suspend an incoming request and queue it and later dequeue and resume the request. Can somebody help me to understand if this is possible using zuul2 ?
