### ISSUE TITLE
Systemd drop-in files that are used while running zuul on CentOs 7 cause an error

### ISSUE THREAD

**Issue by jnhemant** [Netflix/zuul#977]
The systemd drop-in file has ```EcecStart=/usr/bin/nodepool-launcher``` while the nodepool-launcher.service file present at /etc/systemd/system contains ```ExecStart=/usr/local/bin/nodepool-launcher```. On locating the nodepool-launcher in CentOs, I found that the nodepool-launcher directory is present at /usr/local/bin, and not in /usr/bin. So, modifying the drop-in file(centos.conf) such that ```ExecStart=/usr/local/bin/nodepool-launcher``` solved the issue for me. Initially, it gave this error:
 ```● nodepool-launcher.service - Nodepool Launcher Service
   Loaded: loaded (/etc/systemd/system/nodepool-launcher.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/nodepool-launcher.service.d
           └─centos.conf
   Active: failed (Result: exit-code) since Fri 2021-01-15 12:38:49 IST; 5s ago
  Process: 20664 ExecStart=/usr/bin/nodepool-launcher (code=exited, status=203/EXEC)
 Main PID: 20664 (code=exited, status=203/EXEC)
 ```
 
The same error is observed while starting zuul-scheduler, zuul-executor and zuul-web.

**Comment by carl-mastrangelo** [comment]
I think you opened this issue in the wrong repo.   That isn't related to the Zuul product.
